### ISSUE TITLE
On Forms some properties have not dropdown menu instead have simple text

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#100]
I tried some properties of Form container.
Some properties which are fixed need to be in a dropdown menu like BorderStyle, ControlBox, Enabled, FormStyle, ModalResult, StartPosition, WindowState etc. These properties are mostly true/false and fixed values 0-some value, 1-some value etc...

Instead of dropdown menu these properties are simple text with unknown values to developer (no manual, no help text)

It would be grate improvement to set these fixed values in dropdown menus.

Thanks.

**Comment by XusinboyBekchanov** [comment]
Until now it is available in the Windows version, I have to add it to the Linux version too.

**Comment by demosthenesk** [comment]
This dropdown menus issue may be affect and other controls with fixed values.
I am waiting the linux version to be complete, so i can start describing them in my book.
Thanks!

**Comment by XusinboyBekchanov** [comment]
Improved: Property Grid in Linux:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/3adf1e09939b15ea3b6cdf9a7dfc71ebf3230711

Fixed: TextBox GotFocus and LostFocus event in Linux:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/a3162991c05f591993339fa4d9451b9dbbbaf199

**Comment by demosthenesk** [comment]
fixed
