### ISSUE TITLE
On Form designer the Properties tab and Events tab close when lost focus.

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#101]
When i design a form and have open properties tab or Events tab, they close when lost focus. For example when i click the form.

Could it stay open? And close only when i click the Properties or Event tab ?

**Comment by XusinboyBekchanov** [comment]
To do this, you need to click on the tab one of them twice or on the pin button. Then these windows are fixed.

**Comment by XusinboyBekchanov** [comment]
![image](https://user-images.githubusercontent.com/32607344/130421144-fe4adb7e-6f98-4e00-917f-7fea2521c612.png)

**Comment by demosthenesk** [comment]
ok
