### ISSUE TITLE
Drag and drop files doesn't work

### ISSUE THREAD

**Issue by W98X** [XusinboyBekchanov/VisualFBEditor#102]
The "ondropfile" event set for a control or form doesn't trigger. 

The form or control doesn't accept files to be dragged and dropped on it from Windows Explorer.

The VFBE property grid doesn't have a property for "WS_EX_ACCEPTFILES"; which is what needs to be set, so the "ondropfile" event can be triggered.

**Comment by XusinboyBekchanov** [comment]
Added: AllowDrop property to Control:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/4bfe4da9540401675070793ca6956b7f9f4d5feb

**Comment by W98X** [comment]
I tested it and it works! :thumbsup:

Drag and drop files is so easy to do in VFBE now. It's only about 3 mouse clicks. :grinning:

Many thanks!
