### ISSUE TITLE
In linux cannot save Form1.frm...strange behavior of saving files

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#104]
1) Create a Project1
2) Add a Form1.frm
3) Save Project and Form1. While saving Form1.frm asks for overwrite !!!
4) Make changes to Form1.frm
5) Save again Form1.frm. Asks to Save As file !!!
6) Form1.frm does not appear in project folder
7) I found Form1.frm file in /home/user and installation path of VisualFBEditor

**Comment by XusinboyBekchanov** [comment]
I need to check this. I can’t say anything without checking.

**Comment by XusinboyBekchanov** [comment]
Fixed: SaveFileDialog FileName property:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/18624df89925a48f441e114787f796419463239b

**Comment by demosthenesk** [comment]
ok fixed.
