### ISSUE TITLE
In linux, compiler and includes paths are wrong

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#105]
compiler path
.//home/user/Bin/FreeBASIC-1.08.1-ubuntu-20.04-x86_64/bin/fbc

include paths same
..//path

**Comment by XusinboyBekchanov** [comment]
This is a known problem to me. I didn’t pay enough attention before. I have always removed the first two characters. I'll fix it when I'm at home.

**Comment by XusinboyBekchanov** [comment]
Fixed: Adding extra characters when selecting files and folders:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/8075a28b02f5c2ca2f53d8af065338f4f48dd330

**Comment by demosthenesk** [comment]
fixed
