### ISSUE TITLE
In linux, xterm argument is wrong

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#107]
xterm has -bc as argument
better is
xterm -e

**Comment by XusinboyBekchanov** [comment]
Improved: Changed xterm command line to -e:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/03e1798b475c168721683d1ff4b9b09ef8439320

**Comment by demosthenesk** [comment]
ok closed!
