### ISSUE TITLE
project path settings does not affect anything

### ISSUE THREAD

**Issue by rexxitall** [XusinboyBekchanov/VisualFBEditor#11]
In the preferences you can enter the path for your projects.
It does not matters even if you edit the init file. The editor will always open in his main directorty

**Comment by XusinboyBekchanov** [comment]
According to the current rule, the Projects path will be opened at the first opening; at the next opening, the last open path is used.
I have now changed this rule a little differently. When you save an existing file, the path of the existing file opens; when you save a new file, the Projects path opens. When opened, the Projects path is always used.
I will update the program later.

**Comment by XusinboyBekchanov** [comment]
Added Project Path initial dir on Open Project
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/8ce04269dec50d09a6378ce5c3400809d18cae4e

**Comment by XusinboyBekchanov** [comment]
Fixed Save new file to Projects path:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/ddcdec8863b13b9015cbb282de72536d9087d046
