### ISSUE TITLE
Listview control doesn't have a property for gridlines

### ISSUE THREAD

**Issue by W98X** [XusinboyBekchanov/VisualFBEditor#117]
The listview control is missing a property which enables to toggle gridlines on/off
 
And there are some other properties for the listview which are also missing:

- "full row select" 
- "border select"
- "header drag drop"
- "checkboxes"
- "LVM_SETHOVERTIME"
- "LVS_EX_LABELTIP"

**Comment by XusinboyBekchanov** [comment]
Added: AllowColumnReorder, BorderSelect, CheckBoxes, GridLines, HoverTime, FullRowSelect, LabelTip properties to ListView:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/0eb1b5c94721cf6533d402883a169800e237d918

**Comment by W98X** [comment]
I tested it and there is problems. 

The extended styles for the listview aren't working properly:

- When labeltip is set to true, the scrollbar for the listview appears on the left!
- Checkboxes don't appear

It's because listview extended styles need to be set according to the reasons explained here:
https://stackoverflow.com/questions/18031987/list-view-control-ignores-extended-styles

**Comment by XusinboyBekchanov** [comment]
Fixed: AllowColumnReorder, BorderSelect, CheckBoxes, LabelTip properties of ListView:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/0bf3bc0cda7e508055f3d3ea487aff403cac552c

Thanks for the link.

**Comment by XusinboyBekchanov** [comment]
Updated:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/8e4164ac2334adc392ea3734f302b7703f621395

**Comment by W98X** [comment]
I tested it, and it's working now :thumbsup:

Now I am able to toggle gridlines and the other listview properties on/off whilst the exe is running. 

VFBE makes it so easy to do. 😄 

Many thanks.

**Comment by XusinboyBekchanov** [comment]
Added: Checked property to ListViewItem:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/b0fae5e091e6a9292414bb5fb350e20c7884907d

**Comment by W98X** [comment]
Yes, listview checkboxes can be toggled whilst the exe is is running now. 🧮 

In case anybody out there is wondering how 🕵️ :mag:, it's done with the following code:

`listview1.ListItems.Item(2)->Checked = True ` 📋 

(The above code sets the checkbox for the no2 (zero based) checkbox in the list view )

**Comment by XusinboyBekchanov** [comment]
Yes, that's right.

**Comment by XusinboyBekchanov** [comment]
Fixed: ListViewItem Checked property:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/21cf5b283ab329e7dbe363c318d44fbcf96a25ab

Now the Checked property is possible in the constructor.

**Comment by W98X** [comment]
Example of listview items added in the constructor, including showing how to add text to a subitem / 2nd column:
![vfbe-listview-added-in-constructor-example](https://user-images.githubusercontent.com/88371717/131416806-46d829fc-7a78-489c-b3eb-82ec9010f750.png)
