### ISSUE TITLE
In linux, Form Backcolor does not work properly

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#119]
Whatever color i choose i get a black color finally for form backcolor.

And how i use Form.Forecolor ?

**Comment by XusinboyBekchanov** [comment]
Fixed: Color property of ColorDialog:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/7de0e48b0c66ae28e4dd61f168820c8ac14f70d4

> And how i use Form.Forecolor ?

Can be used when printing on a Form. It works fine in Windows. But in Linux it doesn't print unless the color is black (this needs to be fixed).

**Comment by demosthenesk** [comment]
ok fixed!
