### ISSUE TITLE
In linux, Delete CommandButton1 crashes IDE if it is set as CancelButton or DefaultButton

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#120]
If i have set as Form CancelButton or DefaultButton a CommandButton and try to Delete the button from designer the IDE crashes.
Also it would be better if i could set CancelButton to None so i can unset it from properties grid.

**Comment by XusinboyBekchanov** [comment]
> Also it would be better if i could set CancelButton to None so i can unset it from properties grid.

Added: The ability to select an empty component in the Properties grid:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/7a1606d8e86b5e501c41a5c23534a84a5cf7f7f5

**Comment by demosthenesk** [comment]
The ability to select an empty component in the Properties grid is ok. FIXED!

In linux and Windows, Delete CommandButton1 crashes IDE if it is set as CancelButton or DefaultButton, not fixed.
In Windows cannot delete button with delete key from keyboard. I can delete from pop up menu with right click and Delete command.

**Comment by XusinboyBekchanov** [comment]
Fixed: Form ActiveControl property in Design mode:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/b9a0331e50d091257871bd03ec5a85ae8984348e

Fixed: Delete Controls from Designer:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/037a5d6e4cd7d2033d7660b0daa0d0a0df6a3b50

> In Windows cannot delete button with delete key from keyboard. I can delete from pop up menu with right click and Delete command.

The delete key should work

**Comment by demosthenesk** [comment]
ok fixed the crash in linux and windows.
But in windows cannot delete any control with delete from keyboard, sometimes
