### ISSUE TITLE
In linux, Form WindowState is not working

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#123]
I set the Form's WindowState to 1-wsNormal, 2-wsMaximized, 3-wsMinimized but it has no effect at running form.

**Comment by XusinboyBekchanov** [comment]
Fixed: Form WindowState in Linux:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/213f5e6aab25fb1c2fd00dd996d8ca079203ff2e

**Comment by demosthenesk** [comment]
ok fixed.
