### ISSUE TITLE
In Windows 10, when set Form WindowState, form disapears from designer

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#124]
Set Form WindowState to any value, the form in designer disapears.

**Comment by XusinboyBekchanov** [comment]
Fixed: Form WindowState property:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/4983a0a401fb2f12abd1c5b9686d88037c222b7e

**Comment by demosthenesk** [comment]
fixed!
