### ISSUE TITLE
In Linux, property detached from grid and follows scrolling

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#125]
If i click a property from property grid and scroll down or up the property grid, then the focused property is following the scrolling up and down.

see video.

https://user-images.githubusercontent.com/1350282/131125928-ecbe4f3c-5804-469b-b5b7-36cc268d6955.MP4

**Comment by XusinboyBekchanov** [comment]
Added: OnEndScroll event to ListView and TreeListView in Linux:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/04cbc0541cec4e0135363b7d56ccd599bfd03a25

Fixed: Property Grid on scrolling in Linux:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/484cc63253f4c2292dfe2f8fa25a6ec6bebe6684

**Comment by demosthenesk** [comment]
fixed!
