### ISSUE TITLE
In linux, drag n drop does not work.

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#126]
1) Drag n drop does not work in linux.
2) What happens if i dnd many files at once ?

**Comment by XusinboyBekchanov** [comment]
Added: OnDropFile event to Control in Linux:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/be6d3e2b87fb3912c96316d0b6fa8e8581b144d8

**Comment by demosthenesk** [comment]
i get error:
/home/user/Downloads/VisualFBEditor-master/MyFbFramework/mff/Control.bas(1595) error 71: Incomplete type, before 'data'

**Comment by XusinboyBekchanov** [comment]
Fixed: OnDropFile event in GTK3:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/708b0c0939815a2ca435d842df9010de20324617

**Comment by demosthenesk** [comment]
fixed!
