### ISSUE TITLE
In linux, Constraints have no implementation yet.

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#127]
Constraints do not work in linux yet.

**Comment by XusinboyBekchanov** [comment]
Added: Contraints property to controls in Linux:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/06e46c4f9607f4b5cda900bfbff950a730c01d84

**Comment by demosthenesk** [comment]
How do i test Contraints ?
Is there an example project please ?

**Comment by XusinboyBekchanov** [comment]
Here:
```
#ifdef __FB_WIN32__
	'#Compile "Form1.rc"
#endif
'#Region "Form"
	#include once "mff/Form.bi"
	
	Using My.Sys.Forms
	
	Type Form1Type Extends Form
		Declare Constructor
		
	End Type
	
	Constructor Form1Type
		' Form1
		With This
			.Name = "Form1"
			.Text = "Form1"
			.Constraints.Top = 80
			.Constraints.Width = 200
			.SetBounds 0, 0, 350, 300
		End With
	End Constructor
	
	Dim Shared Form1 As Form1Type
	
	#ifndef _NOT_AUTORUN_FORMS_
		#define _NOT_AUTORUN_FORMS_
		
		Form1.Show
		
		App.Run
	#endif
'#End Region
```

**Comment by demosthenesk** [comment]
Strange behavior of Form with Constraints in linux

https://user-images.githubusercontent.com/1350282/132996219-84b2fbbf-501f-4da7-9fd3-c32f1e12e9f2.MP4

**Comment by demosthenesk** [comment]
What is the purpose of Constraints ?
if you try to move the form it makes strange movement...

**Comment by XusinboyBekchanov** [comment]
The goal is to prevent changes to the boundaries specified in the properties.

**Comment by XusinboyBekchanov** [comment]
On Windows, you can check how it works.

**Comment by demosthenesk** [comment]
fixed!
