### ISSUE TITLE
In linux, opacity does not work in run time.

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#128]
Opacity of a form works in designer but not in run time

**Comment by XusinboyBekchanov** [comment]
Doesn't it really work for you? Why does it work for me. Here's some information on this:
https://developer.gimp.org/api/2.0/gtk/GtkWindow.html#gtk-window-set-opacity

"X screens with a compositing manager running" does it work for you?

**Comment by demosthenesk** [comment]
i don't know what is a compositing manager and what manager ubuntu-mate 20.04 has?
in my laptop with ubuntu-mate 20.04 does not work in run time...it works in design mode.

**Comment by XusinboyBekchanov** [comment]
Does this print true or false?
```
Private Sub Form1.Form_Create(ByRef Sender As Control)
	?gtk_widget_is_composited(widget)
End Sub
```

**Comment by demosthenesk** [comment]
> Does this print true or false?
> 
> ```
> Private Sub Form1.Form_Create(ByRef Sender As Control)
> 	?gtk_widget_is_composited(widget)
> End Sub
> ```
i get these errors
![Screenshot at 2021-08-30 11-52-54](https://user-images.githubusercontent.com/1350282/131313652-3376a54f-d078-48cf-88c4-a41b8cb34051.png)

**Comment by XusinboyBekchanov** [comment]
Fixed: Form Hide property in GTK2 (in Linux):
https://github.com/XusinboyBekchanov/MyFbFramework/commit/0bcf40161697a495256894e71707ca2cd7cfb273

**Comment by demosthenesk** [comment]
> Does this print true or false?
> 
> ```
> Private Sub Form1.Form_Create(ByRef Sender As Control)
> 	?gtk_widget_is_composited(widget)
> End Sub
> ```
It Prints 1 , so true

**Comment by demosthenesk** [comment]
i set opacity to 100 from range 0-255.
in designer it is partcial transparent OK
in run time it is not, it is opaque

**Comment by XusinboyBekchanov** [comment]
Please try to set at the beginning of includes #define __USE_GTK3__, maybe it works in gtk3.

**Comment by demosthenesk** [comment]
> Please try to set at the beginning of includes #define **USE_GTK3**, maybe it works in gtk3.
> 
> ```
> #define __USE_GTK3__
> #include once "mff/Form.bi"
> ```

I tried but is the same...the bug exists too.
I don't understand, in design mode the opacity works! In run time it doesn't.
Could you find and copy the code from design mode?

**Comment by XusinboyBekchanov** [comment]
Here's the code that's the same everywhere:
```
Property Form.Opacity(Value As Integer)
		FOpacity = Value
		#ifdef __USE_GTK__
			#ifdef __USE_GTK3__
				gtk_widget_set_opacity(widget, Value / 255.0)
			#else
				gtk_window_set_opacity(gtk_window(widget), Value / 255.0)
			#endif
		#else
			ChangeExStyle WS_EX_LAYERED, Cast(Boolean, 255 - FOpacity)
			If FHandle Then
				SetLayeredWindowAttributes(FHandle, 0, FOpacity, LWA_ALPHA)
			End If
		#endif
	End Property
```

In some places it is written that the form will be transparent if you set the property after showing the form.

**Comment by demosthenesk** [comment]
Well i have some news...
i installed Gnome on Ubuntu Mate 20.04. In Gnome the opacity works just fine !!!
This issue is only about Mate. For some reason in Mate opacity does not work in run time.... i don't know why...!
I test also Trinity (The old KDE3.5), opacity does not work there too.

**Comment by demosthenesk** [comment]
i think we can close this issue... it is an issue of desktop manager not MyFbFramework or VFBE...!

**Comment by XusinboyBekchanov** [comment]
>For some reason in Mate opacity does not work in run time.... i don't know why...!

In the designer it is a container (gtklayout), and in runtime it is a window (gtkwindow).

**Comment by demosthenesk** [comment]
> > For some reason in Mate opacity does not work in run time.... i don't know why...!
> 
> In the designer it is a container (gtkbox), and in runtime it is a window (gtkwindow).

I think its a GTK and Desktop Manager issue.

**Comment by XusinboyBekchanov** [comment]
Yes, right
