### ISSUE TITLE
In Linux and Windows ImageBox Graphics does not load a png picture...not try other format.

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#129]
In linux when try to load a png image to image manager the IDE freezes.
In windows the png is loaded to image manager but the ImageBox disapears from design if try to change the size with loaded image.

**Comment by XusinboyBekchanov** [comment]
> In windows the png is loaded to image manager but the ImageBox disapears from design if try to change the size with loaded image.

Fixed: ImageBox resizing on select image:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/84227c06c0ee28b352d3719a44a91e52fa4586de

**Comment by XusinboyBekchanov** [comment]
> In linux when try to load a png image to image manager the IDE freezes.

Fixed: Property grid edit combo in Linux
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/a68aba40784ec17abde16bc75885027f263f2298

Fixed: Bitmap and Graphic LoadFromResourceID functions in Linux:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/7d2dfcc47144c214f4fcda037155ce1760fb34c5

**Comment by XusinboyBekchanov** [comment]
In Linux, for the property Graphic to work in run time, the image file must be located in the "path to the executable file/resources" or "path to the executable file/Resources" folder, or you must specify the path to the file:
```
                ' ImageBox1
		With ImageBox1
			.Name = "ImageBox1"
			.SetBounds 80, 60, 100, 60
			' File name from the Resources folder (can receive files with the extension .png, .ico, .xpm)
			.Graphic = "Add"
			' Image file path
			.Graphic = "./Resources/Add.png"
			' or
			.Graphic.LoadFromFile("./Resources/Add.png")
			.Parent = @This
		End With
```

**Comment by demosthenesk** [comment]
In Linux, png image loads in design mode, but not shown in runtime mode

**Comment by XusinboyBekchanov** [comment]
I'll take a look in the evening.

**Comment by XusinboyBekchanov** [comment]
Fixed: ImageBox events:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/c4e12fdacd11e98d460df46fecbdaa22da7102d5

OnMouseHover in Linux is not yet implemented in other controls either.

**Comment by XusinboyBekchanov** [comment]
> In Linux, png image loads in design mode, but not shown in runtime mode when it is with Resource name.

For this, the file must be in the folder "path to the executable file/resources" or "path to the executable file/Resources"

**Comment by demosthenesk** [comment]
In linux, png image not shown in design mode or runtime mode when it is with "resource name"
```
		With ImageBox1
			.Name = "ImageBox1"
			.Text = "ImageBox1"
			.SetBounds 100, 100, 160, 120
			**.Graphic = "git"**
			.Parent = @This
		End With

```
i try to load ./Resource/git.png

**Comment by XusinboyBekchanov** [comment]
>In linux, image png does not load in design when it is relative path.
`.Graphic = "./Resources/git.png"`

Fixed: Setting the Graphic property to a relative path:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/6925ddd5310befa86a6fe2dad7fdcf39f2553b8b

**Comment by XusinboyBekchanov** [comment]
>1. In linux, png image not shown in design mode or runtime mode when it is with "resource name"

>3. In linux, Graphics value of properties does not update from code editor

Here:
https://user-images.githubusercontent.com/32607344/131943887-f0bcd114-48c6-44d2-9a0d-df34e1fac394.mp4

Changed your project:
[Project4.zip](https://github.com/XusinboyBekchanov/VisualFBEditor/files/7103034/Project4.zip)

**Comment by demosthenesk** [comment]
fixed!
