### ISSUE TITLE
Remove file from Project has strange behaviour

### ISSUE THREAD

**Issue by rexxitall** [XusinboyBekchanov/VisualFBEditor#13]
To get rid a file out of the project you has made the [-] Button.
It does not update the file list and also not always remove the file from the project.

**Comment by XusinboyBekchanov** [comment]
I did not detect this behavior.

**Comment by rexxitall** [comment]
If you will add the buttons it might be gone or at least you will see it :)
FB could be really a nice product if finally got a IDE worth using ready. 
You are not that far from that :) The format option is great. For example.
A little bit fine tuning and maybe make it a little bit more near to the VB6 or VBA IDE (Shortcuts). Things people will feel immediatly homy and familar with it. :)
