### ISSUE TITLE
In Linux, varius Form Events are not implemented yet.

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#130]
The following Form events are missing from linux version.

1. OnActivate
2. OnActivateApp
3. OnDeactivate
4. OnHide
5. OnScroll
6. OnTimer

**Comment by XusinboyBekchanov** [comment]
Added: Form OnHide event in Linux:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/c3a84394c7f69addd41a21c966d81e91442e34b5

**Comment by XusinboyBekchanov** [comment]
Added: OnActivate, OnActivateApp, OnDeactivate, OnDeactivateApp event to Form in Linux; Removed: OnFree, OnTimer event from Form in Linux
https://github.com/XusinboyBekchanov/MyFbFramework/commit/ed117305d7c184671cc1f30f599fdd5d1512ba2c

OnScroll was added beforehand.

**Comment by demosthenesk** [comment]
fixed!
