### ISSUE TITLE
Feature Request: Add OnMove event for Forms and controls

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#131]
Can we add the OnMove event which occurs when an object moves in screen or in a container or MDI Form ?

**Comment by XusinboyBekchanov** [comment]
Added: OnMove event to Controls:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/4f766606c46858be8bc85ae15a2785bd563e2de9

**Comment by demosthenesk** [comment]
ok. Added!
