### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#133]
i get this error:
/home/user/Downloads/VisualFBEditor-master/src/frmMenuEditor.frm(48) error 4: Duplicated definition, BGR

**Comment by XusinboyBekchanov** [comment]
Fixed: Compiling error:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/3ddddf7f3dcc7b1bc35010ca145e0b31fc4f8d14

**Comment by demosthenesk** [comment]
ok fixed

**Comment by demosthenesk** [comment]
i get these errors
/home/user/Downloads/VisualFBEditor-master/MyFbFramework/mff/Form.bas(1138) error 42: Variable not declared, gtk_widget_visible
/home/user/Downloads/VisualFBEditor-master/MyFbFramework/mff/Form.bas(1138) error 3: Expected End-of-Line, found 'gtk_widget_visible'
/home/user/Downloads/VisualFBEditor-master/MyFbFramework/mff/Form.bas(1142) error 125: Expected 'END SUB', found 'End'
/home/user/Downloads/VisualFBEditor-master/MyFbFramework/mff/Label.bas(243) error 42: Variable not declared, Value
/home/user/Downloads/VisualFBEditor-master/src/EditControl.bas(2558) error 7: Expected ')'

**Comment by XusinboyBekchanov** [comment]
Fixed: Compile error:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/e4147f723c9d13fddd7a64304dd86953f98ab76e

Fixed: Compile error:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/d11152aba5d7ed2bed11a0b996903e5463035e9b

**Comment by demosthenesk** [comment]
fixed

**Comment by demosthenesk** [comment]
i get
/home/user/Downloads/VisualFBEditor-master/src/frmSplash.frm(34) warning 4(2): Suspicious pointer assignment

**Comment by demosthenesk** [comment]
i get these errors:
/home/user/Downloads/VisualFBEditor-master/MyFbFramework/mff/Font.bas(71) error 202: Illegal member access, found 'Widget'
/home/user/Downloads/VisualFBEditor-master/MyFbFramework/mff/Font.bas(73) error 202: Illegal member access, found 'Widget'
/home/user/Downloads/VisualFBEditor-master/MyFbFramework/mff/Font.bas(96) error 202: Illegal member access, found 'Widget'
/home/user/Downloads/VisualFBEditor-master/src/TabWindow.bi(179) error 14: Expected identifier, found 'HWND'

**Comment by XusinboyBekchanov** [comment]
Fixed: Compile error:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/31adc26478198141db8061497d4d51fced561eef

Fixed: Font:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/0c5382983a31958134f8a722fdc6ba5bf667851b

**Comment by demosthenesk** [comment]
fixed

**Comment by demosthenesk** [comment]
i get
/home/user/Downloads/VisualFBEditor-master/src/Main.bas(1801) error 18: Element not defined, AddObject
/home/user/Downloads/VisualFBEditor-master/src/Main.bas(1808) error 18: Element not defined, IndexOfObject
/home/user/Downloads/VisualFBEditor-master/src/Main.bas(1810) error 18: Element not defined, InsertObject
/home/user/Downloads/VisualFBEditor-master/src/Main.bas(1812) error 99: No matching overloaded function, CAPTION()
/home/user/Downloads/VisualFBEditor-master/src/Main.bas(1821) error 18: Element not defined, Object
/home/user/Downloads/VisualFBEditor-master/src/Main.bas(1822) error 1: Argument count mismatch, found '('
/home/user/Downloads/VisualFBEditor-master/src/Main.bas(1824) error 9: Expected expression, found '('
/home/user/Downloads/VisualFBEditor-master/src/Main.bas(2216) error 99: No matching overloaded function, TEXT()
/home/user/Downloads/VisualFBEditor-master/src/Main.bas(2222) error 24: Invalid data types, found '&'
/home/user/Downloads/VisualFBEditor-master/src/Main.bas(2231) error 99: No matching overloaded function, CONTAINS()
/home/user/Downloads/VisualFBEditor-master/src/Main.bas(2231) error 133: Too many errors, exiting

**Comment by XusinboyBekchanov** [comment]
Improved: AddItem and InsertItem method of ListControl:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/f4a650e2b5531ae55a07ed896bd586e24494d095

Fixed: Compile error:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/d5073d6d6d49327a976f8c323daea1421ee422d9

**Comment by demosthenesk** [comment]
fixed!

**Comment by demosthenesk** [comment]
i get this error in linux,
/home/user/Downloads/VisualFBEditor-master/MyFbFramework/mff/TreeListView.bas(505) error 18: Element not defined, Items

**Comment by XusinboyBekchanov** [comment]
Fixed: Compiling error:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/a6a3f9de7beef40a8df06c6a260e22af8ebb0398

**Comment by demosthenesk** [comment]
fixed!
