### ISSUE TITLE
In linux, TextBox crashes IDE

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#134]
1) Add a TextBox
2) Set WordWrap to true
3) Set Text to any value to test wrap
4) IDE freezes or crash

**Comment by XusinboyBekchanov** [comment]
Fixed: Property grid edit combo in Linux:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/a68aba40784ec17abde16bc75885027f263f2298

**Comment by demosthenesk** [comment]
1. Add a TextBox
2. Set WordWrap to true
3. Set Text to any value to test wrap
4. Text property does not work properly

**Comment by XusinboyBekchanov** [comment]
Fixed: Designer:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/bc2875398affcab1fb61331aea7161c64941488e

Fixed: TextBox WordWraps property in Design Mode:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/948d7718093e9ad5fd7b226a816d765c99c9890e

**Comment by demosthenesk** [comment]
fixed.
