### ISSUE TITLE
Feature Request: Add WordWrap in Label Control

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#135]
Add WordWrap in Label Control

**Comment by XusinboyBekchanov** [comment]
Added: WordWrap property to Label:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/9efdc5fc067d8d0ca9be190336806b82f57f4ef9

**Comment by demosthenesk** [comment]
added!
