### ISSUE TITLE
In Windows, TextBox Wordwrap is not working

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#136]
In Windows, TextBox Wordwrap is not working.
I set Wordwrap to true and enter a large text in Text property of TextBox, but word wrap is not working.

**Comment by W98X** [comment]
Textbox word-wrap was fixed in issue #91 25 days ago.

You need to set the multiline property to true aswell for it to wrap to another line.

Without the multiline property also set, it will stay stuck on 1 line and unable to wrap.

**Comment by demosthenesk** [comment]
In runtime it works the wrap and multiline
In designer it does not work

**Comment by XusinboyBekchanov** [comment]
Fixed: ScrollBars and WordWraps properties of TextBox works in design mode:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/19296f77bc52f13efa5ae05957f37fdba6627500

**Comment by demosthenesk** [comment]
fixed!
