### ISSUE TITLE
In Linux, Ctrl-C (copy), Ctrl-V (paste) in properties grid do not work 

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#139]
In Linux, Ctrl-C (copy), Ctrl-V (paste) in properties grid do not work.
Works right click - menu- Copy,Paste.

**Comment by XusinboyBekchanov** [comment]
Fixed: TextBox CutToClipboard, CopyToClipboard, PasteFromClipboard and SelectAll properties in Linux
https://github.com/XusinboyBekchanov/MyFbFramework/commit/fa43d6d812f92f7bfb36c50a8cafb7b162bf95c0

**Comment by demosthenesk** [comment]
fixed!
