### ISSUE TITLE
Feature request CONSOLE OPEN button

### ISSUE THREAD

**Issue by rexxitall** [XusinboyBekchanov/VisualFBEditor#14]
just a button to open cmd.exe in the current project directory

**Comment by XusinboyBekchanov** [comment]
I added, will update later.

**Comment by rexxitall** [comment]
Found the button :) But does nothing. Should be placed in the main Icon bar. Maybee it looks for  the wrong cmd.exe ? The 64 bit cmd is located in x:\windows\system32  and the 32 bit is located in x:\windows\WOWhatever :)

**Comment by XusinboyBekchanov** [comment]
Does your IDE open with a console or without a console?
If with the console then try to click this open console, it will appear there.
If it opens without a console, then you need to work normally.

**Comment by rexxitall** [comment]
Yes i saw it now. Might be an Idea to bring the console also to front after creation . The other problem is that if that console get closed the IDE closes also. Which is usally not wanted :) CMD has to be started independent .

**Comment by XusinboyBekchanov** [comment]
The IDE must compile with the -s gui switch. Then there will be no problem. Console mode is needed during debugging to print the values of variables.

**Comment by rexxitall** [comment]
There are some tricks with the console possible. Start one, get her window handle and you can put her in any window you create with freebasic. You just has to take care about the underlaying task. That works with every external program.  If the console is just needed for some kind of debug action this console can be started invisible. There is a win APi availeable "CreateProcess". This api you can tell not to open a real window for example.
A real "robbed" console becomes handy cause in that window you can start for exampel the FAR file manager or whatever else. Minggw Tools cygwin. Log ago KATE for linux KDE has had such a feature. Was very handy to run the midnight commander in such a window. Which then also can all cursor and color tricks withot additional coding :)

**Comment by rexxitall** [comment]
This here i usesd yesterday in VB.net to get my gdb wrapper to work. In VBA you can not really create independend tasks or threads. So it was easier to use .net :)
[fbclass.zip](https://github.com/XusinboyBekchanov/VisualFBEditor/files/4767089/fbclass.zip)
This shows also the nice trick how to get a com wrapper for free to that routines. <assembly gettype)"FB"> does that nice trick

**Comment by rexxitall** [comment]
Opens console and IDE get not closed while closing this window. Ony thing to be done is that a opened console should get the focus and comes to front, Main use for this point is usually to call some batch file inside the project to clean up things.

**Comment by XusinboyBekchanov** [comment]
The IDE must compile with the -s gui switch. Then there will be no problems. Have you tried compiling the IDE with the -s gui switch?

**Comment by XusinboyBekchanov** [comment]
Command Prompt тow will open a new window even if compiled with the -s console switch:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/aef966074ce1d1978581db3583a19d06541451fd
