### ISSUE TITLE
Splitter doesn't stay with the mouse when being dragged on high DPI

### ISSUE THREAD

**Issue by W98X** [XusinboyBekchanov/VisualFBEditor#140]
The splitter control behaves correctly on normal DPI.

However, on high DPI, on Windows10, there is a problem:

When the splitter is being dragged, it moves ahead of the mouse cursor further and further until it goes past the edge of the form. So the splitter dpi scaling has got a bug in it somewhere.

**Comment by XusinboyBekchanov** [comment]
Fixed: High DPI in Splitter:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/e15ef004ac5767c5f737c7a3db3deabd6c5b46ee

**Comment by W98X** [comment]
Yes, I just tested it and the splitter seems to be dragging correctly on high DPI now 👌 

Thanks. :grinning:
