### ISSUE TITLE
Feature request : duplicate current line in code editor

### ISSUE THREAD

**Issue by W98X** [XusinboyBekchanov/VisualFBEditor#141]
Sometimes it is necessary to duplicate a current line, such as when adding columns to a listview:
```
listview1.columns.add("col1", , 150)
listview1.columns.add("col2", , 150)
listview1.columns.add("col3", , 150)
listview1.columns.add("col4", , 150)
```
	

Therefore I am feature requesting that the current line in the code editor can be duplicated by pressing ctrl+d or some other such user configuable key combination.

Here is a screenshot showing how this feature works in FBEdit:
![fbEdit-duplicate-current-line](https://user-images.githubusercontent.com/88371717/131444067-3e868902-efa7-4e8d-b19b-8ef1af2dcfe6.png)

Here is a screenshot showing how this feature works in Scite4Autoit:
![scite-duplicate-line](https://user-images.githubusercontent.com/88371717/131444109-a85ef564-6c60-4c70-9e27-82067230a000.png)

**Comment by XusinboyBekchanov** [comment]
Added: Dublicate function to Edit menu:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/15ffb9fc1d06f6f400a085de33b3badb88f47085

**Comment by W98X** [comment]
Yes that's great, I've tested it and it works 👍 

Duplicating the current line is so easy now :grinning:

Many thanks.

However, I did notice a spelling error:

Duplicate is spelt with a 'p' not a 'b'

👉 Duplicate =  correct spelling ✔️ 
👉 Dublicate =  wrong spelling ❌

**Comment by XusinboyBekchanov** [comment]
Fixed: Wrong spelling:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/0a172909c6480f9cd236cd87b55fb88809b0467a

In Uzbek (mine) and Russian, it is Dublikat, so I was wrong.

**Comment by W98X** [comment]
The spelling was fixed quickly, so it's all good now. :thumbsup:

But one last request:

Could the menu entry have the word "Line" added after the word "Duplicate", to make it be **"Duplicate Line"**, just like how it is in the FBEdit menu (with the word "Line" on the end), just to provide that extra bit of clarity on what it does (ie duplicates the current line)

![fbEdit-duplicate-current-line-cropped](https://user-images.githubusercontent.com/88371717/131472938-707bd4e8-45e5-41c2-9d79-efe139ea09ec.png)

**Comment by XusinboyBekchanov** [comment]
Maybe so:
Duplicate Line/Control

**Comment by W98X** [comment]
I just tried in the form designer and it indeed duplicated the current control!

I didn't know that 🤦 

So it can duplicate the current line **or** the current control! 😄 

It's multi-functional.

It's all complete and perfect now. :thumbsup: Issue closed. Thanks.
