### ISSUE TITLE
The toolbar icons have gone missing in Windows

### ISSUE THREAD

**Issue by W98X** [XusinboyBekchanov/VisualFBEditor#142]
I have compiled the latest version today and now the toolbar icons have disappeared from the toolbar in recent builds for Windows 10!!!

(Menu icons remain unaffected)
![vfbe-toolbar-icons-disappeared](https://user-images.githubusercontent.com/88371717/131474887-9dea8595-acff-43bb-8c51-3f89ad85225a.png)

**Comment by XusinboyBekchanov** [comment]
I just downloaded and compiled, everything is displayed normally.

**Comment by W98X** [comment]
I have been downloading and then compiling MFF and VFBE using the same bat file for the last few weeks without any problems.

However, I have been keeping the same **VisualFBEditor32.ini** settings file in order to maintain my peferences between each compile.

After doing a careful analysis, I have diagnosed this problem as being caused by a setting inside the ini file:

`BottomClosed=true`

When this setting is set to *true* the toolbar icons disappear.

Setting `BottomClosed=false` makes the toolbar icons come back again.

However, after applying this fix, unpinning the bottom panel and left side panel makes VFBE crash.

Whilst examining the settings ini file, I also noticed a strange entry for an recent file entry:
`RecentFile=ListControl1_DropFile(ByRef Sender As Control, ByRef Filename As WString)`

That is not a file! There must be some sort of bug or corruption happening to the VisualFBEditor32.ini file.

Using a freshly downloaded VisualFBEditor32.ini file makes the toolbar icons come back. But when the left panel and bottom panels are unpinned, the toolbar icons **disappear again!**

Unpinning the left panel and bottom panel is causing problems.

**Comment by XusinboyBekchanov** [comment]
Fixed: Control Style procedure:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/3cc1bea4cb866ee9b47197a178b34dee36994eb0

**Comment by XusinboyBekchanov** [comment]
> Whilst examining the settings ini file, I also noticed a strange entry for an recent file entry:
> RecentFile=ListControl1_DropFile(ByRef Sender As Control, ByRef Filename As WString)
> 
> That is not a file! There must be some sort of bug or corruption happening to the VisualFBEditor32.ini file.
 
This could have been due to the error shown above.

**Comment by W98X** [comment]
Yes! That's fixed it!
The icons are back now and it's not crashing when unpinning the panels :thumbsup:

Thanks.

**Comment by XusinboyBekchanov** [comment]
Thank you too for information.
