### ISSUE TITLE
In linux, Image Manager needs redesign

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#143]
in linux, image manager needs to be like windows.
Without 16x16 image etc...just image load and preview

**Comment by XusinboyBekchanov** [comment]
Yes, I need to fix it, the controls from ImageListEditor appeared there by mistake.

**Comment by XusinboyBekchanov** [comment]
Fixed: Form Show Invisible Controls:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/7609a0052c000fba854aaf9df9017581ef76ccfd

**Comment by demosthenesk** [comment]
fixed.
