### ISSUE TITLE
In linux, when closes a Project, properties help is not cleared

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#144]
![Screenshot at 2021-08-31 15-59-49](https://user-images.githubusercontent.com/1350282/131507164-5c180090-8c50-458a-b111-c9c644338654.png)

**Comment by XusinboyBekchanov** [comment]
Fixed: On close current window clears Property Grid help box:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/4bc5d440a07c827aa1951fe788a6878e8d851c17

Thanks.

**Comment by demosthenesk** [comment]
fixed!
