### ISSUE TITLE
In Linux, varius TextBox Properties not implemented yet.

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#146]
These TextBox Properties are not implemented in linux yet!
Alignment
CaretPos
CharCase
Ctl3D
HideSelection
Lines
MaskChar
Masked
MaxLength
Modified
OEMConvert
ScrollBars
SelEnd
SelLength
SelStart
SelText
TopLine
WantReturn
WantTab

**Comment by XusinboyBekchanov** [comment]
Added: OnCopy, OnCut, OnPaste, OnScroll, OnUpdate event and Alignment, CaretPos, CharCase, Ctl3D, Lines, MaskChar, Masked, MaxLength, Modified, ScrollBars, SelEnd, SelLength, SelStart, SelText, TopLine, WantReturn, WantTab properties to TextBox in Linux:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/05fc8f728b6d62ec10a945d4d4ad882dbef3b6ec

**Comment by XusinboyBekchanov** [comment]
I couldn't find a way to add HideSelection and was not interested with OEMConvert.

**Comment by demosthenesk** [comment]
> I couldn't find a way to add HideSelection and was not interested with OEMConvert.

οκ!

**Comment by demosthenesk** [comment]
i get these errors:
home/user/Downloads/VisualFBEditor-master/MyFbFramework/mff/TextBox.bas(371) error 42: Variable not declared, gtk_entry_set_input_hints
/home/user/Downloads/VisualFBEditor-master/MyFbFramework/mff/TextBox.bas(372) error 3: Expected End-of-Line, found 'gtk_entry_set_input_hints'
/home/user/Downloads/VisualFBEditor-master/MyFbFramework/mff/TextBox.bas(373) error 3: Expected End-of-Line, found 'gtk_entry_set_input_hints'

**Comment by XusinboyBekchanov** [comment]
Fixed: CharCase property of TextBox (gtk2 not supports):
https://github.com/XusinboyBekchanov/MyFbFramework/commit/abfaeb5840c2a093609acb11c4fb175c8c50d9b0

**Comment by demosthenesk** [comment]
cannot set MaskChar.
i try to set as * but when property looses focus it is changed to empty

**Comment by demosthenesk** [comment]
1. When i set ScrollBars, TextBox in design does not appear correctly
![Screenshot at 2021-09-03 17-56-31](https://user-images.githubusercontent.com/1350282/132026252-93887bff-c4cc-4baf-9483-335d72eb397d.png)

**Comment by demosthenesk** [comment]
> Fixed: CharCase property of TextBox (gtk2 not supports):
> [XusinboyBekchanov/MyFbFramework@abfaeb5](https://github.com/XusinboyBekchanov/MyFbFramework/commit/abfaeb5840c2a093609acb11c4fb175c8c50d9b0)

Could you add it manually with UCase/LCase ?

**Comment by XusinboyBekchanov** [comment]
> > Исправлено: свойство CharCase TextBox (gtk2 не поддерживает): 
> > [XusinboyBekchanov / MyFbFramework @ abfaeb5](https://github.com/XusinboyBekchanov/MyFbFramework/commit/abfaeb5840c2a093609acb11c4fb175c8c50d9b0)
> 
> Не могли бы вы добавить его вручную с помощью UCase / LCase?

Let's see, if there is no other way, then we will do so.

**Comment by XusinboyBekchanov** [comment]
Fixed: Masked and MaskChar properties of TextBox:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/7bd562acc36dd91fba028a36b6ea045336a01177

**Comment by XusinboyBekchanov** [comment]
>ReadOnly property looses its dropdown menu when is set to true

I have not found this behavior.

**Comment by demosthenesk** [comment]
> Fixed: Masked and MaskChar properties of TextBox:
> [XusinboyBekchanov/MyFbFramework@7bd562a](https://github.com/XusinboyBekchanov/MyFbFramework/commit/7bd562acc36dd91fba028a36b6ea045336a01177)

fixed!

**Comment by demosthenesk** [comment]
> > ReadOnly property looses its dropdown menu when is set to true
> 
> I have not found this behavior.

Yes it is fixed!

**Comment by demosthenesk** [comment]
> 1. When i set ScrollBars, TextBox in design does not appear correctly
>    ![Screenshot at 2021-09-03 17-56-31](https://user-images.githubusercontent.com/1350282/132026252-93887bff-c4cc-4baf-9483-335d72eb397d.png)

This one is left!

**Comment by demosthenesk** [comment]
> > Fixed: CharCase property of TextBox (gtk2 not supports):
> > [XusinboyBekchanov/MyFbFramework@abfaeb5](https://github.com/XusinboyBekchanov/MyFbFramework/commit/abfaeb5840c2a093609acb11c4fb175c8c50d9b0)
> 
> Could you add it manually with UCase/LCase ?

And this one...

**Comment by XusinboyBekchanov** [comment]
> This one is left!

Gtk3 does not allow lower heights for the GtkTextView (without Multiline, this is a GtkEntry control).

**Comment by demosthenesk** [comment]
> > This one is left!
> 
> Gtk3 does not allow lower heights for the GtkTextView (without Multiline, this is a GtkEntry control).

so we leave it as it is ?

**Comment by XusinboyBekchanov** [comment]
Maybe set the points to new positions.

**Comment by demosthenesk** [comment]
> Maybe set the points to new positions.

yes, that is in my mind.

**Comment by demosthenesk** [comment]
> > Maybe set the points to new positions.
> 
> yes, that is in my mind.

if you click Form and then click back to TextBox it is ok.
This issue is only when for first time change size
![Screenshot at 2021-09-03 19-36-02](https://user-images.githubusercontent.com/1350282/132039617-70265533-cb3a-4fae-899f-a19d72ef0d66.png)

**Comment by XusinboyBekchanov** [comment]
> > > Fixed: CharCase property of TextBox (gtk2 not supports):
> > > [XusinboyBekchanov/MyFbFramework@abfaeb5](https://github.com/XusinboyBekchanov/MyFbFramework/commit/abfaeb5840c2a093609acb11c4fb175c8c50d9b0)
> > 
> > 
> > Could you add it manually with UCase/LCase ?
> 
> And this one...

Fixed: CharCase property of TextBox in GTK2:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/1c4e52d425b0cf33a8ed1d4981e3278769f8e0d6

**Comment by demosthenesk** [comment]
> > > > Fixed: CharCase property of TextBox (gtk2 not supports):
> > > > [XusinboyBekchanov/MyFbFramework@abfaeb5](https://github.com/XusinboyBekchanov/MyFbFramework/commit/abfaeb5840c2a093609acb11c4fb175c8c50d9b0)
> > > 
> > > 
> > > Could you add it manually with UCase/LCase ?
> > 
> > 
> > And this one...
> 
> Fixed: CharCase property of TextBox in GTK2:
> [XusinboyBekchanov/MyFbFramework@1c4e52d](https://github.com/XusinboyBekchanov/MyFbFramework/commit/1c4e52d425b0cf33a8ed1d4981e3278769f8e0d6)

ok fixed!

**Comment by demosthenesk** [comment]
> > > Maybe set the points to new positions.
> > 
> > 
> > yes, that is in my mind.
> 
> if you click Form and then click back to TextBox it is ok.
> This issue is only when for first time change size
> ![Screenshot at 2021-09-03 19-36-02](https://user-images.githubusercontent.com/1350282/132039617-70265533-cb3a-4fae-899f-a19d72ef0d66.png)

This is the last one, i think.

**Comment by XusinboyBekchanov** [comment]
Fixed: Designer:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/90669ebfafd93e02b96f931dc4a8f4026da8969a

**Comment by demosthenesk** [comment]
fixed!
