### ISSUE TITLE
In Linux, varius TextBox Events are not implemented yet!

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#147]
These events are not implemented yet, in linux.
OnCopy
OnCut
OnPaste
OnScroll
OnUpdate

**Comment by XusinboyBekchanov** [comment]
Added: OnCopy, OnCut, OnPaste, OnScroll, OnUpdate event and Alignment, CaretPos, CharCase, Ctl3D, Lines, MaskChar, Masked, MaxLength, Modified, ScrollBars, SelEnd, SelLength, SelStart, SelText, TopLine, WantReturn, WantTab properties to TextBox in Linux:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/05fc8f728b6d62ec10a945d4d4ad882dbef3b6ec

**Comment by demosthenesk** [comment]
ok fixed!
