### ISSUE TITLE
In linux, varius ImageBox Events are not impemented yet!

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#148]
I tried,
OnEnter
OnHover
OnClick
may be more or all

**Comment by XusinboyBekchanov** [comment]
> OnEnter
This has been fixed before:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/c4e12fdacd11e98d460df46fecbdaa22da7102d5

> OnClick
Fixed: ImageBox OnClik and OnDblClick event in Linux:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/eb63a32655e32b97f0dbaa68bf842f0a771a55d6

**Comment by demosthenesk** [comment]
> > OnEnter
> 
> This has been fixed before:
> [XusinboyBekchanov/MyFbFramework@c4e12fd](https://github.com/XusinboyBekchanov/MyFbFramework/commit/c4e12fdacd11e98d460df46fecbdaa22da7102d5)
> 
> > OnClick
> 
> Fixed: ImageBox OnClik and OnDblClick event in Linux:
> [XusinboyBekchanov/MyFbFramework@eb63a32](https://github.com/XusinboyBekchanov/MyFbFramework/commit/eb63a32655e32b97f0dbaa68bf842f0a771a55d6)

ok these are fixed!

What about OnMouseHover ?

**Comment by demosthenesk** [comment]
Please check which Events of ImageBox in linux missing and tell me if all is ok to close this issue.

**Comment by XusinboyBekchanov** [comment]
>What about OnMouseHover ?

This is currently being worked on.

>Please check which Events of ImageBox in linux missing and tell me if all is ok to close this issue.

OnDropFile - Now it does not work in any control yet.
OnDraw - Not yet.

**Comment by XusinboyBekchanov** [comment]
Added: OnMouseHover event to Control in Linux:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/32828b1faed9af421dd3ecb3bcfab0bdf76a04c0

**Comment by demosthenesk** [comment]
ok fixed!

Fix and OnDraw and i close this issue.
OnDropFile is in another issue open.

**Comment by XusinboyBekchanov** [comment]
OnDraw is impossible to implement in Linux.

**Comment by demosthenesk** [comment]
ok...so close it!
