### ISSUE TITLE
In linux, ImageBox not visible in design mode when it has no focus

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#150]
1. Add an ImageBox on a Form.
2. Click on form so ImageBox looses focus
3. Borders of Imagebox with no image are not shown
4. if i click ImageBox again is ok

**Comment by XusinboyBekchanov** [comment]
Improved: ImageBox visible in Design mode:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/6c1c0412da6176b610be021c117a33f891f31809

**Comment by XusinboyBekchanov** [comment]
Fixed: Designer:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/6412f9cc1445fbe7913afc672e51c4480fd6dc8b

**Comment by demosthenesk** [comment]
fixed!
