### ISSUE TITLE
In linux, ImageBox has TabStop but no TabIndex

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#151]
No TabIndex for ImageBox

**Comment by XusinboyBekchanov** [comment]
ImageBox is not TabStop control.

**Comment by demosthenesk** [comment]
if ImageBox is no TabStop control so TabStop property should be removed?

**Comment by XusinboyBekchanov** [comment]
Yes

**Comment by XusinboyBekchanov** [comment]
Fixed: TabStop property of Controls:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/49eb43aee7ec55d784c1130f02afb67562589900
