### ISSUE TITLE
Combo box doesn't adapt to change in font size

### ISSUE THREAD

**Issue by W98X** [XusinboyBekchanov/VisualFBEditor#153]
The combobox edit control (Windows10, in high dpi 140%) will cut off bottom pixels of text in the comboboxedit  drop down items if the font size is changed
### 
**Example 1:**
When VFBE IDE font size is changed to Segoe UI size 9 (default system font for Windows10), it cuts off bottom pixels, making the word "gdb" look like "adb":
![vfbe options menu font size segoe crop](https://user-images.githubusercontent.com/88371717/132082701-2bfb08cd-9bae-4663-9a2e-b8eca1679bd1.png)
![vfbe-combobox-bottom-pixels-missing-1-zoomed](https://user-images.githubusercontent.com/88371717/132082583-13429fcf-d523-484f-a343-7b87b2ce8b04.png)

**Example 2:**
This combo box has it's font set to Tahoma size 12 and the bottom half of combobox items is cut off:
![vfbe-combobox item cutoff tahoma size 12](https://user-images.githubusercontent.com/88371717/132082592-6a548a9a-5af9-4583-b39a-ad128310ffb7.png)

**Comment by XusinboyBekchanov** [comment]
Fixed: Fixed ComboBoxEdit ItemHeight property:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/5d1f3b75249f51c0d8b06b69f058386b310a620d

**Comment by W98X** [comment]
I just tested it and confirm it's fixed. 
The comboboxedit drop-down list is displaying properly now 👌 

Thanks.
