### ISSUE TITLE
Form.Show, Form.Hide and Form Coordinates

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#154]
I have a many-form project, Project1.
When i click CommandButton1 Form2 is visible.
When i click CommandButton2 Form2 is not visible.
If i move Form2 at x,y position on screen and hide it, after when it is visible looses its x.y coordinates and appears next to Form1.
I expect x,y of hidden form to remain the same and only visibility be affected.
[Project1.zip](https://github.com/XusinboyBekchanov/VisualFBEditor/files/7109426/Project1.zip)

**Comment by XusinboyBekchanov** [comment]
Fixed: Form StartPosition property:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/39660f64fa187f5e2ec1cd76b7863f610cc4b48e

**Comment by demosthenesk** [comment]
fixed!
