### ISSUE TITLE
Feature Request: Add Form Template, change form code by form name

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#155]
If i add 2 forms, Form1.frm, Form2.frm then Form2.frm has the template of Form1.
Is it possible the Form2.frm has Form2 name in code ?
Etc for any other form, Form3,4,5,...

**Comment by demosthenesk** [comment]
my thought is about the added form to have code according to its file name
Type Form2 .... etc

﻿```
#ifdef __FB_WIN32__
	'#Compile "Form2.rc"
#endif
'#Region "Form"
	#include once "mff/Form.bi"
	
	Using My.Sys.Forms
	
	Type Form2 Extends Form
		
	End Type
	
	
'#End Region
```

**Comment by demosthenesk** [comment]
Now, if you add Form2.frm the code says Type Form1...

**Comment by XusinboyBekchanov** [comment]
Ok, let's do it

**Comment by demosthenesk** [comment]
fine! Thanks!

**Comment by XusinboyBekchanov** [comment]
Fixed: Add Form from Template:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/a254cb0d676c5faea95d6e257eec857c776b61b8

**Comment by demosthenesk** [comment]
ok! Added!
Thanks!
