### ISSUE TITLE
In linux, Project Properties Window needs redesign.

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#156]
![Screenshot from 2021-09-04 12-06-36](https://user-images.githubusercontent.com/1350282/132089247-df2bac8c-857d-4b68-b2b4-070a194eaf68.png)

some elements are one over the other.

**Comment by demosthenesk** [comment]
![Screenshot from 2021-09-04 16-59-51](https://user-images.githubusercontent.com/1350282/132097067-5034d0f7-b80f-4d7e-82ee-a4727e1aa30a.png)

**Comment by XusinboyBekchanov** [comment]
Fixed: Project Properties window in Linux:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/a9c56a7ca98559aa05b4ad910963375481c92a48

![Снимок экрана от 2021-09-04 19-09-26](https://user-images.githubusercontent.com/32607344/132097394-c65e190c-5f48-4d3c-82d5-280f313edb93.png)
![Снимок экрана от 2021-09-04 19-09-33](https://user-images.githubusercontent.com/32607344/132097397-f69bc0ab-4657-4a6e-bdcb-673258a40b97.png)
![Снимок экрана от 2021-09-04 19-09-41](https://user-images.githubusercontent.com/32607344/132097399-41e571d5-a71a-4098-8024-3129d340352f.png)
![Снимок экрана от 2021-09-04 19-09-48](https://user-images.githubusercontent.com/32607344/132097401-b2d89dfe-3e5d-4436-b203-63b1b2c91d28.png)

**Comment by demosthenesk** [comment]
1. Run IDE
2. Close Unnamed
3. Show Project Properties
![Screenshot from 2021-09-04 17-20-39](https://user-images.githubusercontent.com/1350282/132097689-546f6bf2-afdb-47e0-a76b-0e3748636f83.png)
4. There are some odd compilation arguments in Windows 32/64 bit TextBoxes.

**Comment by XusinboyBekchanov** [comment]
Fixed: Project Properties window:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/45dede56aec04f7e50245c4e34575d6b80ecc6e0

**Comment by demosthenesk** [comment]
fixed!
