### ISSUE TITLE
In linux, TextBox drag n drop called multiple times

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#157]
i have a TextBox and i enabled drag n drop
```
Private Sub Form1.TextBox1_DropFile(ByRef Sender As Control, ByRef Filename As WString)
	Print "TextBox " & Filename
End Sub

```
when i drag n drop 2 files i get
```
TextBox /home/user/Downloads/VisualFBEditor-master/objdump.exe
TextBox /home/user/Downloads/VisualFBEditor-master/README.md
TextBox 
TextBox /home/user/Downloads/VisualFBEditor-master/objdump.exe
TextBox /home/user/Downloads/VisualFBEditor-master/README.md
TextBox 

```

**Comment by XusinboyBekchanov** [comment]
Fixed: TextBox OnDropFile event:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/3840048bfc333270f89187c36b459a76aa2bf0a4

**Comment by demosthenesk** [comment]
The many times is fixed!
But now if i drag n drop many files i get
/home/user/Downloads/VisualFBEditor-master/objdump.exe
**file://**/home/user/Downloads/VisualFBEditor-master/README.md
**file://**/home/user/Downloads/VisualFBEditor-master/VisualFBEditor_Change.log

**Comment by XusinboyBekchanov** [comment]
Fixed: Control OnDropFile event:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/bee6b52f6c066d6d44db22131011b167f51355fe

**Comment by demosthenesk** [comment]
fixed!
