### ISSUE TITLE
In linux, TextBox LoadFromFile fails

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#158]
i get this error when i try to load from file in a TextBox.
(Form1:339911): Gtk-CRITICAL **: 19:59:54.655: gtk_text_buffer_emit_insert: assertion 'g_utf8_validate (text, len, NULL)' failed

[Project2.zip](https://github.com/XusinboyBekchanov/VisualFBEditor/files/7112036/Project2.zip)

**Comment by XusinboyBekchanov** [comment]
Fixed: TextBox LoadFromFile method in Linux:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/236f011a0055775c0c2207a908d06f3bdab05728

**Comment by demosthenesk** [comment]
fixed!
