### ISSUE TITLE
In linux, cannot catch ComboBoxEdit and ComboBoxEx in design mode

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#159]
1. Add a form
2. Add a ComboBoxEdit or ComboBoxEx
3. Click the form
4. try to click again CombBoxEdit or ComboBoxEx
5. i cannot catch in design ComboBoxEdit or ComboBoxEx

**Comment by XusinboyBekchanov** [comment]
Now I can catch drawing a rectangle around these controls. But this needs to be fixed.

**Comment by demosthenesk** [comment]
> Now I can catch drawing a rectangle around these controls. But this needs to be fixed.

yes with a drawing rectangle it is possible but not with a simple click.

**Comment by XusinboyBekchanov** [comment]
Added: OnMouseEnter, OnMouseMove, OnMouseHover, OnMouseLeave events to ComboBoxes in Linux and filled Read and Write Properties:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/63915fa0170968a3aee6bc5646a13fd9c80c482a

Fixed: Selecting ComboBoxes with Mouse Pointer in Designer (in Linux):
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/b7569a46faaf74cc7e87febc9279a70af12274e0

**Comment by demosthenesk** [comment]
fixed the mouse selecting in designer
but there are some other issues now...

1. i click the ComboBoxEdit ok
2. i can't move it with mouse
3. i can move it on form with arrow keys but it looses it's blue points see image
![Screenshot from 2021-09-08 22-26-29](https://user-images.githubusercontent.com/1350282/132572902-07259b83-c839-4439-a6a6-9bc53e8fdaba.png)

**Comment by XusinboyBekchanov** [comment]
Yes, I saw it now, I need to fix it.

**Comment by XusinboyBekchanov** [comment]
Fixed: Moving Controls by key press in Designer (in Linux):
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/7ae9d18b512ac0f8e714d3615f595861c07593cf

**Comment by demosthenesk** [comment]
> Fixed: Moving Controls by key press in Designer (in Linux):
> [7ae9d18](https://github.com/XusinboyBekchanov/VisualFBEditor/commit/7ae9d18b512ac0f8e714d3615f595861c07593cf)

fixed!

**Comment by demosthenesk** [comment]
1. Add a ComboBoxEdit or ComboBoxEx.
2. Click on form
3. Click on ComboBoxEdit or ComboBoxEx
4. Try to drag it on form... impossible!

**Comment by XusinboyBekchanov** [comment]
Moving is not possible because I could only detect the release of the mouse button.

**Comment by XusinboyBekchanov** [comment]
It is possible to move only in cbDropDown or cbSimple style.

**Comment by demosthenesk** [comment]
ok!
so should i close this issue ?

**Comment by XusinboyBekchanov** [comment]
Yes, I think so

**Comment by demosthenesk** [comment]
closed!
