### ISSUE TITLE
In linux, code is shown always unsaved, cannot move cursor with arrows

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#160]
1. Open the untitled.bas
2. edit ComboBox .Title from code
3. Try to change line in code by arrows two times ... it fails
4. File shows with * always unsaved.
[Untitled.bas.zip](https://github.com/XusinboyBekchanov/VisualFBEditor/files/7115466/Untitled.bas.zip)

**Comment by XusinboyBekchanov** [comment]
Fixed: Designer:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/2192f2c9051fb5e3c292e6225cfb7fef3ad1f62b

**Comment by demosthenesk** [comment]
fixed!
