### ISSUE TITLE
mff65.dll error

### ISSUE THREAD

**Issue by DFergFLA** [XusinboyBekchanov/VisualFBEditor#161]
Hi, I'm new.  really, really new.  I found this project when doing in internet search on basic.  I was a Quick Basic user... like 1000 years ago.  I haven not touched a programming language in over 20 years.  That said I was able to compile VisualFBEditor.  This was quite an adventure but I finally did  it.  It's the next part I am having problems with and I didn't know where to go for help, so I'm starting here.

When running the following line from the instructions to compile. the framework.  I am getting:

D:\FreeBASIC\VisualFBEditor\MyFbFramework\mff>"D:\FreeBasic\fbc.exe" -b "mff.bi" "mff.rc" -dll -x "..\mff64.dll"
D:\FreeBASIC\VisualFBEditor\MyFbFramework\mff\Grid.bas(320) error 202: Illegal member access, MY.SYS.FORMS.CONTROL.PERFORM
D:\FreeBASIC\VisualFBEditor\MyFbFramework\mff\Grid.bas(320) error 3: Expected End-of-Line, found ','
D:\FreeBASIC\VisualFBEditor\MyFbFramework\mff\Grid.bas(420) error 202: Illegal member access, MY.SYS.FORMS.CONTROL.PERFORM
  
I have just downloaded both VisualBFEditor and MyFbFramework today.  I unzipped them and that's it.  I can start the Editor but without the mff64.dll there isn't much there to see.

Help!! Please.

Donald

**Comment by XusinboyBekchanov** [comment]
Fixed: Grid control:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/130ef06de1abd39b73eed5e66969a8757e9002a8

There were some changes a few days ago, so it didn't compile. Thank you for message.

**Comment by DFergFLA** [comment]
Thank you.  I was able to compile without errors.   Now I just have to figure out where to start.  I apricate the help.
