### ISSUE TITLE
Newbie

### ISSUE THREAD

**Issue by DFergFLA** [XusinboyBekchanov/VisualFBEditor#162]
Hello, Newbie here.  I mean new..  I have not played around with Quick Basic in almost 30 years and not any kind of programming at all in over 20.  The last thing I used was VB6.  I was never a professional programmer, just a hobbist.  I stared with my Comodore 64, then over to my Amiga and Amiga Basic.  Anyway.  I have spent the last few hours downloading FreeBasic, VisualBFEditor and MyFbFramework.  Much to my amazement, I was actually able to get it compiled and running.  I have even done the traditionally "Hello World"  Interestingly I wasn't able to find a "Message Box" so I just changed the text of the button.  But, I did get it to work.  

I need help to just get started here.  Like I said, it's been decades and I am just playing around.  Is there any newbie guide to using the IDE?

**Comment by XusinboyBekchanov** [comment]
Unfortunately, not now.

There is information here too:
https://github.com/XusinboyBekchanov/VisualFBEditor/discussions/98

**Comment by XusinboyBekchanov** [comment]
You can print to the console. To do this, you must enable the console:
`Print "Hello World"`
![image](https://user-images.githubusercontent.com/32607344/132274387-052df71f-f330-4594-a9cf-484fc246a61e.png)

You can also display the message:
`MsgBox "Hello World"`

**Comment by demosthenesk** [comment]
Hello, my opinion is that first you must learn the syntax of the FreeBASIC.
Here is a starting point https://www.freebasic.net/wiki/DocToc
This wiki is always exist as chm for offline use see here https://sourceforge.net/projects/fbc/files/FreeBASIC-1.08.1/Documentation/
Start with simple programs which print to the screen values and messages, learn the internals.
FreeBASIC has a dialect for qb but it has more to offer when you use the default dialect which is freebasic.
If you have experience with VB6 then this project is a piece of cake for you.
Always you can get help in forum https://www.freebasic.net/forum/index.php

**Comment by demosthenesk** [comment]
For questions and discussions use better https://github.com/XusinboyBekchanov/VisualFBEditor/discussions and not isuues which is for reporting bugs.
Welcome and good luck my friend!
