### ISSUE TITLE
SelectCanceled of ComboBoxEdit is not implemented in linux yet

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#163]
SelectCanceled can be caught when opening and closing DropDown in Linux.

_Originally posted by @XusinboyBekchanov in https://github.com/XusinboyBekchanov/VisualFBEditor/discussions/98#discussioncomment-1290535_

**Comment by XusinboyBekchanov** [comment]
Added: OnSelectCanceled event to ComboBox in Linux:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/7f83e60be52eb161f498fdde5c173edd582d91fe

There is one note: In Linux OnDropDown, OnCloseUp, OnSelectCanceled works only with keys (Alt + Down, Alt + Up and Esc).
https://docs.gtk.org/gtk4/signal.ComboBox.popdown.html
https://docs.gtk.org/gtk4/signal.ComboBox.popup.html

**Comment by demosthenesk** [comment]
i can't trigger OnSelectCanceled...
I click ComboBoxEdit and items are showed.
i dont choose any item and i click form, items menu is off

```
Private Sub Form1.ComboBoxEdit1_SelectCanceled(ByRef Sender As ComboBoxEdit)
	Print "Canceled"
End Sub
```
no print out on terminal

**Comment by XusinboyBekchanov** [comment]
The GtkComboBox does in fact "eat the mouse click", so there is no way to adjust this (to receive an DropDown opened signal with the mouse). As it is written in the gtk help, signals work only while working with the keys (Alt + Down, Alt + Up and Esc). Help is at the top.

**Comment by demosthenesk** [comment]
ok! i close this.
