### ISSUE TITLE
In linux, Sort property of ComboBoxEdit is not implemented yet

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#164]
Sort - Possible.

_Originally posted by @XusinboyBekchanov in https://github.com/XusinboyBekchanov/VisualFBEditor/discussions/98#discussioncomment-1290654_

**Comment by XusinboyBekchanov** [comment]
Added: Sort property to ComboBox and ComboBoxEx in Linux:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/ce00e25780a9e87f976cd2f53c1f9981ad2552cb

**Comment by demosthenesk** [comment]
i have the next code:

```
		' ComboBoxEdit1
		With ComboBoxEdit1
			.Name = "ComboBoxEdit1"
			.TabIndex = 0
			.SetBounds 30, 30, 143, 31
			.Parent = @This
			.AddItem("c")
			.AddItem("b")
			.AddItem("a")
			.Sort = True
			.Designer = @This
			.OnSelectCanceled = @ComboBoxEdit1_SelectCanceled_
			.Text = "a"
		End With
```
i get c,b,a items of comboboxedit not sorted

**Comment by demosthenesk** [comment]
well i found it...
Sort property is defined in constructor but .AddItem should be called in run time like below:

```
		With ComboBoxEdit1
			.Name = "ComboBoxEdit1"
			.Text = "ComboBoxEdit1"
			.TabIndex = 0
			.SetBounds 60, 40, 150, 31
			.Parent = @This
			.Sort = True
		End With
	End Constructor
	
	Dim Shared fForm1 As Form1
	
	#ifndef _NOT_AUTORUN_FORMS_
		fForm1.Show
		fForm1.ComboBoxEdit1.AddItem("c")
		fForm1.ComboBoxEdit1.AddItem("b")
		fForm1.ComboBoxEdit1.AddItem("a")

		App.Run
	#endif

```

**Comment by demosthenesk** [comment]
should i close this issue or are you planing to fix to sort in the constructor also ?

**Comment by XusinboyBekchanov** [comment]
In the Constructor, after the property can also be added, but I thought to sort the previous ones too, in the evening.

**Comment by demosthenesk** [comment]
I tried to sort after AddItem and before AddItem...both fail.

```
		' ComboBoxEdit1
		With ComboBoxEdit1
			.Name = "ComboBoxEdit1"
			.Text = "ComboBoxEdit1"
			.TabIndex = 0
			.SetBounds 60, 40, 150, 31
			.Parent = @This
			.AddItem("c")
			.AddItem("b")
			.AddItem("a")
			.Sort = True
		End With
```

**Comment by XusinboyBekchanov** [comment]
Doesn't it work like that?
```
                ' ComboBoxEdit1
		With ComboBoxEdit1
			.Name = "ComboBoxEdit1"
			.Text = "ComboBoxEdit1"
			.TabIndex = 0
			.SetBounds 60, 40, 150, 31
			.Parent = @This
			.Sort = True
			.AddItem("c")
			.AddItem("b")
			.AddItem("a")
		End With
```

**Comment by demosthenesk** [comment]
> Doesn't it work like that?
> 
> ```
>                 ' ComboBoxEdit1
> 		With ComboBoxEdit1
> 			.Name = "ComboBoxEdit1"
> 			.Text = "ComboBoxEdit1"
> 			.TabIndex = 0
> 			.SetBounds 60, 40, 150, 31
> 			.Parent = @This
> 			.Sort = True
> 			.AddItem("c")
> 			.AddItem("b")
> 			.AddItem("a")
> 		End With
> ```

yes it works...
did you fix it?

**Comment by demosthenesk** [comment]
fixed!

**Comment by XusinboyBekchanov** [comment]
>did you fix it?

When I said "Added: Sort property to ComboBox and ComboBoxEx in Linux", this is how it worked for me.

**Comment by demosthenesk** [comment]
ok ... i see now... my first code the sort = true was after AddItem...
so my mistake ...

**Comment by XusinboyBekchanov** [comment]
I didn’t see it as your mistake, I saw it as a test of the program in different ways.

**Comment by demosthenesk** [comment]
ok!
