### ISSUE TITLE
Code editor hint shows html code

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#167]
Code editor hint shows html code
![Screenshot at 2021-09-08 16-07-27](https://user-images.githubusercontent.com/1350282/132515320-2ef18e4e-54a1-48c4-a5d7-caa4e20cf433.png)

**Comment by XusinboyBekchanov** [comment]
Fixed: Disabled Hint from Code Editor:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/c7fe7f2dd460f09d2da14b6cccad8535901e88a5

Fixed: Control ShowHint property in Linux:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/226effb2a474bf5298dea710ae3c5f338b6e1b27

**Comment by demosthenesk** [comment]
fixed!
