### ISSUE TITLE
In linux, borders of Components are not visible well in design mode

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#168]
The borders of ImageList need to be visible in design mode.
1. Add an ImageList
2. Click on form, ImageList borders are disapeared on form.

This is also for all Components, their borders needs to be visible in design mode.

**Comment by demosthenesk** [comment]
As i saw in Windows, there is an image and borders for each Component.
Is it possible to implement the same way the linux code ?
Thanks!

**Comment by XusinboyBekchanov** [comment]
Improved: Shows Component borders in Design mode:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/0c2635c2a15176c9791d2653a6392dd6dcd96bd0

**Comment by demosthenesk** [comment]
fixed!
