### ISSUE TITLE
In linux, ListControl borders are not shown well in design mode

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#169]
1. Add a ListControl
2. Click on form
3. The borders of ListControl disappeared

**Comment by XusinboyBekchanov** [comment]
Added: ListControl borders in Linux:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/caf7c1557fa7168b20f8652b50cb8d7cb4f3506c

**Comment by demosthenesk** [comment]
fixed!

**Comment by demosthenesk** [comment]
ListControl borders are get lost when move control with arrow keys.
![Screenshot from 2021-09-09 20-27-05](https://user-images.githubusercontent.com/1350282/132734049-ff654ba6-129a-4487-9403-f6f8eecf4c5b.png)

**Comment by XusinboyBekchanov** [comment]
Fixed: Moving Controls by key press in Designer (in Linux):
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/7ae9d18b512ac0f8e714d3615f595861c07593cf

**Comment by demosthenesk** [comment]
fixed!
