### ISSUE TITLE
In linux, ExtendSelect and Sort properties of ListControl do not add code in code editor

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#170]
In linux, ExtendSelect and Sort properties of ListControl do not add code in code editor

**Comment by XusinboyBekchanov** [comment]
Improved: Filled Read and Write property function:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/733042d44c2a8a169bd81a9b3c82517c76bd22bd

**Comment by demosthenesk** [comment]
fixed!
