### ISSUE TITLE
In linux, Listcontrol property Columns not implemented yet

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#171]
1. Columns - Not impossible.

_Originally posted by @XusinboyBekchanov in https://github.com/XusinboyBekchanov/VisualFBEditor/discussions/98#discussioncomment-1303119_

**Comment by demosthenesk** [comment]
Did you mean impossible ?
Or not impossible = possible ?

**Comment by XusinboyBekchanov** [comment]
I mean Impossible, sorry

**Comment by demosthenesk** [comment]
:) ok!
closed!
