### ISSUE TITLE
In linux, varius properties of ListControl are not implemented yet

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#173]
1. Columns - Impossible.
4. SelCount - Possible.
6. SelItems - Possible.

_Originally posted by @XusinboyBekchanov in https://github.com/XusinboyBekchanov/VisualFBEditor/discussions/98#discussioncomment-1303119_

**Comment by XusinboyBekchanov** [comment]
Added: SelCount and SelItems properties in Linux:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/a480d2ba5b65f7a1803f1ed5e8905a744d0e5eb7

**Comment by demosthenesk** [comment]
fixed!
