### ISSUE TITLE
In linux, CheckedListBox Items cannot be checked

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#176]
Items of CheckedListBox cannot be checked !

**Comment by XusinboyBekchanov** [comment]
Fixed: Check items of CheckedListBox in Linux:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/4f371e4b9019f692d584e5392e6da92458a74753

**Comment by demosthenesk** [comment]
fixed!
