### ISSUE TITLE
In linux, Multiselect of ListControl

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#177]
### Multiselect CheckedListBox vs ListControl
When ListControl has enabled Multiselect, the user can multi selects the items with just left mouse clicks.

When CheckedListBox has enabled Multiselect the user needs to press SHIFT + Left Mouse click, in order to multi selects items.
Also, CTRL+Left Mouse Clicks unselect a selected item and Selects an unselected item.

I propose ListControl has the same behavior as CheckedListBox for Multiselect. It needs to be changed.

_Originally posted by @demosthenesk in https://github.com/XusinboyBekchanov/VisualFBEditor/discussions/98#discussioncomment-1309788_

**Comment by XusinboyBekchanov** [comment]
Changed: MultiSelect of ListControl in Linux:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/f8144776864749145cf92ae82e141da52c042bfd

Fixed: ListBoxes in Linux:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/2cafc7138eff4a28519135503954a3f0ab96079d

**Comment by demosthenesk** [comment]
1. There is no Multiselect property of ListControl

2. i get error
/home/user/Downloads/VisualFBEditor-master/MyFbFramework/mff/ListControl.bas(389) error 158: Declaration outside the original namespace or class

**Comment by XusinboyBekchanov** [comment]
This commit has fixed that too:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/a480d2ba5b65f7a1803f1ed5e8905a744d0e5eb7

**Comment by demosthenesk** [comment]
fixed!
