### ISSUE TITLE
In linux, GroupBoxes and RadioButtons

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#178]
RadioButtons are not drawn well on GroupBoxes.
![Screenshot at 2021-09-11 23-14-52](https://user-images.githubusercontent.com/1350282/132960602-a7e7ed94-0232-4a7c-b366-ebc16b2f8581.png)

**Comment by XusinboyBekchanov** [comment]
Fixed: GroupBox control in Designer:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/00d43a7ac8c54d2e6a7bb37b1af0db88541f0484

Fixed: Get Top position of controls contained in GroupBox:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/1198786bf2d3300e4ed307a63b4fe9267479d99f

**Comment by XusinboyBekchanov** [comment]
Fixed: Designer:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/cf3c8d47a9e97117fb14b464ef687228757c6b9b

**Comment by demosthenesk** [comment]
fixed!
