### ISSUE TITLE
In linux, TabPages and RadioButtons

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#179]
1. RadioButtons are not shown well in designer on TabPages
2. i get these errors at compiling
 21:49:29: Compilation: "/home/user/Bin/FreeBASIC-1.08.1-ubuntu-20.04-x86_64/bin/fbc"   -b "Untitled.bas" -exx -i "/home/user/Bin/VisualFBEditor/./MyFbFramework" -i "/home/user/Bin/FreeBASIC-1.08.1-ubuntu-20.04-x86_64/include/freebasic" -p "/home/user/Bin/FreeBASIC-1.08.1-ubuntu-20.04-x86_64/lib/freebasic/linux-x86_64" 2> "/home/user/Bin/VisualFBEditor/Temp/Compile.log"

ld: Untitled.o: in function `FORM1::FORM1()':
Untitled.c:(.text+0x59f9b): undefined reference to `MY::SYS::FORMS::TABPAGE::TABINDEX__set__(long)'
ld: Untitled.c:(.text+0x5a008): undefined reference to `MY::SYS::FORMS::TABPAGE::TABINDEX__set__(long)'

21:49:49: Do not build file.
[Untitled.bas.zip](https://github.com/XusinboyBekchanov/VisualFBEditor/files/7150135/Untitled.bas.zip)

**Comment by XusinboyBekchanov** [comment]
Fixed: TabIndex, TabStop and Text property of TabPage:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/f68668fcaf71a0d5e12def8c96caab223ee8d421

**Comment by demosthenesk** [comment]
1. RadioButtons are not shown well in designer on TabPages
![Screenshot at 2021-09-13 14-12-47](https://user-images.githubusercontent.com/1350282/133074356-e9ee2708-53e3-4f17-9e34-c863c2fbfc4e.png)

**Comment by demosthenesk** [comment]
2. Tabpages are not shown well in designer
![Screenshot at 2021-09-13 14-12-39](https://user-images.githubusercontent.com/1350282/133074461-b0a9508b-f621-4117-817b-4faaada7b414.png)

**Comment by XusinboyBekchanov** [comment]
>2. Tabpages are not shown well in designer

Fixed: Controls coordinates in Designer:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/949e1af4fa0124a6ee98df61cf84a5e83c1b2546

**Comment by demosthenesk** [comment]
> > 1. Tabpages are not shown well in designer
> 
> Fixed: Controls coordinates in Designer:
> [949e1af](https://github.com/XusinboyBekchanov/VisualFBEditor/commit/949e1af4fa0124a6ee98df61cf84a5e83c1b2546)

fixed!

**Comment by XusinboyBekchanov** [comment]
>1. RadioButtons are not shown well in designer on TabPages

Fixed: Show Dots in Designer on Linux:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/c3a6859616cf653a95006fa714b0d46891f454e7

**Comment by demosthenesk** [comment]
i get warnings
/home/user/Downloads/VisualFBEditor-master/src/Designer.bas(2791) warning 3(2): Passing different pointer types, at parameter 3 (x) of GETPOSTOCLIENT()
/home/user/Downloads/VisualFBEditor-master/src/Designer.bas(2791) warning 3(2): Passing different pointer types, at parameter 4 (y) of GETPOSTOCLIENT()
/home/user/Downloads/VisualFBEditor-master/src/Designer.bas(2792) warning 3(2): Passing different pointer types, at parameter 3 (x) of GETPOSTOCLIENT()
/home/user/Downloads/VisualFBEditor-master/src/Designer.bas(2792) warning 3(2): Passing different pointer types, at parameter 4 (y) of GETPOSTOCLIENT()

**Comment by demosthenesk** [comment]
i get also an error message
![Screenshot from 2021-09-26 21-10-28](https://user-images.githubusercontent.com/1350282/134819285-3b394d81-a346-46c8-80fb-8eb1e046b127.png)

The IDE does not show a form in designer.

**Comment by XusinboyBekchanov** [comment]
Update Designer.bas:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/3604730979f56637bfd7b4900cb01279a20387c9

Update UString.bas:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/384c7c5a4d7db2356d337ef3eb51e49858de67c7

By default, the gtk2 version is compiled, to compile the gtk3 version you must specify in the command line `-d __USE_GTK3__`:
```
  cd Path_to_VisualFBEditor/src
  fbc "VisualFBEditor.bas" -x "../VisualFBEditor64_gtk3" -i "Path_to_VisualFBEditor/MyFbFramework" -d __USE_GTK3__
  cd Path_to_VisualFBEditor/MyFbFramework/mff
  fbc -b "mff.bi" -dll -x "../libmff64_gtk3.so" -d __USE_GTK3__
```

**Comment by XusinboyBekchanov** [comment]
Because, I plan to add a menu to the toolbar to select gtk2 or gtk3.

**Comment by demosthenesk** [comment]
fixed!
