### ISSUE TITLE
In linux, Text and Caption properties of GroupBox are not set from properties grid in code

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#180]
1. Add a GroupBox
2. Set Text/Caption property from properties grid
3. Text/Caption is not set in code

**Comment by XusinboyBekchanov** [comment]
Fixed: Set Text property of GroupBox from Property Grid:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/24470955d6191070ac0429bfe9eaebf27ef9ca8c

**Comment by demosthenesk** [comment]
fixed!
