### ISSUE TITLE
In linux, ScrollBarControl Style property does not be set.

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#181]
1. Add a ScrollBarControl
2. set Style property to Vertical
3. Property does not be set
4. Property does not add to code in code editor

**Comment by XusinboyBekchanov** [comment]
Improved: Filled Read and Write property functions of ScrollBar controls:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/77f57dac7598e2d2acb8e30cb597835ebee6c17f

**Comment by XusinboyBekchanov** [comment]
Fixed: Designer:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/aef49a8a2611c08cc12f99257b5c21b1bef7ce97

**Comment by demosthenesk** [comment]
i get errors on compiling mff:
/home/user/Downloads/VisualFBEditor-master/MyFbFramework/mff/HScrollBar.bas(206) error 4: Duplicated definition
/home/user/Downloads/VisualFBEditor-master/MyFbFramework/mff/VScrollBar.bas(207) error 4: Duplicated definition

**Comment by XusinboyBekchanov** [comment]
Fixed: Compiling error:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/8efd9370bdbd2db98fab7b2d4a8f91bc1912ee0c

**Comment by demosthenesk** [comment]
fixed!
