### ISSUE TITLE
In linux, cannot set MaxValue over 100 for a ScrollBarControl

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#182]
I try to set Maxvalue to 255 and MinValue to 0, i can't.
When i set Maxvalue from property grid the Minvalue is set instead.

**Comment by XusinboyBekchanov** [comment]
Fixed: ScrollBar controls set MaxValue:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/7b607a948ad8a69ed742b293e3bc047d88b1556e

**Comment by demosthenesk** [comment]
fixed!
