### ISSUE TITLE
In linux, grid properties Minvalue, Maxvalue of ScrollBarControl are not updated when code is changing

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#183]
In linux, grid properties Minvalue, Maxvalue of ScrollBarControl are not updated when code is changing

**Comment by XusinboyBekchanov** [comment]
Fixed: Update Designer on Code Editor change:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/cfaa7d8f830a5a4e3e337cfd42febbc737e6d562

**Comment by demosthenesk** [comment]
fixed!
