### ISSUE TITLE
In linux, Global Functions via Сtrl + Space

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#184]
Yes, there is, you can access it via Сtrl + Space (Edit -> Complete Word)

_Originally posted by @XusinboyBekchanov in https://github.com/XusinboyBekchanov/VisualFBEditor/discussions/98#discussioncomment-1334885_

There is a bug in autocomplete with Ctrl+Space.
When the autocomplete is shown i cant scroll it with arrow keys for the keyword Any and above.

**Comment by XusinboyBekchanov** [comment]
Added: Intellisense limit to Options:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/3f5683368a175e61efae2ae1500969167c94f4f1

![image](https://user-images.githubusercontent.com/32607344/133549490-d4d8d51d-9038-4534-b99b-8bebd6113c24.png)

**Comment by XusinboyBekchanov** [comment]
To scroll up you must place the cursor in front of a word (or without words) and press Ctrl + Space.

**Comment by demosthenesk** [comment]
1. I press Ctrl+Space in an empty line.
2. Autocomplete shows up.
3. I press Down arrow key. Aytocomplete goes to word "Any"
4. I press Up arrow key to go to word "Abs". Impossible. It FAILS.

**Comment by XusinboyBekchanov** [comment]
Here:
https://user-images.githubusercontent.com/32607344/133605887-1d76277b-5be1-4c58-92ab-432f5509cf19.mp4

**Comment by XusinboyBekchanov** [comment]
I need to check in Linux in the evening, maybe it does not work in Linux.

**Comment by demosthenesk** [comment]
> 1. I press Ctrl+Space in an empty line.
> 2. Autocomplete shows up.
> 3. I press Down arrow key. Aytocomplete goes to word "Any"
> 4. I press Up arrow key to go to word "Abs". Impossible. It FAILS.
> 
> i test it in a laptop without scroll button, i use arrows up/down

follow these steps to test in Linux.

**Comment by XusinboyBekchanov** [comment]
Fixed: ListView SelectedItemIndex property and ListItems.Add function in Linux:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/d32432c8f98bc8cb809f61efffe9c4e5b3db0fa3

**Comment by demosthenesk** [comment]
fixed!
