### ISSUE TITLE
In linux, TrackBar grid properties do not read/write in code

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#185]
In linux, TrackBar grid properties do not read/write in code

**Comment by XusinboyBekchanov** [comment]
Improved: Filled TrackBar Read and Write property function:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/d223641d14097659dfefcc5183f69643e3f1c238

**Comment by demosthenesk** [comment]
fixed!
