### ISSUE TITLE
In linux, TrackBar does not slide in run time

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#186]
In linux, TrackBar does not slide in run time

**Comment by XusinboyBekchanov** [comment]
Removed: Tick property of TrackBar. Added: MinValue, MaxValue, Position, LineSize, PageSize, ThumbLength, Frequency, TickStyle and Style property and AddTickMark method to TrackBar in Linux:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/f0cd18d71231552650c6937015047226dc975139

**Comment by demosthenesk** [comment]
fixed!
