### ISSUE TITLE
In linux, events OnScroll, OnChange of TrackBar do not work

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#187]
I tested OnScroll and OnChange events of TrackBar. They do not work.
Please make a test for all events of TrackBar.

**Comment by XusinboyBekchanov** [comment]
Added: OnScroll and OnChange events to TrackBar in Linux:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/74db01fc1b09771cc6f49d02347f8455f864cd88

**Comment by demosthenesk** [comment]
fixed!
