### ISSUE TITLE
In linux properties grid of ProgressBar Read/Write in code does not work.

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#188]
In linux properties grid of ProgressBar Read/Write in code does not work.

**Comment by XusinboyBekchanov** [comment]
Improved: Filled ProgressBar Read and Write property functions:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/de970393bd4717b59f0993d71fd799d1b8f39941

**Comment by demosthenesk** [comment]
i get errors:
/home/user/Downloads/VisualFBEditor-master/MyFbFramework/mff/ProgressBar.bas(266) error 9: Expected expression, found '='
/home/user/Downloads/VisualFBEditor-master/MyFbFramework/mff/ProgressBar.bas(278) error 9: Expected expression, found '='

**Comment by XusinboyBekchanov** [comment]
Fixed: StepBy and StepIt methods of ProgressBar in Linux:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/13c2a52f1b1f12ccb802c0aebed10e14a05698b2

**Comment by demosthenesk** [comment]
ok fixed!
