### ISSUE TITLE
In linux, in IDE after launch the progressbar down right, plays without purpose

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#189]
In linux, in IDE after launch the progressbar down right, plays without purpose

**Comment by XusinboyBekchanov** [comment]
Can you send a video?

**Comment by demosthenesk** [comment]
> Can you send a video?

one moment please... i will send

**Comment by demosthenesk** [comment]
https://user-images.githubusercontent.com/1350282/133887741-8a729913-3831-4469-9d0f-1d85ed3d1aae.MP4

**Comment by XusinboyBekchanov** [comment]
Fixed: Progress marquee in Linux:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/a779286f38388c8c89f33eae7d2f8f27b5099746

**Comment by demosthenesk** [comment]
fixed
