### ISSUE TITLE
Debugging -with integrated IDE debugger fails 

### ISSUE THREAD

**Issue by rexxitall** [XusinboyBekchanov/VisualFBEditor#19]
Hi, I tried to make the IDE Debugger work. I got always 
![image](https://user-images.githubusercontent.com/22050310/84333967-7765f680-ab91-11ea-8fe7-0487ceb7c5b3.png) Which is strange. I tryed all 3 possibilitys -g also -g -gstabs+ and dwarf is not recogniced at all.  So how to use the debugger :) ??? Or is he just "still work in progess ? "

**Comment by XusinboyBekchanov** [comment]
Try 32-bit VisualFBEditor and compile to 32-bit exe with -g (Use Debugger button auto adds "-g" key). 64-bit still work in progress.

**Comment by rexxitall** [comment]
That are not that good  news *sigh*. 32bit is outdated by years.  If i run ACAD with my enhancements i just have wasted at least two Gigs + OS - hm Might be possible to draw a garage still :) The Computer i use has 64 Gigs of RAM and sometimes even that is not enough. During night i try to utilze GDB - Works somehow but ... 
![image](https://user-images.githubusercontent.com/22050310/84351599-fec85f80-abbb-11ea-89e2-7524db316077.png) Debug fun looks different. And to load a 32bit DLL inside autocad is usually either a crash or some kind of strange roulette :)

**Comment by XusinboyBekchanov** [comment]
If Autocad is 64-bit then you must load a 64 bit dll

**Comment by rexxitall** [comment]
Nearly true. Some COM.DLLs are able to run even by 32 bit. But that is very special. Just as info. (There is a wrapper in some components - weired solution). In general you are totally right :) It usually crashes imediatly with the wrong dll or even a wrong definition. Absolute fastes way to close Autocad. Call a dll in VBA with the wrong variable type :D.  All your work has gone. That is the reason why i would love to get freebasic 64bit running and a usable IDE for it too. In fact if you look for speed you can forget a lot of things (marketing peoples i guess) tell. Lisp - slow ! VB.ne or C# also not really fast and a pain in the ass to develop. If you rebuild a dll you has to close acad first, use Visual Studio, make the dll, load acad, load the dll, open a drawing, do all things needed to get the point of debugging.... Such a turn is about 5 minutes each. Just to recognice that you creates bullshit again :) The most easy way to enhance Autocad ist still VBA. You can even change the program while running often (as long you do not defines new variables). The current VBA version is also really fast again (2013 was slow). Faster then .Net. :D. Maximum speed you get with a really compiled dll. The official way is to use C++ (If you do not has other hobbys). My way is to create dlls in freebasic for time critical tasks and call them either from VBA or by VB.net. They have to be 64 bit and therefore i have also to debug them in 64 bit. Which has the backdraft that freebasic and 64bit seems to be a new land for the freebasic guys (since years). In 32bit nearly all works out of the box. In 64bit... Fun Fun Fun. Something is usually always missing or broken or not documented. Takes a week to get the actual sqlite version, scriptbasic and even silly dictionarys to run in 64 bit. Usually you has to compile the whole thing from scratch. After that its for sure very fast :)

**Comment by XusinboyBekchanov** [comment]
Integrated IDE Debugger x64 bit correctly works with key "-g -Wc -gdwarf-2".
You need also objdump.exe in root folder VisualFBEditor.

I am attaching objdump.exe
In future versions, I will include it in the VisualFBEditor distribution
[objdump.zip](https://github.com/XusinboyBekchanov/VisualFBEditor/files/4766189/objdump.zip)

You also can use Standalone GUI Debugger: FBDebugger 2.96 (Integrated IDE Debugger based on this program) (https://freebasic.net/forum/viewtopic.php?f=8&t=13935)
In the debugger settings, this line is also available.

**Comment by rexxitall** [comment]
hm same result as with the standalone debugger - the reason i do not use that too. 
![image](https://user-images.githubusercontent.com/22050310/84422904-fe60b080-ac1d-11ea-9208-b39e29b0b38d.png) This dialog needs also a cancel button

**Comment by XusinboyBekchanov** [comment]
When I worked with the Integrated IDE Debugger version was 2.93. Now the new version 2.96 can be a lot of things fixed in the new version of FBDebugger.

Yes, I will add a cancel button, then it will be more convenient.

**Comment by rexxitall** [comment]
;) Well it would :) Use Taskmanager  isnt that fun. I was thinking it might be a problem with the compiler and the object dump tool. So i switched to FBC 1.0.7 . Which in fact start to debug in 64bit :) Congratulations, you seems the *first* to reach that target :) And i can also see the content of the vars  ! Works as long until i decided to stop debuggin :d Then i got this  
![image](https://user-images.githubusercontent.com/22050310/84426571-be9cc780-ac23-11ea-9405-a8a0854e83a1.png)

![image](https://user-images.githubusercontent.com/22050310/84425864-8b0d6d80-ac22-11ea-9698-e311e089779d.png)
 But definitly it will help me :)

**Comment by rexxitall** [comment]
Works also wit 1.08 :) GREAT !!!
