### ISSUE TITLE
In linux, right click in code does not show pop up menu !

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#192]
1. Open Project1
2. Try to right click in code
3. No pop up menu. FAILS
[Project1.zip](https://github.com/XusinboyBekchanov/VisualFBEditor/files/7191479/Project1.zip)

**Comment by XusinboyBekchanov** [comment]
Fixed: TabPage ImageKey property, PopupMenu ParentWindow property and ListView View property in Linux:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/ff00e92661d2228a14b8a23bfed8b75b12c2143b

**Comment by demosthenesk** [comment]
fixed
