### ISSUE TITLE
IA__gtk_icon_view_set_pixbuf_column: assertion 'column_type == GDK_TYPE_PIXBUF' failed

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#193]
when i run Form1 i get this error in console
(Form1:319191): Gtk-CRITICAL **: 11:40:56.889: IA__gtk_icon_view_set_pixbuf_column: assertion 'column_type == GDK_TYPE_PIXBUF' failed

[Project1.zip](https://github.com/XusinboyBekchanov/VisualFBEditor/files/7191500/Project1.zip)

**Comment by XusinboyBekchanov** [comment]
Fixed: TabPage ImageKey property, PopupMenu ParentWindow property and ListView View property in Linux:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/ff00e92661d2228a14b8a23bfed8b75b12c2143b

**Comment by demosthenesk** [comment]
fixed
