### ISSUE TITLE
Is it possible to implement in linux Sort and View properties for ListView ?

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#194]
Is it possible to implement in linux Sort and View properties for ListView ?

_Originally posted by @demosthenesk in https://github.com/XusinboyBekchanov/VisualFBEditor/discussions/98#discussioncomment-1353806_

> Yes, it is possible.

**Comment by XusinboyBekchanov** [comment]
Added: ListView Sort property in Linux, Fixed: ListView View property in Linux:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/aaef5fe7f3f3e30553a25ffcfddd7bed36761616

**Comment by demosthenesk** [comment]
added!
