### ISSUE TITLE
In linux, when change View of ListView OnItemClick is not trigered

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#195]
If i change View of ListView control other than 1-vsDetails, OnItemClick is not work

**Comment by XusinboyBekchanov** [comment]
Fixed: ListView View property in Linux:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/4c329fa33f652af552a55afbfe9361bf1a3240ad

**Comment by demosthenesk** [comment]
fixed!
