### ISSUE TITLE
In linux, varius TreeView events not implemented yet

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#196]
This is events possible:
1. OnAfterLabelEdit
2. OnNodeClick
3. OnNodeDblClick
4. OnNodeExpanded
5. OnNodeExpanding

_Originally posted by @XusinboyBekchanov in https://github.com/XusinboyBekchanov/VisualFBEditor/discussions/98#discussioncomment-1361473_

**Comment by XusinboyBekchanov** [comment]
Added: IsChild property to Control in Linux, Get by index function to Dictionary, OnItemDblClick, OnItemKeyDown and OnSelectedItemChanging events to ListView in Linux, Added: Images, SelectedImages and EditLabels property to TreeView in Linux, DraggedNode function to TreeView in Linux, OnNodeClick, OnNodeDblClick, OnNodeCollapsing, OnNodeCollapsed, OnNodeExpanding, OnNodeExpanded, OnSelChanging, OnBeforeLabelEdit and OnAfterLabelEdit events to TreeView in Linux
https://github.com/XusinboyBekchanov/MyFbFramework/commit/697c25a95cb5e98df22438abf6e357d03ba69af5

**Comment by demosthenesk** [comment]
fixed!
