### ISSUE TITLE
In linux, latest version of VFBE can not open Project file

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#198]
1) i can not open Project2.vfp.
IDE crashes.

2) If i create a new project, ide crashes on Close Project.

**Comment by demosthenesk** [comment]
[Project2.zip](https://github.com/XusinboyBekchanov/VisualFBEditor/files/7207740/Project2.zip)

i can not open Project2.vfp

**Comment by XusinboyBekchanov** [comment]
I'll take a look in the evening.

**Comment by XusinboyBekchanov** [comment]
Have both been compiled? IDE and the library?

**Comment by demosthenesk** [comment]
> Have both been compiled? IDE and the library?

yes
this issue exists only on Open/Close Projects

**Comment by XusinboyBekchanov** [comment]
Fixed: TreeView OnSelChanging event:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/a594874b96c71abadb153948f72efc9fb4d4d2fa

Fixed: Designer:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/11baa604e9ce90e0cddca7b0de4f3f081922317e

**Comment by demosthenesk** [comment]
fixed!
