### ISSUE TITLE
external tools window needs own menu entry

### ISSUE THREAD

**Issue by rexxitall** [XusinboyBekchanov/VisualFBEditor#20]
Having  tools or add-ins is fine but it is unhandy if you put them in a sub menu to call them.  They should be able to call directly if defined. Best would be to run them also by a keyboard shortcut.

**Comment by XusinboyBekchanov** [comment]
This added:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/c9c6cce3b63bc4920bf42939bd47a1ee7e7ce373
