### ISSUE TITLE
In linux, Animate control not shown in designer

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#200]
In linux, Animate control not shown in designer.

**Comment by XusinboyBekchanov** [comment]
Added: Animate Control in Linux:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/2de4874368ec8350a64bf77c611cf331059dcae6

Added: Animate Control Example:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/d7de6f7cc6f3e624fbd69c65c1d2c6df4068a250

**Comment by demosthenesk** [comment]
fixed!
