### ISSUE TITLE
In linux, Animate control read/write grid properties and in code editor, not work yet

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#201]
In linux, Animate control read/write grid properties and in code editor, not work yet

**Comment by XusinboyBekchanov** [comment]
Improved: Filled Animate Read and Write property functions:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/161a2eb09b94ba1f01ded7b2f9f9415f53466764

**Comment by demosthenesk** [comment]
When i design an Animate control on a form there is no change in code editor.
No code is added, no include no constructor no properties.

**Comment by XusinboyBekchanov** [comment]
Added: Animate Control in Linux:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/2de4874368ec8350a64bf77c611cf331059dcae6

Added: Animate Control Example:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/d7de6f7cc6f3e624fbd69c65c1d2c6df4068a250

**Comment by demosthenesk** [comment]
fixed!
