### ISSUE TITLE
In linux, Properties Tab closes after setting one property

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#202]
1. Add a form.
2. Add Animate control.
3. Set a property from grid - properties.
4. Properties tab closes

**Comment by XusinboyBekchanov** [comment]
Fixed: Closing Properties window on select from combo:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/cfc16c6dfd42869655e22429e50e636e418c73c7

**Comment by demosthenesk** [comment]
fixed!
