### ISSUE TITLE
Pinned.png is out of Resources folder.

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#203]
There is a png named Pinned.png in master folder.
Should not be inside Resources folder ?

**Comment by XusinboyBekchanov** [comment]
Thanks, I removed it.

Delete Pinned.png:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/89acb7ee36dff736b04fd792a14023be7f1b820c

**Comment by demosthenesk** [comment]
fixed!
