### ISSUE TITLE
In linux, Properties Tab closes when click form in designer or code editor

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#204]
When i click the form in designer or when i try to design a control then Properties Tab closes

**Comment by demosthenesk** [comment]
Also the properties tab closes when i click inside code editor.

**Comment by XusinboyBekchanov** [comment]
Fixed: Automatically close Properties Window on open module (without designer):
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/87baecfe73b5bc2c4d2d80c1ba0b8efb1123df8d

If you pin the properties window, it will be constantly open.

**Comment by demosthenesk** [comment]
> Fixed: Automatically close Properties Window on open module (without designer):
> [87baecf](https://github.com/XusinboyBekchanov/VisualFBEditor/commit/87baecfe73b5bc2c4d2d80c1ba0b8efb1123df8d)
> 
> If you pin the properties window, it will be constantly open.

There is no pin icon-button to use

**Comment by demosthenesk** [comment]
> > Fixed: Automatically close Properties Window on open module (without designer):
> > [87baecf](https://github.com/XusinboyBekchanov/VisualFBEditor/commit/87baecfe73b5bc2c4d2d80c1ba0b8efb1123df8d)
> > If you pin the properties window, it will be constantly open.
> 
> There is no pin icon-button to use

OK...i found it......
