### ISSUE TITLE
In linux, Designer has no scrollbars for forms bigger than designer size

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#205]
I open Animate example but form height is too large for designer view and there is no scrollbars to scroll down the form to show the 2 buttons

**Comment by XusinboyBekchanov** [comment]
Improved: Changed Scroll Window position:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/dd69e02cda68d744e70bf408835318c3c0a3df60

Added: Scrollbars to Designer in Linux:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/7305639230ed36f0ee156d968853d3af1022ddd8

**Comment by demosthenesk** [comment]
fixed!
