### ISSUE TITLE
In linux, the pin button for Properties tab is disappearing some times

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#206]
I cant pin the properties tab.
The pin button is disappeared.

**Comment by demosthenesk** [comment]
1. open IDE
2. The pin button is disappeared
3. Click another window, in order the IDE looses focus
4. Click again IDE the pin button appears

**Comment by demosthenesk** [comment]
i think it is MATE's issue...

**Comment by demosthenesk** [comment]
Now after
> Improved: Changed Scroll Window position:
> [XusinboyBekchanov/MyFbFramework@dd69e02](https://github.com/XusinboyBekchanov/MyFbFramework/commit/dd69e02cda68d744e70bf408835318c3c0a3df60)
> 
> Added: Scrollbars to Designer in Linux:
> [7305639](https://github.com/XusinboyBekchanov/VisualFBEditor/commit/7305639230ed36f0ee156d968853d3af1022ddd8)

1. Open IDE
2. Pin buttons appeared
3. Maximize Window - IDE
4. Pin buttons disappeared
5. Loose focus the IDE. Click another window
6. Gain focus IDE. Click IDE
7. Pin buttons appeared

**Comment by XusinboyBekchanov** [comment]
This can be fixed.

**Comment by demosthenesk** [comment]
The missing Pin buttons
![Screenshot at 2021-09-28 13-03-50](https://user-images.githubusercontent.com/1350282/135067109-b12b0782-4957-4635-b8bc-1bd979a3421f.png)

**Comment by XusinboyBekchanov** [comment]
Added: ToolButton Width and Height property in Linux:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/76f3753329df9366b5f3abdbc5c5cba7e0386fc3

Fixed: Left and Right Pin buttons position in Linux:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/aa6bec47914f26840198c9d61302cac2f704752e

**Comment by demosthenesk** [comment]
fixed!
