### ISSUE TITLE
In linux, can not scroll Vertical separator between Code editor and Designer 

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#207]
1. Load Project2
2. Try to scroll vertical separator between editor and designer in order to view code
3. Impossible
[Project2.zip](https://github.com/XusinboyBekchanov/VisualFBEditor/files/7253926/Project2.zip)
![Screenshot at 2021-09-29 20-32-05](https://user-images.githubusercontent.com/1350282/135319622-5b3e176c-78dc-48e3-bee2-48abafa8d05a.png)

**Comment by XusinboyBekchanov** [comment]
Fixed: Width and Height properties of Components in Linux:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/d45d4c3a8f90ff5fbb0d9fc566527e0b5c6b5bbb

Improved: Pin buttons:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/45f08c0f57d47371c2ff0656555a1ceb1708852c

**Comment by demosthenesk** [comment]
fixed!
