### ISSUE TITLE
In linux, Chart DonutWidth can not be set by properties grid

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#208]
DonutWidth is always set to 0 whatever value be set from properties grid

**Comment by XusinboyBekchanov** [comment]
Fixed: Write Single type property in Property Grid:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/93a0bdcb48cf2454b7c12d8260212432675bff73

**Comment by demosthenesk** [comment]
fixed!
