### ISSUE TITLE
In linux, DateTimePicker does not work yet

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#209]
1. Add a DateTimePicker Control
2. No code added in editor

**Comment by XusinboyBekchanov** [comment]
Added: DateTimePicker in Linux:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/6296d15fcd8d66b9f50ea5ed45213169b7563474

**Comment by demosthenesk** [comment]
fixed!
