### ISSUE TITLE
Feature request Tool Wrapper for external Tools which are precompiled or a interpreted not written in freebasic.

### ISSUE THREAD

**Issue by rexxitall** [XusinboyBekchanov/VisualFBEditor#21]
Some tools you may have already ready to use. For example a "grep.exe" some kind of other command line utility as well. Such tools should be able to run without to write a add-in wrapper first. They should be able to run also by havin a "standard Wrapper or interpreter". Things like CMD.exe, POWERSHELL.exe , CScript.exe. This would also allow to use scripting inside the IDE on a descent level. To act like that they need some "parameter" Project directory, filename, marked lines ... The result of the action should be able to addess  the terminal window, the editor code (replace marked lines) or whole file, /dev Null . They should have some run modes. Like acting hidden, showing output, acting like a filter and by redirectind stdin, stdout, stderr to either the approbiate window or to replace code. Such a feature is very powerful cause now peoples can enhace functionality without knowing about the internal functions of the ide, they can add some level of scripting, and they can use tools which are already written :)

**Comment by XusinboyBekchanov** [comment]
This added:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/c9c6cce3b63bc4920bf42939bd47a1ee7e7ce373
