### ISSUE TITLE
In linux, Change Locale of DateTimePicker control !

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#210]
I have Date/Time in Greek locale in my system.
When i add a DateTimePicker control by default it shows date in system locale. (Greek)

Is it possible to choose the locale for DateTimePicker control.
I want the default to be in English and to be an option for other locales.

**Comment by XusinboyBekchanov** [comment]
I cannot change the language of the calendar and date/time format.

**Comment by demosthenesk** [comment]
ok i close it
