### ISSUE TITLE
In linux, DateTimePicker, when change year from month calendar the year always increasing with no stop

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#212]
In linux, DateTimePicker, when change year from month calendar the year always increasing with no stop

**Comment by XusinboyBekchanov** [comment]
Fixed: Changing year and month in DateTimePicker calendar on Linux:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/1766dc5a32153669428e0f1eb764e029deafd5a7
