### ISSUE TITLE
In linux, IPAddress control not implemented yet !

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#218]
In linux, IPAddress control not implemented yet !

**Comment by XusinboyBekchanov** [comment]
Added: IPAddress control on Linux:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/00c75ff54c1a1e7bbcd3c02c13077debe52486ee

Added: OnChange and OnFieldChanged events to IPAddress control on Linux:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/71609a5d38b96ec9f3b39dce3f425b66ea037872

**Comment by XusinboyBekchanov** [comment]
Fixed: IPAddress control Text property:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/9aa93e054e95a1b1e1056755a97e4ce4be138535

**Comment by demosthenesk** [comment]
fixed!
