### ISSUE TITLE
In linux, LinkLabel control: How to add a link ?

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#219]
In linux, LinkLabel control: How to add a link ?

**Comment by XusinboyBekchanov** [comment]
When writing a property to the Text through the Property Grid, the program itself will add double quotes in the code.

If you write in the code yourself, then you need to write like this:
`.Text = "e-mail: <a href=""mailto:bxusinboy@mail.ru"">bxusinboy@mail.ru</a>"`
