### ISSUE TITLE
Feature request. Using GDB or other debugger seamless inside IDE

### ISSUE THREAD

**Issue by rexxitall** [XusinboyBekchanov/VisualFBEditor#22]
Uing GDB seamless inside the IDE. Note that gdb has a so called IM Interface. Which is designed to act as "man in the middle" for IDE Programs. Might be worth to consider. Such a wrapper is more easy to maintain as a whole full featured debugger :) And would solve my 64 Bit Problem. Same for the Profiler. Both are Part of Freebasic. Would also make the IDE more interesting. Actually there are NO really usable GUI Wrappers for Windows availeable. I tried to use STDIN STDERR STDOUT redirect to utilite GDB. But this guy has also a TCPIP Sock interface which make the Thing more interesting - and is usually more stable than the weired slow redirection.

**Comment by XusinboyBekchanov** [comment]
Yes, in my plan there is also an additional Integrated IDE Debugger with gdb. But I haven't started it yet.

**Comment by rexxitall** [comment]
Yes was also my first so called Plan "B" :) Well you can warp somethig aroud as you could see. Even without any big knowledge how to use GDB i was able to get something to work. Stupidly is GDB a very mature program and the documentation has around 500 Pages in a PDF. To write such a wrapper you need to know at least partly how to tell that command GDB first and then you has to parse the Results. Nothing i can write aside my normal work at the moment. I am happy if i get my job done :D

**Comment by rexxitall** [comment]
PDf with GDB Manual THE IM Interface is the interesting ones i guess :)
[Debugger.pdf](https://github.com/XusinboyBekchanov/VisualFBEditor/files/4771364/Debugger.pdf)

**Comment by XusinboyBekchanov** [comment]
Added: Integrated GDB Debugger:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/bfb9e6604a6ffce924379ed2550c1d9e111a8346
