### ISSUE TITLE
In linux, has NativeFontControl been removed ?

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#220]
In linux, has NativeFontControl been removed ?
i can't find it in toolbox.

**Comment by XusinboyBekchanov** [comment]
I couldn't get it to work in Windows. It is not necessary in Linux, I think. So I removed it.

Here is some information on this control:
https://docs.microsoft.com/en-us/windows/win32/controls/cc-faq-localization
