### ISSUE TITLE
In linux, PageScroller has not been implemented yet

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#223]
In linux, PageScroller has not been implemented yet.

**Comment by XusinboyBekchanov** [comment]
PageSсroller has already been made earlier:
![image](https://user-images.githubusercontent.com/32607344/139514185-2d585f42-b180-4b6c-9c13-ca605a70dae7.png)

**Comment by demosthenesk** [comment]
ok i had old version!
