### ISSUE TITLE
Formatting Corrupts Optional Values

### ISSUE THREAD

**Issue by AndrewLindsay** [XusinboyBekchanov/VisualFBEditor#225]
I have converted over some files that I had written in plain Freebasic, using Notepad++ as my editor.  These programs compiled flawlessly when I compiled them manually.  I have since decided to use the visual IDE to create a GUI for it, I found that when I compiled the programs, while they compiled without issue, they did not run, when they had in the original manual compiled version.

Long story short, the IDE changes the code/format when it saves, so the following line

Function foobar (foo as double, bar as double = 1e-3) as double

gets converted to 

Function foobar (foo as double, bar as double = 1e - 3) as double

Freebasic then interprets this as -3, not 0.001.

When I change it to Function foobar (foo as double, bar as double = 0.001) as double

everything runs perfectly, but when I am dealing with exponents, I'd like to use exponents, because I don't want to have to count '0's each time I want a very small or very large number.

**Comment by XusinboyBekchanov** [comment]
Fixed: Formatting numbers with e- notation:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/9535a75e7abbf7237ac1ab4ad3c9be7677026410

**Comment by XusinboyBekchanov** [comment]
Fixed: Compiling with fbc 64-bit
https://github.com/XusinboyBekchanov/MyFbFramework/commit/8384ec476055138276cf324da025efc9e10fbaac
