### ISSUE TITLE
Properties Tool Window Broken

### ISSUE THREAD

**Issue by AndrewLindsay** [XusinboyBekchanov/VisualFBEditor#226]
Hello,
After the updates to accommodate the exponent options, and the fix for the 64bit compile, the panel for the properties is now bugged, with all the properties and values bunched up in the center of the pan
![BrokenPropertiesPanel](https://user-images.githubusercontent.com/4137215/140870468-0c8f52db-d0ff-41f5-abc9-dcd4e64c489d.png)
el, without the ability to select anything.

**Comment by XusinboyBekchanov** [comment]
Fixed: Rect and Point types on 64-bit:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/b67f293d64fdf8c4d300f5cc63076b0587318347

**Comment by XusinboyBekchanov** [comment]
Is this Windows 11?

**Comment by AndrewLindsay** [comment]
Yes, windows 11

**Comment by AndrewLindsay** [comment]
I've recompiled everything (both the DLL and the IDE), It's all working again now.

**Comment by XusinboyBekchanov** [comment]
https://user-images.githubusercontent.com/32607344/140911182-7418397a-c5a5-4ffa-b076-dbcb6b6d392b.mp4

**Comment by AndrewLindsay** [comment]
Yes, it doesn't work like that for me...

**Comment by XusinboyBekchanov** [comment]
Then I'm waiting for a video from you.

**Comment by AndrewLindsay** [comment]
It's a bit hit and miss for me.  It appears that if I create the tab control and then add pages straight away, it will work, but if I try to add a page to an existing tab control after I have added other controls, it doesn't work that way.

**Comment by XusinboyBekchanov** [comment]
Fixed: TabControl RequestAlign (for TabPages):
https://github.com/XusinboyBekchanov/MyFbFramework/commit/2466926ac2abea61c2428abe5d205875f6c1206c

**Comment by XusinboyBekchanov** [comment]
Now there should be no problem when drawing a TabPage to an already existing TabControl. Because the previous TabPage is now located normally.

**Comment by AndrewLindsay** [comment]
Brilliant!!  I am recompiling everything now.

Do you happen to have a tutorial on how to add a menu (File, Edit, About etc) to a form?

**Comment by XusinboyBekchanov** [comment]
No manual available. But you can add MainMenu and with the right mouse button you need to open the Menu Editor. There you can add an menu items.

**Comment by XusinboyBekchanov** [comment]
You also need to select this MainMenu1 in the Menu property of the form.

**Comment by XusinboyBekchanov** [comment]
You also need to select this MainMenu1 in the Menu property of the Form.

**Comment by AndrewLindsay** [comment]
Thanks!  I worked out that I need to select the box around the menu icon to select it, I tried to click on it, and double click, and it just kept on selecting and raising events on the main form.  But I've got the hang of it now.
My next task no doubt will be to explore the chart examples that youve created, or try to find out how to put an XY chart on a dialog, as I'm not sure you have included an XY-scatter plot in your chart examples as of yet.
There will be more questions I am sure, and thank you for your work, it's fantastic.

**Comment by XusinboyBekchanov** [comment]
>Thanks! I worked out that I need to select the box around the menu icon to select it, I tried to click on it, and double click, and it just kept on selecting and raising events on the main form. But I've got the hang of it now.

Fixed: Select Components in Designer:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/a1b35cfae13f06bd8fb29a018e6407045b8f227e

>My next task no doubt will be to explore the chart examples that youve created, or try to find out how to put an XY chart on a dialog, as I'm not sure you have included an XY-scatter plot in your chart examples as of yet.
There will be more questions I am sure, and thank you for your work, it's fantastic.

Yes, you can see examples of Chart control.
