### ISSUE TITLE
Position of controls jumps to -32768

### ISSUE THREAD

**Issue by AndrewLindsay** [XusinboyBekchanov/VisualFBEditor#227]
Sometimes when I modify a control, it will disappear from the dialog box display.  I have found that it is closely linked (but not always) to when I try to fine-tune the positioning via the properties dialog box.  While I may put in say 20, for the top or left coordinate, the widget will disappear from the dialog box, and when I look at the form code, I find that the parameter that I was trying to modify is replaced with -32768 as the value.  I'm using Windows 11, in the 64 bit mode dialog box.  So I'm guessing it could be an int/long type issue.

**Comment by XusinboyBekchanov** [comment]
Fixed: Change numeric properties from Property Grid on 64-bit:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/1196664cb519556e72ec422f4e94055feb7f9015

**Comment by AndrewLindsay** [comment]
Brilliant, thanks for fixing this.

**Comment by XusinboyBekchanov** [comment]
Thank you too.
