### ISSUE TITLE
Issues with exponents again

### ISSUE THREAD

**Issue by AndrewLindsay** [XusinboyBekchanov/VisualFBEditor#228]
Sorry to be a pain, but the exponent error is still in the main editing function as you type.

The following line
    W10(1) = 6.66713443086881E-02

as soon as you hit return, the editor changes it to

    W10(1) = 6.66713443086881E - 02

So, instead of being 0.066713....  it is 4.667 (6.667 - 2)

**Comment by XusinboyBekchanov** [comment]
Fixed: Formatting numbers with E- notation:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/7fb373495b76a7e70a441e0b180fe8af6a34d846

Now the big E is also added. Thanks for your issue.
