### ISSUE TITLE
Property of "Align" is not working during Form Edit mode

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/VisualFBEditor#229]
Property of "Align" is not working during Edit mode

**Comment by XusinboyBekchanov** [comment]
Changed: Align property type from Integer to Enum:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/842a43a3338c219e13708b69b7842e459c1bd417

Fixed: Controls Align property:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/501f202915beeb1b4bbd68d495d829d664eaecef

**Comment by XusinboyBekchanov** [comment]
Fixed: Set property from code:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/fe446be6fa0c0ab65139d451bc4f7af3020151ed
