### ISSUE TITLE
GUI Designer "Toolbox missing"

### ISSUE THREAD

**Issue by rexxitall** [XusinboyBekchanov/VisualFBEditor#23]
For sure if someones wants to check aout a VISUAl Designer he will first create a new form. So do i. Then i was looking around where the henk all the Buttons and other gadgets are located. Found them finally hidden behind the Project explorer.  I would suggest to make a setting in the Options which is activaed by defaul. The action of the setting is that if the GUI designer got activated also the gadget toolbox got the focus and get activated. If the code editor is activated the project exploerer got the focus. This is a quick fix i guess. The Gadget Tools should get a own window finally :)

**Comment by XusinboyBekchanov** [comment]
This fixed:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/6cc146b62be47c91c5ab85c1eda144ec30244b68

**Comment by rexxitall** [comment]
Thanks
