### ISSUE TITLE
Feature request Project  *Debugger* command line arguments

### ISSUE THREAD

**Issue by rexxitall** [XusinboyBekchanov/VisualFBEditor#24]
Hi, How about to pass also command lines to the standalone gdb and  
not only arguments to the program ?
This command line argument would force gdb to run a few commands first 
"-x c:\freebasic\projects\x\GDBC.txt" // Take the commands from a textfile for example or do not show version info first...

the file just looks something like this :

file c:/freebasic/projects/x/main.exe
b 1
r

e.g. 
load the/or a main program
set a breakpoint at first line (coud we export them from the IDE ?)
run it

**Comment by XusinboyBekchanov** [comment]
This fixed:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/e4b0ad99e05b8df0a725c7302c4634f5a6f26ab9
