### ISSUE TITLE
Save the file in Utf8/CRLF format, which is actually UTF8/LF format

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/VisualFBEditor#243]
Save the file in Utf8/CRLF format, which is actually UTF8/LF format

![Untitled](https://user-images.githubusercontent.com/35757455/153339699-8342e993-3ea7-4038-838c-6f68529924a7.png)

**Comment by XusinboyBekchanov** [comment]
Fixed: Saving files with New Line types:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/14a2eb93dce2da661012ca2818a248d299432914
