### ISSUE TITLE
Bug: Still "No resources found in RC file"

### ISSUE THREAD

**Issue by tednilsen** [XusinboyBekchanov/VisualFBEditor#245]
The latest commit (d438f8f5f844b8264b77280f2ee97fdfa7a57be9) still won't compile, still "No resources found in RC file"

```
C:\FreeBasic\VisualFBEditor\src>fbc64.exe -v -w all "VisualFBEditor.bas" -s gui -x "../VisualFBEditor64.exe" "VisualFBEditor.rc" -i "C:\FreeBasic\VisualFBEditor\MyFbFramework"
FreeBASIC Compiler - Version 1.09.0 (2021-12-31), built for win64 (64bit)
Copyright (C) 2004-2021 The FreeBASIC development team.
standalone
target:       win64, x86-64, 64bit
backend:      gcc
compiling:    VisualFBEditor.bas -o VisualFBEditor.c (main module)
compiling C:  C:\FreeBasic\FreeBASIC\bin\win64\gcc.exe -m64 -march=x86-64 -S -nostdlib -nostdinc -Wall -Wno-unused -Wno-main -Werror-implicit-function-declaration -O0 -fno-strict-aliasing -frounding-math -fno-math-errno -fwrapv -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables -Wno-format -masm=intel "VisualFBEditor.c" -o "VisualFBEditor.asm"
assembling:   C:\FreeBasic\FreeBASIC\bin\win64\as.exe --64 --strip-local-absolute "VisualFBEditor.asm" -o "VisualFBEditor.o"
compiling rc:               C:\FreeBasic\FreeBASIC\bin\win64\GoRC.exe /ni /nw /o /machine X64 /fo "VisualFBEditor.obj" "VisualFBEditor.rc"

Error!
No resources found in RC file
OBJ file not made
compiling rc failed: 'C:\FreeBasic\FreeBASIC\bin\win64\GoRC.exe' terminated with exit code 1
```

```
C:\FreeBasic\VisualFBEditor\src>fbc32.exe -v -w all "VisualFBEditor.bas" -s gui -x "../VisualFBEditor32.exe" "VisualFBEditor.rc" -i "C:\FreeBasic\VisualFBEditor\MyFbFramework"
FreeBASIC Compiler - Version 1.09.0 (2021-12-31), built for win32 (32bit)
Copyright (C) 2004-2021 The FreeBASIC development team.
standalone
target:       win32, 486, 32bit
backend:      gas
compiling:    VisualFBEditor.bas -o VisualFBEditor.asm (main module)
assembling:   C:\FreeBasic\FreeBASIC\bin\win32\as.exe --32 --strip-local-absolute "VisualFBEditor.asm" -o "VisualFBEditor.o"
compiling rc:               C:\FreeBasic\FreeBASIC\bin\win32\GoRC.exe /ni /nw /o /fo "VisualFBEditor.obj" "VisualFBEditor.rc"

Error!
No resources found in RC file
OBJ file not made
compiling rc failed: 'C:\FreeBasic\FreeBASIC\bin\win32\GoRC.exe' terminated with exit code 1
```

Both VisualFBEditor and MyFbFramework are the freshest, I'm using the latest FreeBasic too as you can see...

**Comment by XusinboyBekchanov** [comment]
Your VisualFBEditor.rc file may be empty.

Because there is data in this file in github:
https://github.com/XusinboyBekchanov/VisualFBEditor/blob/master/src/VisualFBEditor.rc

For me, it compiles successfully.

**Comment by tednilsen** [comment]
> Your VisualFBEditor.rc file may be empty.
> 
> Because there is data in this file in github: https://github.com/XusinboyBekchanov/VisualFBEditor/blob/master/src/VisualFBEditor.rc
> 
> For me, it compiles successfully.

No it's not empty(I've checked), it's the latest commit from your github.
I have no clue why it's reporting empty - I've tried various gcc backends and also 32/64 versions - all reports the same...
I've been fiddeling for many hours, and still no luck! If you can please upload the working version (Dark theme) and maybe I / you can resolve the issue later.

```
C:\FreeBasic\FreeBASIC\bin\win32>gcc.exe --version
gcc.exe (MinGW-W64 i686-posix-sjlj, built by Brecht Sanders) 9.3.0

C:\FreeBasic\FreeBASIC\bin\win64>gcc --version
gcc (x86_64-win32-sjlj-rev0, Built by MinGW-W64 project) 8.1.0

C:\FreeBasic\FreeBASIC\bin\win64>gcc --version
gcc (x86_64-win32-seh, Built by MinGW-W64 project) 4.8.2
```

**Comment by XusinboyBekchanov** [comment]
Here only exe in dll files:
[VisualFBEditor.zip](https://github.com/XusinboyBekchanov/VisualFBEditor/files/8057662/VisualFBEditor.zip)

**Comment by chunmingwang** [comment]
I found this issue either，My solution is conver EOL from LF to CRLF both of ./MyFbFramework/mff/mff.rc and ./src/VisualFBEditor.rc files

**Comment by chunmingwang** [comment]
> > I found this issue either，My solution is conver EOL from LF to CRLF both of ./MyFbFramework/mff/mff.rc and ./src/VisualFBEditor.rc files
> 
> I converted the file VisualFBEditor.rc EOL to Windows CRLF.... and now it works! Compiled, linked and running just fine - thanks! 👍

this should be a fbc issue
fbc should be compatible with Cr / Lf or CrLf
because fbc support to compile Windows / Linux and other applications

**Comment by XusinboyBekchanov** [comment]
Fixed: Saving resource files (*.rc) end lines with CRLF:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/a952ab20fa52dfc609873c2657b3f20a0a5b6bcf

Fixed: Saving resource files (*.rc) end lines with CRLF:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/b58882dee63f6f5dec86738ee3b5a5b57448fbe0

Thank you.
