### ISSUE TITLE
Segmentation violation signal

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/VisualFBEditor#247]
Message box popup duplicate process

1, Start VisualFBEditor32.exe (Don't Nothing)
2, Menu(File->New)
3, New(Projects->GUI Application->OK)
4, Close VisualFBEditor32.exe
5, Save changes to the following files? (No)

Jump out of the following message box

Segmentation violation signal (12) in line -1 in function HANDLE in module F:\OfficePC_Update\!FB\!VisualFBEditor\VisualFBEditor-master\MyFbFramework\mff\Component.bas

![Untitled](https://user-images.githubusercontent.com/35757455/154011392-85f9af6a-4712-48ee-84b5-7cd0e76a450a.png)

**Comment by XusinboyBekchanov** [comment]
Fixed: Showing error message on closing IDE:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/58393a47f7f9a1f1e6f0e0b6c84b2d4fe130bd04
