### ISSUE TITLE
Format Project crashes Editor

### ISSUE THREAD

**Issue by rexxitall** [XusinboyBekchanov/VisualFBEditor#25]
I was curious how to work Format the whole project. The result was that the IDE crashes.
[X.zip](https://github.com/XusinboyBekchanov/VisualFBEditor/files/4766757/X.zip). Might be possible that something is also useful in it.

**Comment by XusinboyBekchanov** [comment]
I just saw, I’ll fix it now.

**Comment by XusinboyBekchanov** [comment]
This fixed:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/4628a986d29e22164a0ede22e9ad2887e342ad87

**Comment by rexxitall** [comment]
works :)
