### ISSUE TITLE
undefined reference to `WinMain'

### ISSUE THREAD

**Issue by retsyo** [XusinboyBekchanov/VisualFBEditor#252]
I try to compile the latest code of VisualFBEditor on windows 10 64bits according to the instruction on https://github.com/XusinboyBekchanov/VisualFBEditor

however
```
C:\tmp\VisualFBEditor-master\src>e:\prg\BASIC\fb\FreeBASIC-1.09.0-win64\fbc -s gui -x "../VisualFBEditor64.exe" "VisualFBEditor.rc" -i ..\..\MyFbFramework-master
e:\prg\BASIC\fb\FreeBASIC-1.09.0-win64\bin\win64\ld.exe: e:\prg\BASIC\fb\FreeBASIC-1.09.0-win64\lib\win64/libmingw32.a(lib64_libmingw32_a-crt0_c.o): in function `main':
R:\winlibs64-sjlj-9.3.0\mingw-w64-v7.0.0\mingw-w64-crt/crt/crt0_c.c:18: undefined reference to `WinMain'
```

btw, I can compile mff32/64.dll without problem

**Comment by XusinboyBekchanov** [comment]
You must include VisualFBEditor.bas on the command line

**Comment by chunmingwang** [comment]
VisualFBEditor的主页里最下面，作者有放完整的编译指令，可以去参考一下

**Comment by chunmingwang** [comment]
> I try to compile the latest code of VisualFBEditor on windows 10 64bits according to the instruction on https://github.com/XusinboyBekchanov/VisualFBEditor
> 
> however
> 
> ```
> C:\tmp\VisualFBEditor-master\src>e:\prg\BASIC\fb\FreeBASIC-1.09.0-win64\fbc -s gui -x "../VisualFBEditor64.exe" "VisualFBEditor.rc" -i ..\..\MyFbFramework-master
> e:\prg\BASIC\fb\FreeBASIC-1.09.0-win64\bin\win64\ld.exe: e:\prg\BASIC\fb\FreeBASIC-1.09.0-win64\lib\win64/libmingw32.a(lib64_libmingw32_a-crt0_c.o): in function `main':
> R:\winlibs64-sjlj-9.3.0\mingw-w64-v7.0.0\mingw-w64-crt/crt/crt0_c.c:18: undefined reference to `WinMain'
> ```
> 
> btw, I can compile mff32/64.dll without problem

VisualFBEditor的主页里最下面，作者有写完整的编译指令，可以去参考一下

**Comment by retsyo** [comment]
aha, I must be blind 2 hours ago
