### ISSUE TITLE
Application finished. Returned code: 12 - Segmentation violation signal

### ISSUE THREAD

**Issue by retsyo** [XusinboyBekchanov/VisualFBEditor#253]
I just compiled your latest VisualFBEditor and MyFbFramework on windows 10 64 bits.

Then I add a chart on the default form

# 1. good example
if i set `charStyle` to `cs_pie` or `cs_donut`, F5 compiles and runs an EXE without problem

# 2. bad example
## 2.1 set output code for 32 bits CPU
if i set `charStyle` to other style( for example, `cs_area`), F5 compiles, the GUI appears but disappears quickly and says 
```
16:29:29: Layout succeeded! Elapsed Time: 2.22 Seconds
16:29:29: Run: "main.exe"  ...
16:29:30: Application finished. Returned code: 12 - Segmentation violation signal
```

## 2.2 set output code for 64 bits CPU
if i set `charStyle` to other style( for example, `cs_area`), F5 compiles, the GUI appears but disappears quickly and says 
```
16:37:49: Layout succeeded! Elapsed Time: 7.57 Seconds
16:37:49: Run: "main.exe"  ...
16:37:52: Application finished. Returned code: 3221225477 - 
```

**Comment by XusinboyBekchanov** [comment]
Maybe you passed the variable incorrectly. Can you show the code. Chart Example with cs_area compiles fine (32 and 64).

**Comment by XusinboyBekchanov** [comment]
It turns out Chart without data is automatically terminated.

**Comment by retsyo** [comment]
so, you assign data to default pie/donut?

**Comment by XusinboyBekchanov** [comment]
>so, you assign data to default pie/donut?
There is no AxiItem in pie/donut.

Fixed: Chart control without data crashing:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/5995a9924ef0162d250e6e8c0080d5ccbdab1e1d
