### ISSUE TITLE
bug: recent sessions/folders/projects/files

### ISSUE THREAD

**Issue by retsyo** [XusinboyBekchanov/VisualFBEditor#256]
I just compiled your latest VisualFBEditor and MyFbFramework on windows 10 64 bits.
under menu `file->recent sessions/folders/projects/files`, I click all the 4 `clear recent opened`, now `file->recent sessions/folders/projects/files` becomes gray

Then I open a `frm` file and close VFB

now run VFB again. all previous items are restored to menu `file->recent sessions/folders/projects/files` again!

**Comment by XusinboyBekchanov** [comment]
Fixed: Saving Recent Files/Folders/Projects/Sessions in Settings:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/7190a2b5d30286972e17ad2f085c74d9363e8d96
