### ISSUE TITLE
bug, misplaced property and value in property editor

### ISSUE THREAD

**Issue by retsyo** [XusinboyBekchanov/VisualFBEditor#257]
I build new VFB from latest VFB and framework code

then I found that 
![vfb_designer_bug](https://user-images.githubusercontent.com/7960913/159644123-85c350e1-45a7-4c46-8f8e-ed14e0ee150d.png)

maybe it is still DPI problem in framework 
https://github.com/XusinboyBekchanov/VisualFBEditor/issues/255

**Comment by XusinboyBekchanov** [comment]
Fixed: Properties Window High DPI
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/0a9ae87cd51f63e6b630d452f9556ecbcf3f05cf
