### ISSUE TITLE
100% crash

### ISSUE THREAD

**Issue by retsyo** [XusinboyBekchanov/VisualFBEditor#259]
in vfb, `file/close all`, then open `c:\Users\USER\Downloads\VisualFBEditor.master\Examples\Chart\Chart Example.bas`, vfb crashes seconds

however, `file/close all`, then open `c:\Users\USER\Downloads\VisualFBEditor.master\Examples\ReBar Example\ReBar Example.bas` , vfb does not crash

**Comment by XusinboyBekchanov** [comment]
Fixed: Control Parent property:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/51feb803f0b1635cb9032abe644e9075362a2080

**Comment by XusinboyBekchanov** [comment]
Fixed: Crash 64-bit IDE on open Chart Example:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/5860f7d7e842781d3714d8a93c690fe5d2138b02

**Comment by XusinboyBekchanov** [comment]
There is still some work to be done.

**Comment by XusinboyBekchanov** [comment]
I eventually fixed it.

Fixed: Crash when double open Chart Example in 64-bit IDE:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/36f74b295e2b2689c184fc612effe1686b477ef3

**Comment by XusinboyBekchanov** [comment]
I think this topic can be closed.
