### ISSUE TITLE
German Language missing

### ISSUE THREAD

**Issue by rexxitall** [XusinboyBekchanov/VisualFBEditor#26]
There is no german Language file....
[Languages.zip](https://github.com/XusinboyBekchanov/VisualFBEditor/files/4767624/Languages.zip)
Until now :)

**Comment by rexxitall** [comment]
I do not know how to embed it and for sure it might not yet be perfect. Things might be too long or just do not hit the context perfectly. But as we say here - Better then nothing ;)

**Comment by XusinboyBekchanov** [comment]
Added GERMAN / Deutsch language:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/5f48cc27dfa8595dc5d62e37305d2fb05b819e8f

Thank you for translating.

**Comment by rexxitall** [comment]
No Problem :) If someones helps me i help him :)
