### ISSUE TITLE
always freeze after openning a file

### ISSUE THREAD

**Issue by retsyo** [XusinboyBekchanov/VisualFBEditor#267]
I have compiled latest VisualFBEditor64.exe and VisualFBEditor32.exe. 

Everytime, when I try to load a `bas` file, no matter VisualFBEditor64.exe or VisualFBEditor32.exe freezes quickly, or in other word, refuses to work.

I have re-start my windows 10 64 bits, the problem is still existed

**Comment by XusinboyBekchanov** [comment]
Your code should be like this:
```
Constructor Form1Type
		' Form1
		With This
			.Name = "Form1"
			.Text = "Form1"
			.Designer = @This
			.OnCreate = @Form_Create_
			.SetBounds 0, -2, 363, 390
		End With
		' Grid1
		With Grid1
			.Name = "Grid1"
			.Text = "Grid1"
			.TabIndex = 1
			.SetBounds 15, 20, 307, 82
			.Parent = @This
		End With
		' Chart2
		With Chart1
			.Name = "Chart1"
			.Text = "Chart1"
			.ChartStyle = ChartStyles.CS_GroupedColumn
			.Border = False
			.FillOpacity = 50
			.LabelsFormats = "{V}"
			.SetBounds 17, 129, 301, 111
			.Parent = @This
		End With
		' CommandButton2
		With CommandButton1
			.Name = "CommandButton1"
			.Text = "CommandButton1"
			.TabIndex = 1
			.Caption = "CommandButton1"
			.SetBounds 20, 271, 296, 51
			.Parent = @This
		End With
	End Constructor
```

**Comment by XusinboyBekchanov** [comment]
Fixed: Control Parent property:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/51feb803f0b1635cb9032abe644e9075362a2080

**Comment by retsyo** [comment]
no

I still met this situation: the 32bits VFBE can open a `bas` file without problem, but the 64bits VFBE gets freezed while try to open the same `bas` file. however, I can't reproduce this every time. And no Chinese IME is used in both cases.

**Comment by XusinboyBekchanov** [comment]
The Chart issue has been fixed. If there are some more comments, you can reopen the topic.
