### ISSUE TITLE
Can't run the application if set the Compilation Arguments with "-x <filename>"

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/VisualFBEditor#273]
Compilation Arguments see as attached

![Untitled](https://user-images.githubusercontent.com/35757455/163327805-59daa573-910d-40cf-9d73-3f1cec06ce52.png)

Can't run the application see as attached

![Untitled1](https://user-images.githubusercontent.com/35757455/163328243-709c1d0f-1670-4699-8e6e-fb0de70b254a.png)

**Comment by XusinboyBekchanov** [comment]
When compiling executable files were created with these names?

Because the VisualFBEditor and MyFbFramework projects also use these settings. But normally it only launches EXE files.

**Comment by chunmingwang** [comment]
I used to distinguish between different paths in order to place the supported DLL files

**Comment by XusinboyBekchanov** [comment]
Try run this exes from Explorer

**Comment by chunmingwang** [comment]
by Explorer is normal

**Comment by chunmingwang** [comment]
the VisualFBEditor revision back to 2022/04/12 also normal

**Comment by chunmingwang** [comment]
Is it the problem caused by this update?
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/4b79d5bb12425763b23a896bb6e7d1b3703b3960

**Comment by chunmingwang** [comment]
I used the old src/TabWindow.bas to compiling VisualFBEditor, then work normal.

![Untitled](https://user-images.githubusercontent.com/35757455/163339771-d7b1ecd2-6f2a-45c6-a579-411f78302909.png)

**Comment by XusinboyBekchanov** [comment]
Fixed: Run compiled exe:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/6446780bbef8c0268e14712c4d8a485e7d59fcd5

**Comment by chunmingwang** [comment]
Today, I compiled it with the latest code and found the same problem again.
The following projects can be used for test.

`\Examples\Bass\bass.vfs`

**Comment by XusinboyBekchanov** [comment]
Fixed: Run compiled program:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/f15e87205746cbcc6ae7f0276b06d215ac7ca8bb

Thanks.

**Comment by chunmingwang** [comment]
Thanks.
