### ISSUE TITLE
Compiled Application do not run. Error code: 740 - 

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/VisualFBEditor#274]
if enabled the Run as administrator, then appear “Application do not run. Error code: 740 - “

![Untitled](https://user-images.githubusercontent.com/35757455/163501920-f6875a1b-ce26-4848-bb85-08be6df1f361.png)

![Untitled1](https://user-images.githubusercontent.com/35757455/163502051-b7d871e6-d9b6-49ed-bd34-f75201b86d41.png)

**Comment by chunmingwang** [comment]
by Explorer is normal

**Comment by XusinboyBekchanov** [comment]
If you run the IDE with administrator rights?

**Comment by chunmingwang** [comment]
IDE do not with administrator rights.

**Comment by chunmingwang** [comment]
I try IDE run as administrator, it is normal. thank.
