### ISSUE TITLE
Doesnt compiles and has problem with windows path names

### ISSUE THREAD

**Issue by rexxitall** [XusinboyBekchanov/VisualFBEditor#281]
Due to wrong directory separators its not possible to compile under windows. mff dll isnt loaded.
![patherror](https://user-images.githubusercontent.com/22050310/163830581-6c8dd38c-435c-4f54-9c32-cb06d4cb471f.png)

![image](https://user-images.githubusercontent.com/22050310/163830660-d787d203-c80b-4f1f-ac1f-66d88b468fd6.png)

Seems you was too long doing unix things ;)

**Comment by rexxitall** [comment]
i checked the ini files as well. Found also some "/" Separators. Best would be to automatically replace al directory separators according to the os type. So it doesnt make any different if they are  for unix or windows.

**Comment by XusinboyBekchanov** [comment]
You must specify the latest MyFbFramework here:
![image](https://user-images.githubusercontent.com/32607344/163831724-3481e14c-0d73-423c-891d-0a9c5462749a.png)

**Comment by XusinboyBekchanov** [comment]
> Due to wrong directory separators its not possible to compile under windows. mff dll isnt loaded.
> ![patherror](https://user-images.githubusercontent.com/22050310/163830581-6c8dd38c-435c-4f54-9c32-cb06d4cb471f.png)

If I delete or rename mff dll, I get an error like this:
![image](https://user-images.githubusercontent.com/32607344/163833002-c3f7339a-f587-4d00-a4ef-418d82b02662.png)

**Comment by XusinboyBekchanov** [comment]
This is my settings:
```
[MainWindow]
MainWidth=1152
MainHeight=1056
LeftClosed=false
LeftWidth=266
RightClosed=true
RightWidth=306
BottomClosed=false
BottomHeight=184
ProjectFolders=true
ToolLabels=true
UseDebugger=false
CompileGUI=true
RecentFiles=D:\GitHub\VisualFBEditor\VisualFBEditor.vfs
RecentFile=D:\GitHub\VisualFBEditor\Examples\Chart\Chart Example.bas
RecentProject=F:\Install\Install2\VisualFBEditor\Projects\Project1.vfp
RecentFolder=D:\GitHub\VisualFBEditor\Examples\AndroidProject
RecentSession=D:\GitHub\VisualFBEditor\VisualFBEditor.vfs
Subsystem=2
ShowMainToolBar=true
ShowStandardToolBar=true
ShowEditToolBar=true
ShowProjectToolBar=true
ShowBuildToolBar=true
ShowRunToolBar=true
ShowTipoftheDay=false
ShowTipoftheDayIndex=0
Maximized=true
Width=1279
Height=732
[Compilers]
DefaultCompiler32=FreeBASIC-1.09.0-winlibs-gcc-9.3.0 x32
DefaultCompiler64=FreeBASIC-1.09.0-winlibs-gcc-9.3.0 x64
Version_0=FreeBASIC-1.09.0-winlibs-gcc-9.3.0 x32
Path_0=D:\FreeBasic\FreeBASIC-1.09.0-winlibs-gcc-9.3.0\fbc32.exe
Version_1=FreeBASIC-1.09.0-winlibs-gcc-9.3.0 x64
Path_1=D:\FreeBasic\FreeBASIC-1.09.0-winlibs-gcc-9.3.0\fbc64.exe
Command_0=
Command_1=
Version_2=FreeBASIC-1.09.0-winlibs-gcc-9.3.0 x32 1
Path_2=F:\Install\Install2\FreeBASIC-1.09.0-winlibs-gcc-9.3.0\fbc32.exe
Command_2=
Version_3=FreeBASIC-1.09.0-winlibs-gcc-9.3.0 x64 1
Path_3=F:\Install\Install2\FreeBASIC-1.09.0-winlibs-gcc-9.3.0\fbc64.exe
Command_3=
[MakeTools]
DefaultMakeTool=make
Version_0=make
Path_0=make
Command_0=
[Debuggers]
DefaultDebugger=
Version_0=fbdbg 32
Path_0=D:\FreeBasic\FBdebugger296\fbdbg 32\FBdebugger.exe
Version_1=fbdbg 64
Path_1=D:\FreeBasic\FBdebugger296\fbdbg 64\fbdebugger.exe
Version_2=gdb
Path_2=D:\FreeBasic\FreeBASIC-1.07.1-win32\bin\win32\gdb.exe
Version_3=gdb64
Path_3=D:\FreeBasic\FreeBASIC-1.07.1-win64\bin\win64\gdb.exe
DefaultDebugger32=
DefaultDebugger64=Integrated GDB Debugger
Version_4=gdb 1
Path_4=F:\Install\Install2\FreeBASIC-1.07.1-win32\bin\win32\gdb.exe
Command_0=
Command_1=
Command_2=
Command_3=
Command_4=
Version_5=VSCode-win32-x64-1.44.2
Path_5=F:\Install\Install2\VSCode-win32-x64-1.44.2\Code.exe
Command_5={D} {S} {|F}
GDBDebugger32=gdb
GDBDebugger64=gdb64
Version_6=gdb64 1
Path_6=F:\Install\Install2\gdb 64 new\gdb.exe
Command_6=
[Terminals]
DefaultTerminal=Standard Windows Console
Version_0=Standard Windows Console
Path_0=
Version_1=cmd
Path_1=cmd.exe
Version_2=Windows PowerShell
Path_2=PowerShell
Command_0=
Command_1=/K "cd /D "{D}" & {F}"
Command_2=-NoExit
[Helps]
DefaultHelp=FreeBasic справка на русском
Version_0=FB-manual-1.09.0
Path_0=.\Help\FB-manual-1.09.0.chm
Version_1=FreeBasic справка на русском
Path_1=.\Help\FreeBasic справка на русском.chm
Version_2=win32_fb
Path_2=.\Help\win32_fb.chm
[IncludePaths]
[LibraryPaths]
[Options]
IncludeMFFPath=true
MFFPath=./MyFbFramework
ProjectsPath=./Projects
Language=english
TabWidth=4
HistoryLimit=20
UseMakeOnStartWithCompile=false
LimitDebug=false
DisplayWarningsInDebug=false
AutoIncrement=true
AutoIndentation=true
AutoComplete=true
AutoCreateRC=true
AutoCreateBakFiles=true
AutoReloadLastOpenFiles=true
AutoSaveBeforeCompiling=2
ShowSpaces=true
HighlightBrackets=true
HighlightCurrentLine=true
HighlightCurrentWord=true
TabAsSpaces=true
GridSize=10
ShowAlignmentGrid=false
SnapToGrid=false
ChangeKeywordsCase=true
ChoosedKeywordsCase=0
CurrentTheme=Dark (Visual Studio)
EditorFontName=Courier New
EditorFontSize=10
InterfaceFontName=Tahoma
InterfaceFontSize=8
DisplayMenuIcons=true
ShowMainToolbar=true
CreateNonStaticEventHandlers=true
DefaultProjectFile=Projects/GUI Application.vfp
WhenVisualFBEditorStarts=1
ShowKeywordsTooltip=true
AddSpacesToOperators=true
LastOpenedFileType=3
IntellisenseLimit=100
CreateFormTypesWithoutTypeWord=false
OpenCommandPromptInMainFileFolder=true
CommandPromptFolder=./Projects
TurnOnEnvironmentVariables=true
EnvironmentVariables=
DarkMode=true
PlaceStaticEventHandlersAfterTheConstructor=true
CreateStaticEventHandlersWithAnUnderscoreAtTheBeginning=false
AddRelativePathsToRecent=true
ShowTooltipsAtTheTop=true
[MRUProjects]
MRUProject_00=MyFbFramework\MyFbFramework.vfp
MRUProject_01=VisualFBEditor.vfp
MRUProject_02=Projects\Project1.vfp
[MRUSessions]
MRUSession_00=VisualFBEditor.vfs
[MRUFolders]
MRUFolder_00=Examples\AndroidProject
[MRUFiles]
MRUFile_00=Projects\Untitled.bas
MRUFile_01=Examples\Chart\Chart Example.bas
MRUFile_02=Projects\HuaRoad\HRD_freeBasic.frm
MRUFile_03=Projects\add.bas
MRUFile_04=Projects\HRD_freeBasic.frm
MRUFile_05=Examples\WebBrowser\WebBrowser1.bas
MRUFile_06=Examples\WebBrowser\WebBrowser Example.bas
MRUFile_07=Projects\Form2\Form2.frm
[Parameters]
Compiler32Arguments=-b {S} -exx -v
Compiler64Arguments=-b {S} -exx -v
Make1Arguments=
Make2Arguments=clean
RunArguments=
Debug32Arguments=
Debug64Arguments=
[Find]
Find_0="Form1.rc
Find_1=This.TextHeight
Find_2=TextHeight
Find_3=UserControl
Find_4=UserControl.ScaleHeight
Find_5=UserControl.ScaleWidth
Find_6=ScaleWidth
Find_7=IntegerList
Find_8=dStyle
Find_9=SizeOf(WNDCLASSEX
[Replace]
Replace_0=Canvas.TextWidth
Replace_1=Canvas.TextHeight
Replace_2=This
Replace_3=This.ClientHeight
Replace_4=This.ClientWidth
Replace_5=DoubleList
Replace_6=ChartArea
[OtherEditors]
Version_0=ResEdit-x64
Extensions_0=.res, .exe
Path_0=D:\Install\ResEdit-x64\ResEdit.exe
Command_0=/K "cd /D " {D} "" & 

```

**Comment by XusinboyBekchanov** [comment]
Try compiling with this (you created this bat file):
https://github.com/XusinboyBekchanov/VisualFBEditor/wiki/Compiling#sample-bat-file

**Comment by rexxitall** [comment]
Compiled source from github on a machine which has never seen the thing and got this errors. I assume that you has done a lot of unix stuff and "adjusted" some file things to get it working there. I have got this type of errors often when i switched the platform. For sure everybody is too lazy to test it on all platforms. (Me usually too). So how its possible to compile the thing ? Install Linux is not a option :) Same with your fbc fork. No executables provided. Might be a idea to provide on a release all executables needed for win and linux. So everyone can just unpack and start working. :) The binarys are not that big. BTW: HAPPY EASTERN !

**Comment by rexxitall** [comment]
The bug is not located in the ini. It happens if you complete the filename i guess. I replaced all / to \ in the ini file. Doesnt help at all :/

**Comment by XusinboyBekchanov** [comment]
>Compiled source from github on a machine which has never seen the thing and got this errors. I assume that you has done a lot of unix stuff and "adjusted" some file things to get it working there. I have got this type of errors often when i switched the platform. For sure everybody is too lazy to test it on all platforms. (Me usually too).

This is not a platform issue. You want to compile the current VisualFBEditor with the old library. This is evident from the errors.

>So how its possible to compile the thing ? Install Linux is not a option :) Same with your fbc fork.

I have added a bat file. If you run this bat file, it downloads from github, creates a VisualFBEditor folder, place the MyFbFramework folder inside the VisualFBEditor folder and compiles them. You can place this file in an empty folder and see everything.

Create DownloadAndCompile.bat:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/1202d464d132b573bc7dccabc6f77cc950b0caba

>No executables provided. Might be a idea to provide on a release all executables needed for win and linux. So everyone can just unpack and start working. :) The binarys are not that big.

I do this on releases. Both Windows and Linux binaries are available. You can unpack the release zip folder and run.

**Comment by rexxitall** [comment]
Hi :) The batch wit questions is a great idea :) But 7z is not a windows internal command. Windows can only handle zip files. So in the case you need 7zip you should download it first :)

**Comment by XusinboyBekchanov** [comment]
Hi, added:
Update DownloadAndCompileWithQuestions.bat:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/296082634beaa4a496782ddd122aae5ebb65d624

**Comment by XusinboyBekchanov** [comment]
Small change:
Update DownloadAndCompileWithQuestions.bat:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/30a4278c24174010d19cad483eea8332e1a7cec1

**Comment by rexxitall** [comment]
Much better :) Download and unzip is running in WIN 10 . But 
![image](https://user-images.githubusercontent.com/22050310/166142765-1fe6331f-ab73-47c6-923f-ede68b275a2a.png)
some setting or path goes wrong.  Told the batch to download everything. Works until it should compile. In WIN 7 it is not able to download. The curl i think is too old. Mabe add a hint that it works only in win 10 and newer.

**Comment by rexxitall** [comment]
The german error message in thee middle of the picture means Path not found. I use  "D:\FB" path  from where i execute the batch file. Might - but should not - confuse the compile run.

**Comment by rexxitall** [comment]
Tryed also the other batch with this resilt: 
![image](https://user-images.githubusercontent.com/22050310/166143269-161f70c1-f6c5-4283-9afa-a03e57ee7002.png)

**Comment by rexxitall** [comment]
Same meaning of the message - path not found

**Comment by XusinboyBekchanov** [comment]
Fixed: Compiling 64-bit with DownloadAndCompileWithQuestions.bat:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/3af06f20c05be910c25aaee6b24217502bb8b092

**Comment by XusinboyBekchanov** [comment]
You have selected both of 32/64/both. The 32bit IDE and library were already compiled, I made a mistake, didn't return the mff.bi location to the right place after compiling the 32bit IDE and library.
So far, I've only tested the 32-bit version.

**Comment by XusinboyBekchanov** [comment]
Small changes:
Update DownloadAndCompileWithQuestions.bat:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/4a69dcb3c4ded1e8eb7735bd12d6d73c67e93e26

**Comment by rexxitall** [comment]
I will check again. BTW: in  the last batch you create same names for the 32 and 64 bit dll and executable.  I think it was a copy and paste mistake. if i remember right the 64bit version wants to have a mff64.dll.

**Comment by XusinboyBekchanov** [comment]
Thanks. I fixed:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/eaddf6878c8ca0731f6dab4d8bccfef11519ca92

**Comment by rexxitall** [comment]
And some laziness stuff. You ask late if the user  wants to download freebasic editor and mff. I would ask all those things at start. then you can get some coffee until everything is ready ;) I mean you do not have to sit and wait until this question happens.

**Comment by XusinboyBekchanov** [comment]
I don't know, you said at the beginning that it doesn't compile. I wanted to prove otherwise with a new batch file, I always tested 32-bit. Because 64-bit compiles for a long time.

**Comment by rexxitall** [comment]
:D You are just not patient enough :) I test using BOTH. takes a few minutes yes :) I have no need for 32 bit.. I need 64 bit only. last batch i changed just the filenames for the 64bit version. So i get 32 and 64 bit files. Both starts and fails  after showing the logo. Anyhow i will cleanup again and give your last batch a try. If i am right there is something wrong while initializing the mff stuff. During last checks  i did in between it comes up if the mffxy.dll was missing. Anyhow i will give the whole thing again a fresh try :) Takes a bit, i use at the moment a slow atom driven netbook with two cores not my workstation. I am visit my GF so no CAD Workstation:D

**Comment by rexxitall** [comment]
Yes same result hangs while creating menus and toolbars. Replace / with \ in ini files  does not help, delete mff dll does not help
something is missing is  misconfigured.

**Comment by rexxitall** [comment]
Both versions hangs 64 and 32 bit.

**Comment by XusinboyBekchanov** [comment]
Are you entering the new VisualFBEditor\VisualFBEditor folder?

**Comment by rexxitall** [comment]
sure only place where i can find the executables
I all the times clean d:\FB commpletely. Then i download gihub zip and uunpack there. Then i start the batch file. so eerything is there where you  want to have it.

**Comment by rexxitall** [comment]
![image](https://user-images.githubusercontent.com/22050310/166148836-fc09da0c-943d-4643-8490-4b687c4c6276.png)
All it does is this

**Comment by rexxitall** [comment]
with a high cpu load. So looks like endless loop or something silly like this.
![image](https://user-images.githubusercontent.com/22050310/166149012-d1eb4d97-b0ee-490b-9331-24f593084c9d.png)

**Comment by XusinboyBekchanov** [comment]
I get in quickly. What is the speed of your computer?

**Comment by XusinboyBekchanov** [comment]
So I also downloaded like you, launched a batch file. Will not hang.
https://user-images.githubusercontent.com/32607344/166149647-455dd26e-9c9d-4924-a3b9-508824fba6b2.mp4

**Comment by rexxitall** [comment]
Nothing fast. 4gig ram  Intel Pentium N5000 
![image](https://user-images.githubusercontent.com/22050310/166149965-1faacb5d-48de-4907-b954-652e62b460e6.png)

**Comment by rexxitall** [comment]
BTW: The version of last year starts a few seconds. So i am in doubt that is just a speed issue. even if i wait minutes. Nothing happens.

**Comment by XusinboyBekchanov** [comment]
In my opinion, you changed the language, after that it happens, right?
I also changed now, it takes a very long time.

**Comment by rexxitall** [comment]
Most likely you has installed some kind of thing, long ago, long forgotten which is needed. You has it at  least i do not have it. Some kind of startup.log file could be help to track it down.

**Comment by rexxitall** [comment]
i changed nothing. i leave everything like it was in the download.

**Comment by rexxitall** [comment]
On the language thing, i saw that the help files got cryptic filennams. So if you has the settings made in letters on a codepage i can not have, it would fail same style. I will look in the ini files. wait

**Comment by rexxitall** [comment]
Language is english so no problem at all I know already that i have to add 600 lines german more in tthe language files. You was busy during last year :D  But all is set as downloaded. I do not know if it matters but in the ini is something mentioned like F:\Install\Install2\FreeBASIC-1.07.1-win32\bin\win32\gdb.exe I do not have a F:\ drive. Also some paths was set wit "/" instead "\" but that i changed last times without result.

**Comment by XusinboyBekchanov** [comment]
Fixed: Load Language Texts On Load IDE:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/e0ef6878205de0cfe2ad0ee4428619a2721f9ab3

After that, the problem should be resolved.

**Comment by rexxitall** [comment]
Works like a charm now :) Thanks ! Just move the last user question (download source and mff) to the other ones so they can be answered at one times. Then it would be very perfect :)

**Comment by rexxitall** [comment]
Stupidly now ive no excuse anymore not to rework the german language file :D

**Comment by XusinboyBekchanov** [comment]
>Just move the last user question (download source and mff) to the other ones so they can be answered at one times. Then it would be very perfect :)

How? I didn't understand. 
There is this question:
Download=Do you want to download VisualFBEditor and MyFbFramework (yes/no)? 

One question is answered only once.

**Comment by rexxitall** [comment]
Do all the questions first. Downloads and unpacking takes time. So you has to wait until a lot of things got downloaded until the mff source question comes up. And now you has to wait again. So first do all user input, then do all the work. Finally you could jump into the FBEDIt IDE and start the exe ;) If the user decides to download all things you could also mofify the compiler settings :) Would result in a fully working IDE out of the box :) BTW: really great work !!!. I love the modern dark design :)

**Comment by XusinboyBekchanov** [comment]
Then I delete the last question. I think it's redundant.

**Comment by XusinboyBekchanov** [comment]
Added: Download GDB question to DownloadAndCompileWithQuestion.bat and Added: Default Compiler and GDB path settings to VisualFBEditor folder
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/24ac1e8f36f77423531f706427a0703b54cdc5a4

**Comment by rexxitall** [comment]
:)

**Comment by XusinboyBekchanov** [comment]
The last one is:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/57191291bb5568781f98e0bc51949cf4f8468744
