### ISSUE TITLE
the crtl + move of the left code editor will give an error prompt on #include "file.bi"

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/VisualFBEditor#287]
When the code editor is splited to the left and right, the crtl + move of the left editor will give an error prompt in #include "file.bi"

![Untitled](https://user-images.githubusercontent.com/35757455/165650784-a2bfbd97-506e-4859-9775-f18cf31bb49b.png)

**Comment by XusinboyBekchanov** [comment]
What mistake?

**Comment by chunmingwang** [comment]
see the screen recod as attached,
ctrl+mouse move on the left side of code editor



--

Best regards,
Cm Wang




在 2022-04-28 08:19:40，"Xusinboy Bekchanov" ***@***.***> ：

What mistake?

**Comment by XusinboyBekchanov** [comment]
Attached file is not.

**Comment by chunmingwang** [comment]
Resend to bxusinboy@mail.ru

**Comment by chunmingwang** [comment]
https://user-images.githubusercontent.com/35757455/165661553-865929d7-80a0-48d8-9da3-c9feca4d01a4.mp4

**Comment by XusinboyBekchanov** [comment]
Fixed: Ctrl + MouseMove on Edit Control on Vertically Split Mode:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/36f49cd9a2c485d0e92e4673e731d16da64b25e1
