### ISSUE TITLE
Feature request: Hotkeys / keybord bindings make changeable

### ISSUE THREAD

**Issue by rexxitall** [XusinboyBekchanov/VisualFBEditor#29]
Nearly everyone has his own preferences for Keyboard shortcuts. There should be a definition file or something like that for it to make it customizeable :)

**Comment by XusinboyBekchanov** [comment]
This added:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/f8b8a67bb969c79184133e934468a6fd86fd38b3

**Comment by XusinboyBekchanov** [comment]
Changes in MyFbFramework (HotKey Control):
https://github.com/XusinboyBekchanov/MyFbFramework/commit/8eaac7f8963b6fa6b26831f8f625d8d72a90f0c5
