### ISSUE TITLE
download sh missing things

### ISSUE THREAD

**Issue by rexxitall** [XusinboyBekchanov/VisualFBEditor#290]
Hi, you already apt installs a lib. You should add all those external tools  like wget, git and so on as well. If its there its good if not it will be there when needed. I never installs git by default on my linux machines. I have some :D . the time loss of APT for checking the database is minimal. But you can be sure that the install will work in any case. :)

**Comment by XusinboyBekchanov** [comment]
Added: Install git and wget to DownloadAndCompile.sh
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/0f2cb3dc66f1a3972768357649cdd83af360374f
