### ISSUE TITLE
File could not be saved.

### ISSUE THREAD

**Issue by rexxitall** [XusinboyBekchanov/VisualFBEditor#291]
After working a day with heavy try and error and lots of pressing STRG+S to save the main file i got this. 
I wrote some kind of shell filter which deals also with files a lot.
Looks for me like that a internal file descriptor is not big enough. 
FBIDE was not closed during this session. Quite ok. (The other bugs i will report later ;) ) 

So finally i have to copy and paste the code to notepad++ to get it saved :D 
I got this here:
![image](https://user-images.githubusercontent.com/22050310/167037916-1d0eedfa-e363-46ed-861a-5652d18fbd05.png)

**Comment by XusinboyBekchanov** [comment]
Fixed: File number leak:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/9aaf01e332fb4cae142ff57c8dbf4e2334c40cf4
