### ISSUE TITLE
Cannot display and jump to the code editor window

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/VisualFBEditor#292]
When the window editor is in full window mode, double-click the event table of the control, cannot display and jump to the code window.

![Untitled](https://user-images.githubusercontent.com/35757455/167092407-64d2b071-6dad-4795-b6cd-3f3b53ba1256.png)

**Comment by XusinboyBekchanov** [comment]
Fixed: Double clicking on an event in the Event window shows the Code editor:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/d7af13f52d204b397a56ff3233423eff14890120

**Comment by chunmingwang** [comment]
test and fixed.
