### ISSUE TITLE
German Language file needs some more lines to translated ...

### ISSUE THREAD

**Issue by rexxitall** [XusinboyBekchanov/VisualFBEditor#30]
I am working on that...

**Comment by XusinboyBekchanov** [comment]
Ok

**Comment by rexxitall** [comment]
So this takes a bit longer :)
[languages.zip](https://github.com/XusinboyBekchanov/VisualFBEditor/files/4775295/languages.zip)
[LNGSQLITE.zip](https://github.com/XusinboyBekchanov/VisualFBEditor/files/4775297/LNGSQLITE.zip)

Seems the .lng files do not contain ALL keys. So i fixed that first . Each language file has now same entrys and count of "keys". You has defined 430 keys - at least in the LG files - somehow somewhere ;) In fact i read them all and generate a key list first. see Keys.zip. Then i parsed all files and try to find the according key / translation couple.
[keys.zip](https://github.com/XusinboyBekchanov/VisualFBEditor/files/4775299/keys.zip)

I put the result also in a sqlite DB. 
To find all NOT translated russian language strings you could use 

select * from "languages" where lng="russian" and translated ="0"

Remark: (translated ="1" means translated)

A updated spredscheet you will find as well in csv.zip. I use the tabulator chr(9) key as field seperator 
[CSV.zip](https://github.com/XusinboyBekchanov/VisualFBEditor/files/4775305/CSV.zip)

I still have the doubt and guess that there are still hard coded things inside the IDE. To detect them i created also the tester.lng file.
The different to the english language is that it contains all entrys with a leading "#"
If a IDE which load that file do not show on each entry the "#" character means that this is hardcoded still and can curently not get translated.
Best regards 
Thomas

**Comment by rexxitall** [comment]
BTW: even i am native german and not THAT english shakespeare Hero  i recognice that the english language needs also to get translated ;)
A perfect translation can only be done by a native born speaker. That must not be nessecaryly XusinboyBekchanov special englisch ;) Would be same if i would translate something to english. It would be understandable for sure but cool ? 

for the fun part i asked a friend from a different area of germany to translate it to his native dialect.
Might be very possible that other guys from the other 16 areas from germany get the funny idea and provide their area specific dialect. Here in lower saxony aka NIEDERSACHSEN we are that stupid that we just know the official german language without dialect :) The brain memory is too limited to also get additional space for a dialect ;) Anyhow Swabian is under construction

**Comment by XusinboyBekchanov** [comment]
This added:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/c5807d7a3b6043d9e6d3bcc33e2824f28255265a

**Comment by rexxitall** [comment]
[German (2).zip](https://github.com/XusinboyBekchanov/VisualFBEditor/files/4778205/German.2.zip)
![image](https://user-images.githubusercontent.com/22050310/84621846-e027d880-aedb-11ea-8050-8210d33cf9a0.png)
All german special characters are there so it looks perfect to me.

**Comment by rexxitall** [comment]
And a very big thank you for all the nice fixes aned enhancements you has made last days :)
