### ISSUE TITLE
The alpha transparent pixels in the PNG image will turn black

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/VisualFBEditor#304]
I tried to use the icon of vs2017 in toolbar and menu for VisualFBEditor, and found the problem that alpha transparent pixels in PNG image turned black, please check out the screenshot below.

![Untitled0](https://user-images.githubusercontent.com/35757455/169748563-934152d0-2c4a-4f3f-985a-887092a8a78a.png)
![Untitled1](https://user-images.githubusercontent.com/35757455/169748569-54729631-dd69-4e6a-9c91-567fa01afe58.png)
![Untitled2](https://user-images.githubusercontent.com/35757455/169748576-55cf7638-a6bc-483c-9c81-970e9347a383.png)
![New](https://user-images.githubusercontent.com/35757455/169748793-4a2e22ed-7ab8-402d-952d-0f14ff3312fc.png)

**Comment by XusinboyBekchanov** [comment]
Send one such PNG, I will try.

**Comment by chunmingwang** [comment]
Yes, I have attached this PNG file at the end

**Comment by chunmingwang** [comment]
https://user-images.githubusercontent.com/35757455/169748793-4a2e22ed-7ab8-402d-952d-0f14ff3312fc.png

**Comment by XusinboyBekchanov** [comment]
Try this please:

Update ImageList.bas:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/491defdb4d97e477324a42378b865608b040fcc8

**Comment by hustbeef** [comment]
Try the Visual Studio 2022  Image Library. It is free and could be download freely and including svg files。
[https://docs.microsoft.com/en-us/visualstudio/extensibility/image-service-and-catalog?view=vs-2022](url)

**Comment by chunmingwang** [comment]
I select the icons for vfbe from the vs2017, as below zip files.
This makes the program look more modern.
If you feel good, you can make it for one of the skin options.

[res_vfbe.zip](https://github.com/XusinboyBekchanov/VisualFBEditor/files/8794603/res_vfbe.zip)
[res_mff.zip](https://github.com/XusinboyBekchanov/VisualFBEditor/files/8794605/res_mff.zip)

dark mode
![Untitled](https://user-images.githubusercontent.com/35757455/170898693-43b4f093-f50c-409a-9cf3-483ee9b6b3b6.png)

light mode
![Untitled0](https://user-images.githubusercontent.com/35757455/170898687-3742145f-14ab-43ef-a3fb-ab002921f637.png)

**Comment by XusinboyBekchanov** [comment]
Ok, thanks.

**Comment by XusinboyBekchanov** [comment]
In my opinion, under license, they can only be used in programs created with Visual Studio:

[Visual Studio 2017 Image Library EULA.zip](https://github.com/XusinboyBekchanov/VisualFBEditor/files/8811627/Visual.Studio.2017.Image.Library.EULA.zip)
