### ISSUE TITLE
FBC needs more themes

### ISSUE THREAD

**Issue by rexxitall** [XusinboyBekchanov/VisualFBEditor#31]
I am working on this ...

**Comment by XusinboyBekchanov** [comment]
Ok

**Comment by rexxitall** [comment]
[Themes.zip](https://github.com/XusinboyBekchanov/VisualFBEditor/files/4780285/Themes.zip)
They mostly will work and be usable. For a better "artwork" i would need to have more possibility / freedom in the highlighting engine and her setup.  For example the possibility to highlight singe chars sets, keyword types (control, type, buildin, function, variables, user function ....) And so n ;)

**Comment by XusinboyBekchanov** [comment]
This added, thank you very much:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/cec3a83182af1d0190a4f626b7655c3025456f82

**Comment by XusinboyBekchanov** [comment]
Regarding the allocation of single character sets, types of keywords, we will still do this.

**Comment by rexxitall** [comment]
Its meanwhile a automated process, if i get more "freedom" (color settings) i can adopt the sets quite fast :)
