### ISSUE TITLE
Language files not loaded...

### ISSUE THREAD

**Issue by rexxitall** [XusinboyBekchanov/VisualFBEditor#32]
I guess you hard compiles the language files inside the IDE. To be honest - not a great idea !
Might be done for speed reasons but that is NOT nessecary !
you has now a valid Key file
which can be turned easy to a enum :)
Then you just has to use the enum to get the desired language string.
On this path of coding or pattern you can show all languages which are availeable immediatly
*i put in my langugage files at the first line the language name*
So read all language files and take the first line into the dropdown list.
So if the first line is different use the name of the file without extension and path.
Make the first letter uppercase and this dropdown would be fine :)
If someone wants JUSt to provide a language file he might not be uilling to get the WHOLE toolchain working.
Its also not needed. :)
Just parse the ascci file.
To get speed you will might have found in the file i send X.zip for the format bug two interesting working things.
Freebasic Dictionarys or SQLITE both would help you on the speed issue :)
My free BSD fiend wich try to make swabian was not THAT amused that nothing wokrd out :) His comments was not the way i would like to cite them :D 
Anyhow - such silly things can not be hard coded and should also not.
Maybee the klingon space force would try the same one day....You wont want to  be at home THAT day  *grin*  ;)

**Comment by XusinboyBekchanov** [comment]
No, the language files do not hard compiles inside the IDE. Only IDE will try to open by utf8, if it can’t open it skips. I am currently preparing a fix for this.

**Comment by XusinboyBekchanov** [comment]
This fixed:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/c5807d7a3b6043d9e6d3bcc33e2824f28255265a

**Comment by rexxitall** [comment]
Seems you found some GUI strings/sentences more now in your program :D We are now by over 530 Lines :D

**Comment by XusinboyBekchanov** [comment]
Yes it is. Many from Debug.bas

**Comment by rexxitall** [comment]
[German.zip](https://github.com/XusinboyBekchanov/VisualFBEditor/files/4776842/German.zip)
Well, then you need a bigger german language file i guess :)

**Comment by XusinboyBekchanov** [comment]
In my opinion, the file is not saved correctly. Must save with UTF8 with specification
```
german
&About=Ьber
&Add Files To Project=Dateien zu Prjekt hinzufьgen
&Add Watch=Ьberwachung hinzufьgen
&Add-Ins=Erweiterungen
&Block Comment=Block Kommentar
&Break=Pause
&Build=Erstellen
&Cancel=Abbruch
&Clear All Breakpoints=Alle Ьberwachungspunkte lцschen
&Close=SchlieЯen

```

**Comment by rexxitall** [comment]
Hm, seems notepad does then something strange with it or openoffice calc which i have used to edit the file. Both programs shows the file correctly. Stupidly or thanks god are all european languages can be displayed with 8bit characters. I will look on that. Same fun with VBA and System calls. VBA has 8bit chars and system calls await wide chars UTF whatever. :/

**Comment by rexxitall** [comment]
![image](https://user-images.githubusercontent.com/22050310/84601912-f3a75500-ae83-11ea-82a1-65980265df5d.png)

**Comment by rexxitall** [comment]
Looks like it should look

**Comment by XusinboyBekchanov** [comment]
This old version is correct, but not completely:

[german1.zip](https://github.com/XusinboyBekchanov/VisualFBEditor/files/4777079/german1.zip)

**Comment by XusinboyBekchanov** [comment]
In my opinion, you need to use Simple Notepad

**Comment by rexxitall** [comment]
The way i do the language file is to use openoffice by tewaking it in that way the i load the language file as csv File.(Told Open Office thet "=" is used as separator) Now i can edit the missing things very comfortable and also have a german spell checker, thesaurus and so on by hand. Its then saved as csv and i replaced the \t by equal signs. I can also sort the lines in Open office by rows and columns. So i do not have to look long which are empty. Just sort them on translated column and you see all empty lines. I personally think that is not the most  stupid way to do this kind of work. But for sure as long as it looks well for me i came not on the UTF8 pitfall idea ;)

**Comment by XusinboyBekchanov** [comment]
Send as the first time, I will do the rest myself.

**Comment by rexxitall** [comment]
![image](https://user-images.githubusercontent.com/22050310/84634358-f9d41a80-aef1-11ea-92dc-c6915f18da05.png)
You got them. I recogniced that the colour settings are not affected.

**Comment by XusinboyBekchanov** [comment]
Fixed:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/d8772315fc229ac3c8e91ae8651e507456880c89

**Comment by rexxitall** [comment]
[German (3).zip](https://github.com/XusinboyBekchanov/VisualFBEditor/files/4785489/German.3.zip)
Fixed some Typos and sentences. color settings and nwe lines will be fixed on next build.

**Comment by XusinboyBekchanov** [comment]
I can not read it. Will it open correctly for you? I have unicode letters shown differently.

**Comment by XusinboyBekchanov** [comment]
Or send here without a file.

**Comment by rexxitall** [comment]
[German.zip](https://github.com/XusinboyBekchanov/VisualFBEditor/files/4787442/German.zip)
I use it the whole day without problem. I just grab it from the working System. Do not do anything with it. On next time i build the IDE i will look for new "empty lines" and translate them as well :) Just for your information. I have  "normal work days" again. I send my weekend day and nght on this and the Theme files. By order of by boss i could also spend the monday on it. He likes also open source and told byself that there should be also some kind of give back. So i was free to finalize the theme and the language file during work time. If you wanna know what i or we do normally -  http://bauing-schmidt.de/ we do infrastructure project. Railway bridges, hotels, roads, channel, tunnel - iin simple words whaever someones wanna build. From the tiny house til a bridge. We do all the drawings and calculations needed. We are just to a tiny part also a software company. In fact we have some developer under contract. I usually do designs or constructions which are more difficult. But sometimes i programm and extend Autocad or calculations programs for faster progress. I do this since over 12 years now. I start writing programs as i was 19 years old. Now i am nearly 55 :)

**Comment by XusinboyBekchanov** [comment]
Here:
![image](https://user-images.githubusercontent.com/32607344/84796237-d7392300-b011-11ea-8c7e-9eccba6f3e19.png)

**Comment by XusinboyBekchanov** [comment]
Copy the text from the file and paste here please.

**Comment by XusinboyBekchanov** [comment]
Or send in Microsoft Word format

**Comment by rexxitall** [comment]
[german (2).zip](https://github.com/XusinboyBekchanov/VisualFBEditor/files/4815088/german.2.zip)
Update to the german Language file.
There are some areas where the space for the text is not sufficiant. (too small to put the text in).
German is a Language which needs often 30% more characters then you would need for the same text in english. (German is very exact and english is a bit more "sloppy") Just as a "rule of thumb". Might be a idea to create a hidden commandline switch which will add "#" characters on each text read from a language file. A text then will be correct implemented if you can read both signs. First is a indicator that the text comes from a language file, and the last shows that the Text Box is big enough :) .

**Comment by XusinboyBekchanov** [comment]
This time it opened correctly for me. I updated it. As for the size of the text, we will still do it.
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/44c64936d4f77f0ab3b0fad7dba232827ae9f23a
