### ISSUE TITLE
StringList.SaveToFile doesn't seem to work

### ISSUE THREAD

**Issue by TRSlimShaney** [XusinboyBekchanov/VisualFBEditor#324]
Var list = StringList()

' successfully loads list of strings from list.txt
list.LoadFromFile("list.txt")

' try to save back to another text file doesn't work
' results in a blank list2.txt being created
list.SaveToFile("list2.txt")

**Comment by XusinboyBekchanov** [comment]
This has been fixed in the new version. You can download the new version from github.

**Comment by TRSlimShaney** [comment]
@XusinboyBekchanov Awesome, thank you.
