### ISSUE TITLE
 Click vertical scrollbar in the code editor

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/VisualFBEditor#329]
Click vertical scrollbar in the code editor. The code is not page up or page down.

**Comment by XusinboyBekchanov** [comment]
Fixed: Page Up and Page Down on Click Vertical Scrollbar in the Code Editor:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/f5bea19050f3c7a0d61e375195605162cffde245

**Comment by chunmingwang** [comment]
Continue feedback:
1. Click vertical scrollbar is 10 lines up and down, not the page up and down.
2. Both Thumb dragging & Arrow clicking can not move to the bottom of code.

**Comment by XusinboyBekchanov** [comment]
Show in the video please, I tried, it turns out.

**Comment by chunmingwang** [comment]
https://user-images.githubusercontent.com/35757455/177472640-d7827e3e-2ac0-427d-bcd7-45c8e7318342.mp4

https://user-images.githubusercontent.com/35757455/177472663-080190c9-6452-48d7-b62b-15c6737d7d47.mp4

**Comment by XusinboyBekchanov** [comment]
Here is my video, everything works:
https://user-images.githubusercontent.com/32607344/177474949-8ffe8674-22f2-41d6-9d3c-60766d6644e4.mp4

**Comment by chunmingwang** [comment]
Can not move to the bottom of code:
EditControl.bas also works for me.
please try more others like VisualFBEditor.bas, TabWindow.bas...

**Comment by XusinboyBekchanov** [comment]
Fixed: Scrolling to the end line of the Edit Control:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/395f0aaf79aa5c195fee593b6f2de0e566bc2317

Thanks for report.

**Comment by chunmingwang** [comment]
Thanks
