### ISSUE TITLE
Minimal font size too small

### ISSUE THREAD

**Issue by rexxitall** [XusinboyBekchanov/VisualFBEditor#33]
Ac.. german law and my eyes the minimal size should be 12 points on a 1920x1054 pixel disply at least.
This has to be recalculated for each display screen size - for sure.
On a 4K display you would sit in Front of your TV use a magnifier glass.
I am a nasty, ugly, old bag of 54 years old. as  I was 20 i could read whatever little without glasses. And for sure i look much better *laugh* Anyhow :)
Now i need +3 Dioptree recipe :) (Glasses)
People get older - you will too.
Please support them :)

**Comment by XusinboyBekchanov** [comment]
In options there is General -> Themes -> Interface font. There you can change.

**Comment by rexxitall** [comment]
should be set to a bigger value as default. You can not find the menu point if its too small ;)
