### ISSUE TITLE
Unpin Property/Even not auto hide in Form show code active

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/VisualFBEditor#330]
See the screen recording as attached
[20220708074113.zip](https://github.com/XusinboyBekchanov/VisualFBEditor/files/9067914/20220708074113.zip)

**Comment by XusinboyBekchanov** [comment]
Fixed: Auto Hide/Show Property Window:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/091f93a3f4fbcd7c18c87881bf8e2add3be134d8

**Comment by chunmingwang** [comment]
Great, thanks for a quick and perfect solution
