### ISSUE TITLE
Cannot edit a file with a line length of more than 1024 bytes

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/VisualFBEditor#333]
Cannot edit a file with a line length of more than 1024 bytes

for Examples project: VisualFBEditor\Examples\Bass\bassaudio.vfp
in file VisualFBEditor\Examples\Bass\frmBass.frm line 190:

`Dim As Label Label1, Label2, Label3, Label4, Label5, Label6, Label8, lblFXMSG0900, lblFXMSG0901, lblFXMSG0902, lblFXMSG0903, lblFXShw0900, lblFXShw0901, lblFXShw0902, lblFXShw0903, lblFXMSG0100, lblFXMSG0101, lblFXMSG0102, lblFXMSG0103, lblFXMSG0104, lblFXMSG0105, lblFXMSG0200, lblFXMSG0201, lblFXMSG0202, lblFXMSG0203, lblFXMSG0204, lblFXMSG0205, lblFXMSG0300, lblFXMSG0301, lblFXMSG0302, lblFXMSG0303, lblFXMSG0304, lblFXMSG0400, lblFXMSG0401, lblFXMSG0402, lblFXMSG0403, lblFXMSG0404, lblFXMSG0500, lblFXMSG0501, lblFXMSG0502, lblFXMSG0503, lblFXMSG0504, lblFXMSG0505, lblFXMSG0506, lblFXMSG0600, lblFXMSG0601, lblFXMSG0700, lblFXMSG0701, lblFXMSG0702, lblFXMSG0703, lblFXMSG0704, lblFXMSG0705, lblFXMSG0706, lblFXMSG0707, lblFXMSG0708, lblFXMSG0709, lblFXMSG0710, lblFXMSG0711, lblFXMSG0800, lblFXMSG0801, lblFXMSG0802, lblFXMSG1000, lblFXMSG1001, lblFXMSG1002, lblFXMSG1003, lblFXShw0100, lblFXShw0101, lblFXShw0102, lblFXShw0103, lblFXShw0104, lblFXShw0105, lblFXShw0200, lblFXShw0201, lblFXShw0202, lblFXShw0203, lblFXShw0204, lblFXShw0205, lblFXShw0300, lblFXShw0301, lblFXShw0302, lblFXShw0303, lblFXShw0304, lblFXShw0400, lblFXShw0401, lblFXShw0402, lblFXShw0403, lblFXShw0404, lblFXShw0500, lblFXShw0501, lblFXShw0502, lblFXShw0503, lblFXShw0504, lblFXShw0505, lblFXShw0506, lblFXShw0600, lblFXShw0601, lblFXShw0700, lblFXShw0701, lblFXShw0702, lblFXShw0703, lblFXShw0704, lblFXShw0705, lblFXShw0706, lblFXShw0707, lblFXShw0708, lblFXShw0709, lblFXShw0710, lblFXShw0711, lblFXShw0800, lblFXShw0801, lblFXShw0802, lblFXShw1000, lblFXShw1001, lblFXShw1002, lblFXShw1003, lblFXMSG0106, lblFXShw0106, lblEQ00, lblEQ01, lblEQ02, lblEQ03, lblEQ04, lblEQ05, lblEQ06, lblEQ07, lblEQ08, lblEQ09, lblEQB00, lblEQB01, lblEQB02, lblEQB03, lblEQB04, lblEQB05, lblEQB06, lblEQB07, lblEQB08, lblEQB09`

at the code editor like following, missing after lblFXShw0203

![Untitled](https://user-images.githubusercontent.com/35757455/180346981-f8410930-cb5c-47a0-b66c-40b6dca43043.png)

**Comment by XusinboyBekchanov** [comment]
Fixed: Loading codes longer than 1024 symbols:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/338cedcf47a3dd57aee36f032d2c7b4dbe268015

Fixed regress, thanks.

**Comment by chunmingwang** [comment]
Thanks!

**Comment by hustbeef** [comment]
It is not recommend worked with too long code in one line.

**Comment by hustbeef** [comment]
And this maybe cause another issure for UTF8 file format. So it si better change 1024 to 2048 or more.

**Comment by hustbeef** [comment]
It is OK for UTF8 ad plaintext file after testing with unicode.

**Comment by chunmingwang** [comment]
> 

上面提供的长代码是以前版本的窗口编辑器自动生成的
除非窗口编辑器有过长自动换行的功能

**Comment by chunmingwang** [comment]
> It is not recommend worked with too long code in one line.

上面提供的长代码是以前版本的窗口编辑器自动生成的
除非窗口编辑器有过长自动换行的功能

**Comment by chunmingwang** [comment]
> > It is not recommend worked with too long code in one line.
> 
> 上面提供的长代码是以前版本的窗口编辑器自动生成的， 不是人为控制写的， 除非窗口编辑器在生产代码时加入过长代码自动换行的功能。

The long code provided above was automatically generated by previous versions of the Window Editor,
Not written by human control,
Unless the window editor adds the function of too long code when you produce code.

**Comment by hustbeef** [comment]
Yes. Should the IDE add this function automaticaly make a new line if more than 1024 chars?

**Comment by XusinboyBekchanov** [comment]
Send me the code that doesn't work properly in this mode.

**Comment by XusinboyBekchanov** [comment]
Or file with UTF8.

**Comment by hustbeef** [comment]
I think this should close now because the user could make a new line at any position.

**Comment by XusinboyBekchanov** [comment]
>Unless the window editor adds the function of auto wrapping for too long code when generate produce code.

>Yes. Should the IDE add this function automaticaly make a new line if more than 1024 chars?

Added: IDE creates a new line if the string of controls exceeds 1024 characters:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/11d247a29ffd6c1d911421e260f700b76e047b05

**Comment by chunmingwang** [comment]
Thanks!
