### ISSUE TITLE
Feature Request: I would like to have the Keywords Files usable for the theme Settings.

### ISSUE THREAD

**Issue by rexxitall** [XusinboyBekchanov/VisualFBEditor#34]
I would like to have the Keywords Files usable for the theme Settings. 
Then i  could give Control flow keywords different styles then normla keywords, highlight var Types and so on.

**Comment by XusinboyBekchanov** [comment]
This added:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/d590c02cc0cba505077b0ad31f930bda4a339881
