### ISSUE TITLE
Toolbox can't display the Controls

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/VisualFBEditor#340]
Toolbox can't display the Controls
![WeChat Image_20220810125137](https://user-images.githubusercontent.com/35757455/183818590-66fec789-4abc-423b-99ad-0498f14f9791.png)

**Comment by XusinboyBekchanov** [comment]
Move MyFbFramework to the Controls folder.

**Comment by chunmingwang** [comment]
Got it, Thanks.

**Comment by hustbeef** [comment]
OK. It time to increase the version number now.

**Comment by XusinboyBekchanov** [comment]
When there is time I will release version 1.3.3
