### ISSUE TITLE
gui file not running 

### ISSUE THREAD

**Issue by alas82** [XusinboyBekchanov/VisualFBEditor#343]
![Capture](https://user-images.githubusercontent.com/65008114/184549684-3d7396dd-11ae-4516-91f2-01f45862f441.PNG)
i already assign the compiler to /FreeBASIC-1.09.0-winlibs-gcc-9.3.0/fbc.exe
but the project is not compiled to exe file neither running 

please solve it 

thanks

**Comment by XusinboyBekchanov** [comment]
What errors did you get when compiling?

**Comment by alas82** [comment]
photos attached , the exe is not running at all

**Comment by XusinboyBekchanov** [comment]
This is a photo of the launch of a non-existent file.
I need a compilation photo.

**Comment by alas82** [comment]
i understand now we need to compile before run
thanks

**Comment by XusinboyBekchanov** [comment]
The F5 key is "Start With Compilation":
![image](https://user-images.githubusercontent.com/32607344/184551244-f4b51fbe-5498-40b4-a0ef-d09a3fe2b50b.png)

**Comment by alas82** [comment]
thanks for your help , i just wanted to start learning freebasic

**Comment by XusinboyBekchanov** [comment]
Then I will close as solved.
