### ISSUE TITLE
Code editor not redraw if moving splitter

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/VisualFBEditor#345]
Code editor not redraw if moving splitter
See as following screenshot

![fb](https://user-images.githubusercontent.com/35757455/184784513-76c6c33d-7038-4fd6-8f4f-d7a9aa3e1922.png)

**Comment by XusinboyBekchanov** [comment]
Fixed: Updating Edit Control on Divided Mode:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/0ee2c5a6870d963278fe1b8bd6d0203da3a935fd

**Comment by chunmingwang** [comment]
Thanks !
