### ISSUE TITLE
The event cannot be prompted at Event Tab

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/VisualFBEditor#346]
Create multiple controls and manually modify the control event, then the changed event cannot be displayed on the event tab

![Untitled](https://user-images.githubusercontent.com/35757455/184787839-42c9d191-b5f4-4db4-930f-c0eab5cb7930.png)

**Comment by XusinboyBekchanov** [comment]
Fixed: Dictionary IndexOfKey function:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/4712107fd97d9d9d87149e3ae19b66ded39c9f08

**Comment by chunmingwang** [comment]
All main menu click no response

**Comment by chunmingwang** [comment]
Can't Showing multi Selected Control Name in Properties Windows

![Untitled](https://user-images.githubusercontent.com/35757455/184847033-2b0fbcdd-578f-4811-83a3-4b1b8db5deb5.png)

**Comment by XusinboyBekchanov** [comment]
Fixed: Menu:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/3a9ea384e6d36573465b06a123f62400ecad869e

**Comment by XusinboyBekchanov** [comment]
Improved: The names of all selected controls are displayed in the Properties and Events window:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/1c1cd3528cb392ccabf9c9fbae56b782afc9952b

**Comment by chunmingwang** [comment]
Thanks!

**Comment by hustbeef** [comment]
Maybe showing Control type in Properties Windows is better or both.
