### ISSUE TITLE
Forms are not getting destroyed

### ISSUE THREAD

**Issue by flaviofornazier** [XusinboyBekchanov/VisualFBEditor#347]
About SDI applications, except main form, anothers forms (modal or not) are not getting destroyed when I click the close button.

If I call them again, the data that was in the components is still there and when I close the main form I get a lot of errors. What's happening? I'm missing something? 

PS: Attached just "tests"
[sqlite.zip](https://github.com/XusinboyBekchanov/VisualFBEditor/files/9348566/sqlite.zip)
.

**Comment by XusinboyBekchanov** [comment]
Fixed: Form Closing errors:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/0b08f52844417fb61a04d428b452b3dd4cbde195

Non-main forms are only hidden, and are designed to receive data from controls after closing.

**Comment by XusinboyBekchanov** [comment]
Menu also fixed:
https://github.com/XusinboyBekchanov/VisualFBEditor/issues/346#issuecomment-1216399600
