### ISSUE TITLE
Will not display icon of Components Control

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/VisualFBEditor#348]
Will not display icon of Components Controls on form designer, if set AllowDrop true of Form.

![Untitled](https://user-images.githubusercontent.com/35757455/185075007-f728dad0-1a80-4f2b-8c47-1b1f3d6a8f8d.png)

![Untitled1](https://user-images.githubusercontent.com/35757455/185075058-7822e878-da2b-44cc-885d-80e406780a6a.png)

**Comment by XusinboyBekchanov** [comment]
Fixed: AllowDrop property of Control on Design mode:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/e9eccb61489d73dea8a62d89322ba973ba82e2b5

**Comment by chunmingwang** [comment]
Thanks!
