### ISSUE TITLE
-lbass not found

### ISSUE THREAD

**Issue by lonnietc** [XusinboyBekchanov/VisualFBEditor#349]
Hello,

I am just now starting to use FreeBASIC on Windows (coming from C/C++) and installed the compiler on my system (64-bit).

Then, I tried to build a few of your examples with one of them the "Bass" example but it complained that it could not find the "-lbass" for the compiler.

The only bass library that I could find was for Win 32-bit but that did not work as I wanted to build a 64-bit binary.

Any thoughts?

**Comment by XusinboyBekchanov** [comment]
Hello, inside these files there are both 32-bit and 64-bit libraries:
![image](https://user-images.githubusercontent.com/32607344/185663429-b655c8cf-cd86-4b7c-8b28-085baaba9c3b.png)

**Comment by chunmingwang** [comment]
You can find the answer here:

https://github.com/XusinboyBekchanov/VisualFBEditor/pull/275

bass library [lib.zip](https://github.com/XusinboyBekchanov/VisualFBEditor/files/8496369/lib.zip)
