### ISSUE TITLE
MariaDBBox Component Icon disappears from the form when project is reopened

### ISSUE THREAD

**Issue by flaviofornazier** [XusinboyBekchanov/VisualFBEditor#352]
When reopening a project/form and if its contains that component, please automatically check ToolBox -> Components -> MariaDBBox.

PS: Declarations and code related to the component remains on code editor as expected
![Capturar](https://user-images.githubusercontent.com/50641373/186260566-3f9c06a3-fad0-413a-b742-b2355e06aa5c.PNG)
.

**Comment by XusinboyBekchanov** [comment]
Improved: When opening a project, all used controls are loaded into the Toolbox:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/f9b14392597c244534d95331253a0aff248132ff

But first you need to re-save the project with the necessary controls.

**Comment by flaviofornazier** [comment]
Project re-saved, closed and opened many times. Now it's working fine. Thank you so much.
