### ISSUE TITLE
MariaDBBox Incorrect SQL Syntax on method TransactionEnd

### ISSUE THREAD

**Issue by flaviofornazier** [XusinboyBekchanov/VisualFBEditor#353]
Please use "COMMIT instead of "END TRANSACTION" on line 637 of the MARIADBBOX module.
(It came from SQLite that accepts "END TRANSACTION" as an alias for "COMMIT")

Thank you in advanced
![Capturar](https://user-images.githubusercontent.com/50641373/186265612-8cad2a58-c5a0-4dcb-8a07-304a5017dcbf.PNG)
.

**Comment by XusinboyBekchanov** [comment]
Added: TransactionRollback function to SQLite3Component and MariaDBBox:
Fixed: TransactionEnd function of MariaDBBox:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/7310475e21bc25c36071e8031640970efa7b9873

**Comment by flaviofornazier** [comment]
Please keep "START TRANSACTION" or simply "BEGIN" on MARIADBBOX  method "TransactionBegin()". SQL syntax "BEGIN TRANSACTION" does not exists (MariaDB only)

Thank you in advanced.

**Comment by XusinboyBekchanov** [comment]
Fixed: TransactionBegin method of MariaDBBox:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/280cd0ef0cdda8a6fe1661fe9646820eff2eef94

Thanks.

**Comment by flaviofornazier** [comment]
No, I'm the hankful one. =)
