### ISSUE TITLE
SQLite/MariaDBBox ROLLBACK method request

### ISSUE THREAD

**Issue by flaviofornazier** [XusinboyBekchanov/VisualFBEditor#354]
Unfortunately, to complement the "TRANSACTIONS CYCLE" and according to your priorities, "ROLLBACK" method implementation will be necessary.

Thank you in advanced.

**Comment by XusinboyBekchanov** [comment]
Added: TransactionRollback function to SQLite3Component and MariaDBBox:
Fixed: TransactionEnd function of MariaDBBox:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/7310475e21bc25c36071e8031640970efa7b9873

**Comment by flaviofornazier** [comment]
Thanks.
