### ISSUE TITLE
SQLite/MariaDBBox SELECT method request

### ISSUE THREAD

**Issue by flaviofornazier** [XusinboyBekchanov/VisualFBEditor#356]
My first idea about the usage of StringSQL event to modify SQL statements for some purposes can becone quite confusing for some programmers. (Please correct me If I'm wrong). Please accept my most humble apologies and consider the implementation of a "SELECT" method for querying multiples tables in a single SQL command. Something like a "EXEC" method plus the result set in an array, as usual.

Thank you in advanced.

**Comment by XusinboyBekchanov** [comment]
SQLFind does all of this. If we add a new method, it will be a repeated SQLFind.

**Comment by flaviofornazier** [comment]
My sinceres apologies, you're absolutely correct. I was so obstinated to make VFB database components perfect for all type of programmers, so I forgot the obvious.
