### ISSUE TITLE
Feature request : Dark theme for  The  whole IDE /MyFbFramework

### ISSUE THREAD

**Issue by rexxitall** [XusinboyBekchanov/VisualFBEditor#36]
Hi, i tryed a bit to hack. So the idea was to just change the default settings in the hope they woulc take any kind of effekt. But it seems its not that easy :) Are the colors hard coded in the RC ? or is there any central point to change them ?
Would make the IDE looks way more modern. I hate the white Interface since FBedit 10 years ago. And this guy uses also a very strange yellow backgrund :)

'###############################################################################
'#  Graphics.bi                                                                 #
'#  This file is part of MyFBFramework                                         #
'#  Authors: Nastase Eodor, Xusinboy Bekchanov                                 #
'#  Based on:                                                                  #
'#   TGraphics.bi                                                               #
'#   FreeBasic Windows GUI ToolKit                                             #
'#   Copyright (c) 2007-2008 Nastase Eodor                                     #
'#   Version 1.0.0                                                             #
'#  Updated and added cross-platform                                           #
'#  by Xusinboy Bekchanov (2018-2019)                                          #
'###############################################################################

#include once "Object.bi"

'Namespace My.Sys.Drawing
#ifdef __USE_GTK__
	#define clScrollBar           &H000000
	#define clBackground          &H000000
	#define clActiveCaption       &H000000
	#define clInactiveCaption     &H000000
	#define clMenu                &H000000
	#define clWindow              &H000000
	#define clWindowFrame         &H000000
	#define clMenuText            &H000000
	#define clWindowText          &H000000
	#define clCaptionText         &H000000
	#define clActiveBorder        &H000000
	#define clInactiveBorder      &H000000
	#define clAppWorkSpace        &H000000
	#define clHighlight           clOrange
	#define clHighlightText       clWhite
	#define clBtnFace             clGray
	#define clBtnShadow           clLtGray
	#define clGrayText            &H000000
	#define clBtnText             &H000000
	#define clInactiveCaptionText &H000000
	#define clBtnHighlight        &H000000
	#define cl3DDkShadow          &H000000
	#define cl3DLight             &H000000
	#define clInfoText            &H000000
	#define clInfoBk              &H000000
#else

Dim UseUserColors As Integer
 UseUserColors =1

Enum syscolor
    ecl3DDkShadow
    ecl3DLight
    eclActiveBorder
    eclActiveCaption
    eclAppWorkSpace
    eclBackground
    eclBtnFace
    eclBtnHighlight
    eclBtnShadow
    eclBtnText
    eclCaptionText
    eclGrayText
    eclHighlight
    eclHighlightText
    eclInactiveBorder
    eclInactiveCaption
    eclInactiveCaptionText
    eclInfoBk
    eclInfoText
    eclMenu
    eclMenuText
    eclScrollBar
    eclWindow
    eclWindowFrame
    eclWindowText
End Enum

'From MS page adapted
Const 	COLOR_SCROLLBAR	=	0	'Scroll bar gray area.
Const 	COLOR_BACKGROUND	=	1	'Desktop.
Const 	COLOR_DESKTOP	=	1	'Desktop.
Const 	COLOR_ACTIVECAPTION	=	2	'Active window title bar. The associated foreground color is?COLOR_CAPTIONTEXT. Specifies the left side color in the color gradient of an active window's title bar if the gradient effect is enabled.
Const 	COLOR_INACTIVECAPTION	=	3	'Inactive window caption. The associated foreground color is COLOR_INACTIVECAPTIONTEXT. Specifies the left side color in the color gradient of an inactive window's title bar if the gradient effect is enabled.
Const 	COLOR_MENU	=	4	'Menu background. The associated foreground color is COLOR_MENUTEXT.
Const 	COLOR_WINDOW	=	5	'Window background. The associated foreground colors are COLOR_WINDOWTEXT and COLOR_HOTLITE.
Const 	COLOR_WINDOWFRAME	=	6	'Window frame.
Const 	COLOR_MENUTEXT	=	7	'Text in menus. The associated background color is COLOR_MENU.
Const 	COLOR_WINDOWTEXT	=	8	'Text in windows. The associated background color is COLOR_WINDOW.
Const 	COLOR_CAPTIONTEXT	=	9	'Text in caption, size box, and scroll bar arrow box. The associated background color is COLOR_ACTIVECAPTION.
Const 	COLOR_ACTIVEBORDER	=	10	'Active window border.
Const 	COLOR_INACTIVEBORDER	=	11	'Inactive window border.
Const 	COLOR_APPWORKSPACE	=	12	'Background color of multiple document interface (MDI) applications.
Const 	COLOR_HIGHLIGHT	=	13	'Item(s) selected in a control. The associated foreground color is COLOR_HIGHLIGHTTEXT.
Const 	COLOR_HIGHLIGHTTEXT	=	14	'Text of item(s) selected in a control. The associated background color is COLOR_HIGHLIGHT.
Const 	COLOR_3DFACE	=	15	'Face color for three-dimensional display elements and for dialog box backgrounds.
Const 	COLOR_BTNFACE	=	15	'Face color for three-dimensional display elements and for dialog box backgrounds. The associated foreground color is?COLOR_BTNTEXT.
Const 	COLOR_3DSHADOW	=	16	'Shadow color for three-dimensional display elements (for edges facing away from the light source).
Const 	COLOR_BTNSHADOW	=	16	'Shadow color for three-dimensional display elements (for edges facing away from the light source).
Const 	COLOR_GRAYTEXT	=	17	'Grayed (disabled) text. This color is set to 0 if the current display driver does not support a solid gray color.
Const 	COLOR_BTNTEXT	=	18	'Text on push buttons. The associated background color is COLOR_BTNFACE.
Const 	COLOR_INACTIVECAPTIONTEXT	=	19	'Color of text in an inactive caption. The associated background color is COLOR_INACTIVECAPTION.
Const 	COLOR_3DHIGHLIGHT	=	20	'Highlight color for three-dimensional display elements (for edges facing the light source.)
Const 	COLOR_3DHILIGHT	=	20	'Highlight color for three-dimensional display elements (for edges facing the light source.)
Const 	COLOR_BTNHIGHLIGHT	=	20	'Highlight color for three-dimensional display elements (for edges facing the light source.)
Const 	COLOR_BTNHILIGHT	=	20	'Highlight color for three-dimensional display elements (for edges facing the light source.)
Const 	COLOR_3DDKSHADOW	=	21	'Dark shadow for three-dimensional display elements.
Const 	COLOR_3DLIGHT	=	22	'Light color for three-dimensional display elements (for edges facing the light source.)
Const 	COLOR_INFOTEXT	=	23	'Text color for tooltip controls. The associated background color is COLOR_INFOBK.
Const 	COLOR_INFOBK	=	24	'Background color for tooltip controls. The associated foreground color is COLOR_INFOTEXT.
Const 	COLOR_HOTLIGHT	=	26	'Color for a hyperlink or hot-tracked item. The associated background color is COLOR_WINDOW.
Const 	COLOR_GRADIENTACTIVECAPTION	=	27	'Right side color in the color gradient of an active window's title bar. COLOR_ACTIVECAPTION specifies the left side color. Use SPI_GETGRADIENTCAPTIONS with the?SystemParametersInfo?function to determine whether the gradient effect is enabled.
Const 	COLOR_GRADIENTINACTIVECAPTION	=	28	'Right side color in the color gradient of an inactive window's title bar. COLOR_INACTIVECAPTION specifies the left side color.
Const 	COLOR_MENUHILIGHT	=	29	'The color used to highlight menu items when the menu appears as a flat menu (see?SystemParametersInfo). The highlighted menu item is outlined with COLOR_HIGHLIGHT.Windows?2000:??This value is not supported.
Const 	COLOR_MENUBAR	=	30	'The background color for the menu bar when menus appear as flat menus (see?SystemParametersInfo). However, COLOR_MENU continues to specify the background color of the menu popup.Windows?2000:??This value is not supported.

Dim Shared FRAMEWORKCOLORS(eclWindowText) As Integer

Sub SystemcolorInit0()
	FRAMEWORKCOLORS(eclScrollBar) = GetSysColor(COLOR_SCROLLBAR)
	FRAMEWORKCOLORS(eclBackground) = GetSysColor(COLOR_BACKGROUND)
	FRAMEWORKCOLORS(eclActiveCaption) = GetSysColor(COLOR_ACTIVECAPTION)
	FRAMEWORKCOLORS(eclInactiveCaption) = GetSysColor(COLOR_INACTIVECAPTION)
	FRAMEWORKCOLORS(eclMenu) = GetSysColor(COLOR_MENU)
	FRAMEWORKCOLORS(eclWindow) = GetSysColor(COLOR_WINDOW)
	FRAMEWORKCOLORS(eclWindowFrame) = GetSysColor(COLOR_WINDOWFRAME)
	FRAMEWORKCOLORS(eclMenuText) = GetSysColor(COLOR_MENUTEXT)
	FRAMEWORKCOLORS(eclWindowText) = GetSysColor(COLOR_WINDOWTEXT)
	FRAMEWORKCOLORS(eclCaptionText) = GetSysColor(COLOR_CAPTIONTEXT)
	FRAMEWORKCOLORS(eclActiveBorder) = GetSysColor(COLOR_ACTIVEBORDER)
	FRAMEWORKCOLORS(eclInactiveBorder) = GetSysColor(COLOR_INACTIVEBORDER)
	FRAMEWORKCOLORS(eclAppWorkSpace) = GetSysColor(COLOR_APPWORKSPACE)
	FRAMEWORKCOLORS(eclHighlight) = GetSysColor(COLOR_HIGHLIGHT)
	FRAMEWORKCOLORS(eclHighlightText) = GetSysColor(COLOR_HIGHLIGHTTEXT)
	FRAMEWORKCOLORS(eclBtnFace) = GetSysColor(COLOR_BTNFACE)
	FRAMEWORKCOLORS(eclBtnShadow) = GetSysColor(COLOR_BTNSHADOW)
	FRAMEWORKCOLORS(eclGrayText) = GetSysColor(COLOR_GRAYTEXT)
	FRAMEWORKCOLORS(eclBtnText) = GetSysColor(COLOR_BTNTEXT)
	FRAMEWORKCOLORS(eclInactiveCaptionText) = GetSysColor(COLOR_INACTIVECAPTIONTEXT)
	FRAMEWORKCOLORS(eclBtnHighlight) = GetSysColor(COLOR_BTNHIGHLIGHT)
	FRAMEWORKCOLORS(ecl3DDkShadow) = GetSysColor(COLOR_3DDKSHADOW)
	FRAMEWORKCOLORS(ecl3DLight) = GetSysColor(COLOR_3DLIGHT)
	FRAMEWORKCOLORS(eclInfoText) = GetSysColor(COLOR_INFOTEXT)
	FRAMEWORKCOLORS(eclInfoBk) = GetSysColor(COLOR_INFOBK)
End Sub
Sub SystemcolorInit()
	FRAMEWORKCOLORS(eclScrollBar) = 000000
	FRAMEWORKCOLORS(eclBackground) = 000000
	FRAMEWORKCOLORS(eclActiveCaption) = 000000
	FRAMEWORKCOLORS(eclInactiveCaption) = 000000
	FRAMEWORKCOLORS(eclMenu) = 000000
	FRAMEWORKCOLORS(eclWindow) = 000000
	FRAMEWORKCOLORS(eclWindowFrame) = 000000
	FRAMEWORKCOLORS(eclMenuText) = 000000
	FRAMEWORKCOLORS(eclWindowText) = 000000
	FRAMEWORKCOLORS(eclCaptionText) = 000000
	FRAMEWORKCOLORS(eclActiveBorder) = 000000
	FRAMEWORKCOLORS(eclInactiveBorder) = 000000
	FRAMEWORKCOLORS(eclAppWorkSpace) = 000000
	FRAMEWORKCOLORS(eclHighlight) = 000000
	FRAMEWORKCOLORS(eclHighlightText) =000000
	FRAMEWORKCOLORS(eclBtnFace) = 000000
	FRAMEWORKCOLORS(eclBtnShadow) = 000000
	FRAMEWORKCOLORS(eclGrayText) = 000000
	FRAMEWORKCOLORS(eclBtnText) = 000000
	FRAMEWORKCOLORS(eclInactiveCaptionText) = 000000
	FRAMEWORKCOLORS(eclBtnHighlight) = 000000
	FRAMEWORKCOLORS(ecl3DDkShadow) = 000000
	FRAMEWORKCOLORS(ecl3DLight) = 000000
	FRAMEWORKCOLORS(eclInfoText) = 000000
	FRAMEWORKCOLORS(eclInfoBk) = 000000
End Sub
SystemcolorInit

Function clScrollBar() As Integer
   clScrollBar = FRAMEWORKCOLORS(eclScrollBar)
End Function 

Function clBackground() As Integer
   clBackground = FRAMEWORKCOLORS(eclBackground)
End Function 

Function clActiveCaption() As Integer
   clActiveCaption = FRAMEWORKCOLORS(eclActiveCaption)
End Function 

Function clInactiveCaption() As Integer
   clInactiveCaption = FRAMEWORKCOLORS(eclInactiveCaption)
End Function 

Function clMenu() As Integer
   clMenu = FRAMEWORKCOLORS(eclMenu)
End Function 

Function clWindow() As Integer
   clWindow = FRAMEWORKCOLORS(eclWindow)
End Function 

Function clWindowFrame() As Integer
   clWindowFrame = FRAMEWORKCOLORS(eclWindowFrame)
End Function 

Function clMenuText() As Integer
   clMenuText = FRAMEWORKCOLORS(eclMenuText)
End Function 

Function clWindowText() As Integer
   clWindowText = FRAMEWORKCOLORS(eclWindowText)
End Function 

Function clCaptionText() As Integer
   clCaptionText = FRAMEWORKCOLORS(eclCaptionText)
End Function 

Function clActiveBorder() As Integer
   clActiveBorder = FRAMEWORKCOLORS(eclActiveBorder)
End Function 

Function clInactiveBorder() As Integer
   clInactiveBorder = FRAMEWORKCOLORS(eclInactiveBorder)
End Function 

Function clAppWorkSpace() As Integer
   clAppWorkSpace = FRAMEWORKCOLORS(eclAppWorkSpace)
End Function 

Function clHighlight() As Integer
   clHighlight = FRAMEWORKCOLORS(eclHighlight)
End Function 

Function clHighlightText() As Integer
   clHighlightText = FRAMEWORKCOLORS(eclHighlightText)
End Function 

Function clBtnFace() As Integer
   clBtnFace = FRAMEWORKCOLORS(eclBtnFace)
End Function 

Function clBtnShadow() As Integer
   clBtnShadow = FRAMEWORKCOLORS(eclBtnShadow)
End Function  
Function clGrayText() As Integer
   clGrayText = FRAMEWORKCOLORS(eclGrayText)
End Function 

Function clBtnText() As Integer
   clBtnText = FRAMEWORKCOLORS(eclBtnText)
End Function 

Function clInactiveCaptionText() As Integer
   clInactiveCaptionText = FRAMEWORKCOLORS(eclInactiveCaptionText)
End Function 

Function clBtnHighlight() As Integer
   clBtnHighlight = FRAMEWORKCOLORS(eclBtnHighlight)
End Function 

Function cl3DDkShadow() As Integer
   cl3DDkShadow = FRAMEWORKCOLORS(ecl3DDkShadow)
End Function 

Function cl3DLight() As Integer
   cl3DLight = FRAMEWORKCOLORS(ecl3DLight)
End Function 

Function clInfoText() As Integer
   clInfoText = FRAMEWORKCOLORS(eclInfoText)
End Function 

Function clInfoBk() As Integer
   clInfoBk = FRAMEWORKCOLORS(eclInfoBk)
End Function 

	'#define clScrollBar           GetSysColor(COLOR_SCROLLBAR)
	'#define clBackground          GetSysColor(COLOR_BACKGROUND)
	'#define clActiveCaption       GetSysColor(COLOR_ACTIVECAPTION)
	'#define clInactiveCaption     GetSysColor(COLOR_INACTIVECAPTION)
	'#define clMenu                GetSysColor(COLOR_MENU)
	'#define clWindow              GetSysColor(COLOR_WINDOW)
	'#define clWindowFrame         GetSysColor(COLOR_WINDOWFRAME)
	'#define clMenuText            GetSysColor(COLOR_MENUTEXT)
	'#define clWindowText          GetSysColor(COLOR_WINDOWTEXT)
	'#define clCaptionText         GetSysColor(COLOR_CAPTIONTEXT)
	'#define clActiveBorder        GetSysColor(COLOR_ACTIVEBORDER)
	'#define clInactiveBorder      GetSysColor(COLOR_INACTIVEBORDER)
	'#define clAppWorkSpace        GetSysColor(COLOR_APPWORKSPACE)
	'#define clHighlight           GetSysColor(COLOR_HIGHLIGHT)
	'#define clHighlightText       GetSysColor(COLOR_HIGHLIGHTTEXT)
	'#define clBtnFace             GetSysColor(COLOR_BTNFACE)
	'#define clBtnShadow           GetSysColor(COLOR_BTNSHADOW)
	'#define clGrayText            GetSysColor(COLOR_GRAYTEXT)
	'#define clBtnText             GetSysColor(COLOR_BTNTEXT)
	'#define clInactiveCaptionText GetSysColor(COLOR_INACTIVECAPTIONTEXT)
	'#define clBtnHighlight        GetSysColor(COLOR_BTNHIGHLIGHT)
	'#define cl3DDkShadow          GetSysColor(COLOR_3DDKSHADOW)
	'#define cl3DLight             GetSysColor(COLOR_3DLIGHT)
	'#define clInfoText            GetSysColor(COLOR_INFOTEXT)
	'#define clInfoBk              GetSysColor(COLOR_INFOBK)
#endif

```

**Comment by XusinboyBekchanov** [comment]
This is not easy. You need to redraw all the controls. Menu bar to create your own. MyFbFramework does not draw anything now. The standard controls of Windows (Windows API) and GTK are used.

**Comment by rexxitall** [comment]
Yes and no :) The standard controls in Windows are not allways used. I played with windows blinds from stardock a bit. Mostley they are used thats true. The menu bar is a custom ones. and not all  color settings takes effect. The Window text color can not be changed and seems hardcoded to black. Which makes dark or black UI skinning impossible. Parts of the GUI background are hardcoded tho gray or white. Ending up with ugly nasty white frames around the controls. And "best" of all was that Windows 10 has dropped the support for changing the color setup. Was a bit strange to change the things back. Wind 10 still uses the registry entrys for the colors. Just do not has a GUI to set them up. - very "Clever". To make it possible the hardcoded white and black color settings have to be removed first. Then you would have to decide where the color info should comes from. Registry , external file or new Windows 10 settings.  And finally you would need a setup tool and to centralize all color settings as well. I think a separate config would be best. This kind of customisation i tryed since years. If you use the registry keys maybe your application would finally looks great. But then others have had same problem and looks ugly. In Unix they have had same and may have still same problem. Anyhow after the work on the syntax themes it was worth a try.  Some of the dark ones looks really not bad :) Even with the limited possibility settings right now.

**Comment by demosthenesk** [comment]
There is a Dark Theme.
Can be closed.

**Comment by XusinboyBekchanov** [comment]
>There is a Dark Theme.

How to do it?

**Comment by demosthenesk** [comment]
> > There is a Dark Theme.
> 
> How to do it?

Aaahh... he means for the windows decoration.... i thought the code editor....
This is not possible.. in linux the window manager gives the theme on windows.
In Windows 10 i dont know if it is possible.

**Comment by demosthenesk** [comment]
i know gimp 2.8 which uses gtk3 has themes... may be if you look its code ?

**Comment by XusinboyBekchanov** [comment]
Ok

**Comment by demosthenesk** [comment]
> i know gimp 2.8 which uses gtk3 has themes... may be if you look its code ?

sorry my mistake it is Gimp 2.10 that it has the dark theme and light theme. But i don't know which gtk it has, maybe gtk4, i really don't know

**Comment by XusinboyBekchanov** [comment]
VisualFBEditor dark desktop file:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/86d7c9d9245a7e97d8abace4e74e0e4c69666941

This file can be used to launch a dark theme for Linux.

Here's the result:
![Снимок экрана от 2021-09-04 16-30-40](https://user-images.githubusercontent.com/32607344/132092938-f718f9d2-2e06-4902-8973-b8f25824cf86.png)

**Comment by demosthenesk** [comment]
nice!

**Comment by XusinboyBekchanov** [comment]
Added: Dark Mode option:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/77fcc74f1a185a151cfce03da89708c7186802f5

Added: Dark Mode:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/9f57be33955fd565519c10fa347125d3f7462de4

**Comment by XusinboyBekchanov** [comment]
Glad to hear wonderful words from you.

**Comment by rexxitall** [comment]
Well i was busy last months and will be next months. Some bridges are waiting for me. I love dark themes cause first they look cool sure. But also makes work way more easy. I hate to look in a lamp. :) On old screens, when you has had to draw hours thin lines you look after a few days like a white rabbit with red eyes :D. I use black themes since over 30 years whenever possible :).

**Comment by XusinboyBekchanov** [comment]
I agree with you.
