### ISSUE TITLE
Installation on Linux/Raspberry Fails (Attached Fixed Scripts)

### ISSUE THREAD

**Issue by flaviofornazier** [XusinboyBekchanov/VisualFBEditor#360]
Due to recent changes of folder structure, currently Linux/Raspberry installation scripts fails from line 12. Please consider new attached scripts tested on a real machine running Ubuntu Desktop 20.04. Should work fine for the most popular Linux distribuitions. =
[scripts.tar.gz](https://github.com/XusinboyBekchanov/VisualFBEditor/files/9428534/scripts.tar.gz)
![vfb_running_ubuntu_20](https://user-images.githubusercontent.com/50641373/186778637-793cab06-a022-4881-9004-3080fd141f7b.png)
![vfb_ubuntu_20_compilation](https://user-images.githubusercontent.com/50641373/186778639-c4212602-07a4-44d4-90f8-73a3e68ccb9d.png)
)

**Comment by XusinboyBekchanov** [comment]
Very well. But the Compilers folder fit inside the Controls folder.

**Comment by flaviofornazier** [comment]
Thank you. Now the scripts are working well.

**Comment by XusinboyBekchanov** [comment]
Fixed: DownloadAndCompile scripts on Linux:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/fb82d522e9ba79b7bdaf96fd63923ac9c29d9c28

Yes, in my script, too, I did not take into account the compilers folder. Now corrected.

**Comment by flaviofornazier** [comment]
Your scripts have been downloaded and tested again and now they're working fine. Thank you.
