### ISSUE TITLE
Null Pointer Access

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/VisualFBEditor#361]
Issue occurrence process

1. on Form Editor, place a ToolBar to the Form.
2. from ToolBar Editor add a button not change or edit any of properties.
3. Close ToolBar Editor.
4. Click the Form then prompt following message.

![Untitled](https://user-images.githubusercontent.com/35757455/186850281-17d96d5f-c521-4044-9ff3-ca4a2d58475e.png)

**Comment by XusinboyBekchanov** [comment]
Fixed: Error on Design ToolBar:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/ed11379fc505b0bf7269a8ffa108b7d8f1a61586

**Comment by chunmingwang** [comment]
Thanks!
