### ISSUE TITLE
ToolBar Editor

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/VisualFBEditor#363]
1, Can't display the icons on desing time.

desing time
![Untitled-desingtime](https://user-images.githubusercontent.com/35757455/187100253-443c80cc-1c87-401f-8341-a28178f11470.png)

run time
![Untitled-runtime](https://user-images.githubusercontent.com/35757455/187100261-840353da-2d14-4850-9d2e-49f8ad3e45fc.png)

2, Can't Insert/Move Up/Move Down during index on added button

here is my test project
[MDIForm.zip](https://github.com/XusinboyBekchanov/VisualFBEditor/files/9440695/MDIForm.zip)

**Comment by XusinboyBekchanov** [comment]
Fixed: Opening Resourc file on Designer:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/efc55e63012614c7a82d1ed276de9550012091ca

You need change:
`.Add "New " , "New"`
to:
`.Add "New", "New"`

**Comment by chunmingwang** [comment]
> You need change:
> `.Add "New " , "New"`
> to:
> `.Add "New", "New"`

Thanks!

**Comment by XusinboyBekchanov** [comment]
Added: Insert, Move Up and Move Down functions to ToolBar Editor and StatusBar Editor, Fixed: Opening StatusBar Editor:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/82c2e8ddebedf0d5018a5ce4e18096ce4f811610

Added: ControlRepaint Export sub for Control, ChangeIndex method for List, PanelIndex property to StatusPanel, ChangePanelIndex method for StatusBar, ButtonIndex property to ToolButton, ChangeIndex method to ToolButtons:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/ef12e10842faa2d860e8fb6b06e1bd7168f26d48

**Comment by chunmingwang** [comment]
Thanks!

**Comment by XusinboyBekchanov** [comment]
You need:
`MDIForm.RequestAlign`

**Comment by chunmingwang** [comment]
it works, thanks!

**Comment by XusinboyBekchanov** [comment]
I think it's already been decided. Please confirm.

**Comment by chunmingwang** [comment]
is it will improve to display the icons on desing time?

**Comment by chunmingwang** [comment]
Move it to suggestion, close it

**Comment by XusinboyBekchanov** [comment]
It works:
![image](https://user-images.githubusercontent.com/32607344/187693292-a8fffd16-7ce9-431a-a837-2d6ef36807f3.png)

**Comment by XusinboyBekchanov** [comment]
In this comment, I said that I fixed it:
https://github.com/XusinboyBekchanov/VisualFBEditor/issues/363#issuecomment-1229709351
