### ISSUE TITLE
UpDown Component crash IDE (Windows x86/64 only)

### ISSUE THREAD

**Issue by flaviofornazier** [XusinboyBekchanov/VisualFBEditor#364]
Just try drag the component to a form.

Thank you in advanced.

**Comment by XusinboyBekchanov** [comment]
Fixed: UpDown control:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/d9bdbf2dbbd8931edd5ce31d84384393bd9687ed

Thanks.

**Comment by flaviofornazier** [comment]
Fixed. Thanks.
