### ISSUE TITLE
WebBrowser (Windows x86/64 only)

### ISSUE THREAD

**Issue by flaviofornazier** [XusinboyBekchanov/VisualFBEditor#365]
After drag WebBrowser to a form, in designer mode the component tries to access some homepage and after that it does no accept mouse clicks to set its properties, resize it, etc.

Thank you in advanced.

**Comment by XusinboyBekchanov** [comment]
Now it is only possible to define the surroundings of the WebBrowser with the mouse inside the form.

**Comment by flaviofornazier** [comment]
Close issue?

**Comment by XusinboyBekchanov** [comment]
Fixed: WebBrowser designing:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/9306279fe25667b8480a121c9f23c6ce140d4778

**Comment by flaviofornazier** [comment]
Thank you very much Mr.Bekchanov. I'm already behind in my FB studies, 
I'm still fighting with Grid and just now I've notice that TAG property of 
components is not a string... I'm the worst of the worst! lol

**Comment by XusinboyBekchanov** [comment]
If we make Tag a string, then only the string can be set. At the moment it is Any Ptr. That is, you can set pointers of all types (strings too). If you saw in Dotnet, you can also set objects, strings, etc. in the Tag.

**Comment by flaviofornazier** [comment]
Mr.Bekchanov,

You're right, I'm almost reaching pointers chapter...

I'll post the question on the forum.

Thank you in advanced.
