### ISSUE TITLE
StatusBar Editor

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/VisualFBEditor#366]
Start the StatusBar Editor get this issue

![Untitled](https://user-images.githubusercontent.com/35757455/187115076-7e79f265-2dca-4903-8b34-8d2181c42734.png)

**Comment by XusinboyBekchanov** [comment]
Added: Insert, Move Up and Move Down functions to ToolBar Editor and StatusBar Editor, Fixed: Opening StatusBar Editor:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/82c2e8ddebedf0d5018a5ce4e18096ce4f811610

**Comment by chunmingwang** [comment]
Thanks!
