### ISSUE TITLE
RichTextBox component crashes IDE

### ISSUE THREAD

**Issue by flaviofornazier** [XusinboyBekchanov/VisualFBEditor#368]
Just drag the component to a form...

The last component with this kind of problem...

Thank you in advanced.

**Comment by XusinboyBekchanov** [comment]
Fixed: RichTextBox TextRTF property and adding to Designer:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/a778df6260af759db2c977c51d2f63d6d26a83eb

**Comment by flaviofornazier** [comment]
Well... that was de last of it. Thank you very much.
