### ISSUE TITLE
Linux installation

### ISSUE THREAD

**Issue by Plutonium5793** [XusinboyBekchanov/VisualFBEditor#369]
I am trying to install VisualFBEditor in Fedora (36) linux.   I am getting an error on the shown command that it doesn't like some equal signs.  The code seems correct so I am stuck.

[jduchek@HP-K src]$ fbc "VisualFBEditor.bas" -x "../VisualFBEditor64_gtk3" -i "VisualFBEditor/Controls/MyFbFramework" -d __USE_GTK3__
/home/jduchek/01-FreeBasic-2022/VisualFBEditor/src/Main.bi(207) error 59: Illegal specification, at parameter 1 (FileEncoding) of ChangeFileEncoding()
/home/jduchek/01-FreeBasic-2022/VisualFBEditor/src/Main.bi(208) error 59: Illegal specification, at parameter 1 (NewLineType) of ChangeNewLineType()
/home/jduchek/01-FreeBasic-2022/VisualFBEditor/src/Main.bas(140) error 18: Element not defined, Sorted
/home/jduchek/01-FreeBasic-2022/VisualFBEditor/src/Main.bas(141) error 3: Expected End-of-Line, found '='
/home/jduchek/01-FreeBasic-2022/VisualFBEditor/src/Main.bas(142) error 3: Expected End-of-Line, found '='
/home/jduchek/01-FreeBasic-2022/VisualFBEditor/src/Main.bas(143) error 3: Expected End-of-Line, found '='
/home/jduchek/01-FreeBasic-2022/VisualFBEditor/src/Main.bas(144) error 3: Expected End-of-Line, found '='
/home/jduchek/01-FreeBasic-2022/VisualFBEditor/src/Main.bas(145) error 3: Expected End-of-Line, found '='
/home/jduchek/01-FreeBasic-2022/VisualFBEditor/src/Main.bas(146) error 3: Expected End-of-Line, found '='
/home/jduchek/01-FreeBasic-2022/VisualFBEditor/src/EditControl.bi(463) error 59: Illegal specification, at parameter 2 (FileEncoding) of LoadFromFile()
/home/jduchek/01-FreeBasic-2022/VisualFBEditor/src/EditControl.bi(463) error 133: Too many errors, exiting
[jduchek@HP-K src]$ 

I appreciate any help on getting this running. Thanks, John

**Comment by XusinboyBekchanov** [comment]
Maybe you are compiling with the old MyFbFramework. Because, on the old MyFbFramework, there was no FileEncoding, NewLineType enums and Sorted property of WStringList.

**Comment by XusinboyBekchanov** [comment]
You can use DownloadAndCompile.sh file.

**Comment by Plutonium5793** [comment]
Thank you, I will try this.
John

**Comment by Plutonium5793** [comment]
I tried this, and adjusted the first 3 commands for fedora (dnf rather than apt) and minor name change libgtk-3-dev-->gtk3-devel.
the installation went smoothly.  Unfortunately now when I try to run VisualFBEditor64_gtk3  I get a segmentation fault (core dumped) error.  Any idea why that might be?   Thanks for your help,

**Comment by XusinboyBekchanov** [comment]
You can compile with the -g option.
And run with gdb. If it crashes, gdb will show an error line. Enter the command bt and show the result.

**Comment by Plutonium5793** [comment]
I may be showing my ignorance here.   I put the -g after fbc (fbc -g) . (also tried putting the -g additionally next to the -x before the name).   In both cases after compiling I ran gdb VisualFBEditor64_gtk3

and got the following
[jduchek@HP-K VisualFBEditor]$ gdb VisualFBEditor64_gtk3 
GNU gdb (GDB) Fedora 12.1-1.fc36
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from VisualFBEditor64_gtk3...
(No debugging symbols found in VisualFBEditor64_gtk3)
(gdb) 

so somehow my command wasn't right since no debuggin symbols were found.

**Comment by XusinboyBekchanov** [comment]
>fbc -g

In this case, the rest of the commands were also? It should have worked.

>also tried putting the -g additionally next to the -x before the name

In this case it shouldn't work. Because there shouldn't be anything between "-x" and "VisualFBEditor_gtk3".

Try changing the names of the resulting program name. For example: VisualFBEditor_gtk3_g.
And try to run it with gdb.

**Comment by XusinboyBekchanov** [comment]
To run the debugged program, you still need to enter the r command in gdb.

**Comment by Plutonium5793** [comment]
I am currently traveling and will give this a shot within several days.
Thanks for your help,
John

**Comment by XusinboyBekchanov** [comment]
Have a nice trip.

**Comment by demosthenesk** [comment]
Hello,
1) i have run the DownloadAndCompile.sh
2) The compilation with fbc finishes without error
3) i run from terminal ./VisualFBEditor64_gtk3 
4) i get Segmentation fault (core dumped)

**Comment by XusinboyBekchanov** [comment]
Fixed: Running on Linux:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/e3dcb419487b17ae4c0771425d1e5b8db67d2a61

**Comment by demosthenesk** [comment]
i got a compiling warning:
VisualFBEditor.c:7018:7: warning: conflicting types for built-in function ‘execl’; expected ‘int(const char *, const char *, ...)’ [-Wbuiltin-declaration-mismatch]
 7018 | int32 execl( uint8*, uint8*, ... );

**Comment by demosthenesk** [comment]
ok from me IDE is start up and running

**Comment by Plutonium5793** [comment]
I am back. I installed the newest version with no problems in Fedora Linux.   Thank you!
John

**Comment by XusinboyBekchanov** [comment]
Good.
