### ISSUE TITLE
Feature request or fixuo: Drwarf clutter / garbage

### ISSUE THREAD

**Issue by rexxitall** [XusinboyBekchanov/VisualFBEditor#38]
Before the program starts with Dwarf Debug symbols i got a lot of messages which delays the start. 
![image](https://user-images.githubusercontent.com/22050310/84774002-827bb500-afdd-11ea-94bd-5dc444d001d0.png) . I do not know far whats good for, Debugging starts. But it takes time and confuses. I would request a setup switch to hide this messages :)

**Comment by XusinboyBekchanov** [comment]
This added:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/8840e6090a2c2d303b7fab0f5db9df255b25dd08
