### ISSUE TITLE
Can not compile in Linux

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#382]
1) Create a Test Project
2) Create a test.bas module
3) Try to compile
4) i get: File "/home/user/Bin/VisualFBEditor/VisualFBEditor/" not found!

The path /home/user/Bin/VisualFBEditor/VisualFBEditor/ is where VisualFBEditor64_gtk3 and all the files of VFBEditor exists

**Comment by hustbeef** [comment]
You are not set the path of compiler or select a compiler in setting forms.

![image](https://user-images.githubusercontent.com/52040833/189283163-460fd58c-183d-4ec9-b172-315e66edf94d.png)

**Comment by demosthenesk** [comment]
my compiler path is
/home/user/Bin/VisualFBEditor/VisualFBEditor/Compilers/FreeBASIC-1.09.0-linux-x86_64/bin/fbc

**Comment by demosthenesk** [comment]
ok, my mistake i was set the path but not choose the default compiler...
it is ok now!
