### ISSUE TITLE
IDE crashes in Linux

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#384]
1) Run VisualFBEditor64_gtk3
2) Open Test project
3) Double click test.bas to open in code editor
4) IDE crashes
[VFBE_Test.zip](https://github.com/XusinboyBekchanov/VisualFBEditor/files/9540142/VFBE_Test.zip)

**Comment by hustbeef** [comment]
Try add the code "End" to the last line.

**Comment by demosthenesk** [comment]
> Try add the code "End" to the last line.

END (statement) is used to exit the program, and return to the operating system. An optional integer return value can be specified to indicate an error code to the system. If no return value is given, a value of 0 is automatically returned at the end of the program.

Usage of this statement does not cleanly close scope. Local variables will not have their destructors called automatically, because FreeBASIC does not do stack unwinding. Only the destructors of global variables will be called in this case.

**For this reason, it is discouraged to use End simply to mark the end of a program; the program will come to an end automatically, and in a cleaner fashion, when the last line of module-level code has executed.**

**Comment by XusinboyBekchanov** [comment]
>IDE crashes

I tried several times, it didn't happen. Can you post the result of gdb like last time?

**Comment by demosthenesk** [comment]
Thread 1 "VisualFBEditor6" received signal SIGSEGV, Segmentation fault.
0x00000000005fbaee in MY::SYS::FORMS::TABCONTROL::TAB__get__(long) ()

**Comment by XusinboyBekchanov** [comment]
Fixed: Opening files on Linux:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/c1b783d574d720eed02a5a92bc25176d05694548

**Comment by demosthenesk** [comment]
ok fixed!
