### ISSUE TITLE
Crash while writing

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#386]
[v5.zip](https://github.com/XusinboyBekchanov/VisualFBEditor/files/9552706/v5.zip)
1) Run IDE
2) Open OpenWinDOS.vfp
3) Open window.bi
4) Add line 24 of UDT, As UInteger Zorder
5) hit enter to change line
6) crash

Thread 1 "VisualFBEditor6" received signal SIGSEGV, Segmentation fault.
0x00000000005a3cea in WSTRINGLIST::COUNT__get__() ()

**Comment by XusinboyBekchanov** [comment]
Fixed: Crashing IDE on Linux:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/45a14cdeec76233774e9f62421ff874649998a8a

**Comment by demosthenesk** [comment]
ok
