### ISSUE TITLE
No Copy/Paste in Linux

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#388]
No Copy/Paste in Linux

**Comment by demosthenesk** [comment]
Not working the Edit Menu Commands

**Comment by XusinboyBekchanov** [comment]
Fixed: ActiveForm property of Application on Linux:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/5f806d48df3f99eedf7953a156dde9e8cba9211e

Fixed regression. Thanks.

**Comment by demosthenesk** [comment]
ok
