### ISSUE TITLE
Crash on Close

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#389]
Thread 1 "VisualFBEditor6" received signal SIGSEGV, Segmentation fault.
0x0000000000696dc2 in fb_hStrSkipCharRev ()

**Comment by XusinboyBekchanov** [comment]
In what case does this happen? I didn't find it.

**Comment by XusinboyBekchanov** [comment]
After finding the error, you need to enter the bt command in gdb.

**Comment by demosthenesk** [comment]
> In what case does this happen? I didn't find it.

i wrote an empty Sub...End Sub and save the file, and then press close ide from window

**Comment by XusinboyBekchanov** [comment]
>After finding the error, you need to enter the bt command in gdb.

Please try this.

**Comment by demosthenesk** [comment]
i can not redo the crash.
next time i will have it in my mind.

**Comment by chunmingwang** [comment]
Please take a look at the crash issue that occurred with me

1. Start VisualFBEditor64.exe under Windows 10
2. Open project of Examples\MDIScintilla\MDIScintilla.vfp
3. Double click MDIMain.frm to open for edit
4. Close MDIMain.frm then VisualFBEditor64 crash

**Comment by XusinboyBekchanov** [comment]
Fixed: Crash IDE on close tab:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/d126597d17d7c96036b585032342be9d1b79f641

Thanks.

**Comment by chunmingwang** [comment]
> Fixed: Crash IDE on close tab: [d126597](https://github.com/XusinboyBekchanov/VisualFBEditor/commit/d126597d17d7c96036b585032342be9d1b79f641)
> 
> Thanks.

Thank you.

**Comment by XusinboyBekchanov** [comment]
Fixed. The first post is in another thread.
