### ISSUE TITLE
"F8" while debugging has no autorepeat.

### ISSUE THREAD

**Issue by rexxitall** [XusinboyBekchanov/VisualFBEditor#39]
If i want to step trough the debugee i have to press F8 each times to mopve to the next line. Key repeats seems to be disabled for special keys. Makes sense for some of them but not for this ones :)

**Comment by XusinboyBekchanov** [comment]
What are the keys?

**Comment by rexxitall** [comment]
While debugging session - F8 i  jump to the next line / instruction.
Imagine now you has a for next loop from 0 to  255 .
At the moment you are forced to hit 255 510 times the F8 key single by single...
A keyboard has auto repeat.  ...............................................      <the dot line was crated just hold the dot key pressed down. So on the key which jump while debugging to the next line same behavior would be a big help :) Just keep F8 pressed and you can see your programm running..... VBA / VB6  has this debug feature. Its very handy :)

**Comment by XusinboyBekchanov** [comment]
I tried to hold F8, F8 is repeated. Moves to the next line. From time to time I release the key, otherwise it will not be updated.
For such tasks you need to use Run To Cursor.
