### ISSUE TITLE
Crash on edit file

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#391]
Thread 1 "VisualFBEditor6" received signal SIGSEGV, Segmentation fault.
0x000000000069704a in fb_hStrSkipChar ()

#0  0x000000000069704a in fb_hStrSkipChar ()
#1  0x0000000000697c20 in fb_TRIM ()
#2  0x00007fffffffa0b0 in  ()
#3  0x0000000005cfad70 in  ()
#4  0x00007fffffffa0b0 in  ()
#5  0x00007fffffffcb70 in  ()
#6  0x0000000005cc47e0 in  ()
#7  0x00000000004ace5c in GETPARAMETERSPython Exception <class 'gdb.MemoryError'>: Cannot access memory at address 0x7fffffffffffe5a7

**Comment by demosthenesk** [comment]
Also
Thread 1 "VisualFBEditor6" received signal SIGSEGV, Segmentation fault.
0x00000000006970a2 in fb_hStrSkipCharRev ()

#0  0x00000000006970a2 in fb_hStrSkipCharRev ()
#1  0x0000000000697c00 in fb_TRIM ()
#2  0x00007fffffff8ed0 in  ()
#3  0x00007fffffff91f0 in  ()
#4  0x00007fffffff8ed0 in  ()
#5  0x0000000000b64290 in  ()
#6  0x0000000000000100 in  ()
#7  0x00000000004ace5c in GETPARAMETERSPython Exception <class 'gdb.MemoryError'>: Cannot access memory at address 0x7fffffffffffe5a7

**Comment by XusinboyBekchanov** [comment]
Downloaded VisualFBEditor using DownloadAndCompileWithG.sh?

**Comment by XusinboyBekchanov** [comment]
Removed all Trim functions from the GetParameters procedure:
Update TabWindow.bas:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/e1679736c1c4ea8967849cc0b355442b5b950561

Now try.

**Comment by demosthenesk** [comment]
> Downloaded VisualFBEditor using DownloadAndCompileWithG.sh?

yes but gdb gives no lines

**Comment by demosthenesk** [comment]
ok fixed
