### ISSUE TITLE
Add many files not possible

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#392]
If i want to add many bi files i cant. It accepts only one file.

**Comment by XusinboyBekchanov** [comment]
Fixed: Opening multiple files with OpenFileDialog on Linux:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/04398b4b66893ca975d7379fce43a809e1feba63

Thank you.

**Comment by demosthenesk** [comment]
ok fixed
