### ISSUE TITLE
IDE does not 'see' include folders.

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#393]
i set up as compiler
/home/user/Bin/FreeBASIC-1.09.0-ubuntu-20.04-x86_64/bin/fbc

i set up as include folder
/home/user/Bin/FreeBASIC-1.09.0-ubuntu-20.04-x86_64/include/freebasic

i copy https://github.com/angros47/FLTK-headers-for-FreeBasic files to ../include/freebasic/fltk

#include "fltk/Fl.bi" is not seen by ide, nor autocomplete works.

**Comment by demosthenesk** [comment]
false alarm!

**Comment by XusinboyBekchanov** [comment]
You don't need to add an include path. The IDE will find it from the path to the compiler.

**Comment by demosthenesk** [comment]
if i use
#include "Fl.bi" instead #include "fltk/Fl.bi"
compiler gives an error

**Comment by XusinboyBekchanov** [comment]
Because the fltk folder is not included in the include. And you don't need to include it, you can use #include "fltk/Fl.bi".

**Comment by XusinboyBekchanov** [comment]
Or you can include this folder too, then there will be no errors.

**Comment by XusinboyBekchanov** [comment]
Improved: Include paths also added to Auto Complete:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/ba9e34450aa7f4b8a204c632fe2d23621d9c65e4
