### ISSUE TITLE
cannot save Compiler path,reopen will restore

### ISSUE THREAD

**Issue by LFYG** [XusinboyBekchanov/VisualFBEditor#4]
Menu Service -> Options > Compiler >add path 
cannot save path,reopen will restore default
e.g. 

D:\FreeBASIC\FreeBASIC-1.07.1-win32-gcc-5.2.0\fbc.exe
D:\FreeBASIC\FreeBASIC-1.07.1-win64-gcc-5.2.0\fbc.exe

**Comment by XusinboyBekchanov** [comment]
Did you click OK ok Apply?
Please try to click Clear first before adding.

**Comment by LFYG** [comment]
Menu Service -> Options > Compiler >click Clear  > click Apply > add path > click Apply > click OK .
OK , thank you 

Wrong setting:
Menu Service -> Options > Compiler >add path > click Apply > click OK 
cannot save path,reopen will restore default

**Comment by LFYG** [comment]
If you do n’t clear it first, it will fail to save.

**Comment by XusinboyBekchanov** [comment]
> Wrong setting:
You say without clicking OK itself should be saved?

> If you do n’t clear it first, it will fail to save.
Yes, there is a limit of 10 compilers.
In the next release, we will remove this limit.

**Comment by rexxitall** [comment]
I have had also sometimes this strange thing seen. Clean up INI files by hand make it work. I guess if the old settings exists which do not lead to a compiler it stops working. Please set the path "somewhere" in the ini and try to set the right path. I have the feel that the routine just stops if something gets wrong and therefore nothing will be saved or changed.

**Comment by XusinboyBekchanov** [comment]
This fixed. You can now add an unlimited number of paths.
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/a773ea8e9582f1d27c41b13f756d3cee2d6e9458
