### ISSUE TITLE
Feature Request: Blacklist Parts of code while debugging

### ISSUE THREAD

**Issue by rexxitall** [XusinboyBekchanov/VisualFBEditor#40]
Parts of the code should be disabled like chrome debugger can do. For example MyFBFramework i wont debug :) So there should be a setup that at least external code outside the Project folder shuld be ignored.

**Comment by XusinboyBekchanov** [comment]
This added:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/c51d073e06b9778e894cb82167dce358f5ac5bf3
