### ISSUE TITLE
bug in theme on dual display screen

### ISSUE THREAD

**Issue by retsyo** [XusinboyBekchanov/VisualFBEditor#409]
I am using latest VisualFBEditor and mff on windows 10 64 bits.
when VisualFBEditor runs and appear on my main screen(i.e. the screen of my notebook), the dark theme seems ok as image 1 says

then I drag VisualFBEditor to my second display, the background color for toolbar becomes into light-gray as image 2 says, which is some ugly. Then no matter VisualFBEditor lives on main screen, or the second display screen, the background color for toolbar remains  light-gray.

 
![111](https://user-images.githubusercontent.com/7960913/193180338-e1034f6d-7c79-460a-9a16-7a06ba3b5dab.png)

![222](https://user-images.githubusercontent.com/7960913/193179333-373714f4-cdf2-4443-aa87-c345d4e3a855.png)

**Comment by XusinboyBekchanov** [comment]
Fixed: Changing DPI Scale:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/8d6cd765c564a860db2e4c7fa5b07f79395bdcc9
