### ISSUE TITLE
Feature request: "F5" while debug

### ISSUE THREAD

**Issue by rexxitall** [XusinboyBekchanov/VisualFBEditor#41]
In VBA its very handy that if you just reach a breakpoint and has done your examination, you just can press F5 and the program execution continues. This is missing in The Menu. I just figured out by accident. If the programm is debugged or in debugging state just continue if F5 or other key is pressed. BTW Thanks for adding the shortcut Setup :)

**Comment by XusinboyBekchanov** [comment]
There are F5. You will try?

**Comment by rexxitall** [comment]
I try it by "mistake" already . For the "unexpierienced" or new user there should be a menu item there   also :)

**Comment by XusinboyBekchanov** [comment]
There are menu item:
![image](https://user-images.githubusercontent.com/32607344/84799704-17020980-b016-11ea-86f6-efcf12b82ae9.png)
