### ISSUE TITLE
very long width on dual display screen

### ISSUE THREAD

**Issue by retsyo** [XusinboyBekchanov/VisualFBEditor#410]
I am using latest VisualFBEditor and mff on windows 10 64 bits.
First I use only one screen (i.e. the screen of my notebook). I toggle VisualFBEditor to full screen. And I quit VisualFBEditor

Then I enable my second screen as for an extended screen, and run VisualFBEditor. I drag VisualFBEditor to the second screen. Suddenly, the panel of VisualFBEditor gets very big in width. Actually, it uses up both the first and the second screen in width direction

**Comment by hustbeef** [comment]
Yes. VisualFBEditor didn't tested on dual display screen

**Comment by XusinboyBekchanov** [comment]
Fixed: Changing DPI Scale:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/8d6cd765c564a860db2e4c7fa5b07f79395bdcc9

Try this.
