### ISSUE TITLE
bad record of last-used tab

### ISSUE THREAD

**Issue by retsyo** [XusinboyBekchanov/VisualFBEditor#414]
I am using latest VisualFBEditor and mff on windows 10 64 bits.

I click "project properties"-"compile"-"compile to GCC" - "optimize for fast code"-"ok". then I close "project properties" window

I click "project properties" again, as you can find that the tab is on "General", but the contain is actually for "compile"

![111](https://user-images.githubusercontent.com/7960913/193384503-58e326b2-0298-481b-8de3-dfc87591c945.png)

**Comment by XusinboyBekchanov** [comment]
Fixed: Showing Project Properties Window with First tab:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/cb2eea6db11d36ac04e0c586e4d0744c3419bddc

**Comment by XusinboyBekchanov** [comment]
Reverted: Selecting first tab of Project Properties:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/6545a3ce046e1c930046765c13772663bf6d791b

Fixed: Showing last opened TabPage on recreate TabControl window:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/d76218ad70303cbc25513870c60b7c337f88098a
