### ISSUE TITLE
flash between desktop when I close project window

### ISSUE THREAD

**Issue by retsyo** [XusinboyBekchanov/VisualFBEditor#415]
I am using latest VisualFBEditor and mff on windows 10 64 bits.

I open "project"-"project properties", then click "ok" button, my desktop is shown for a very little time, then VisualFBEditor is shown. Since my wallpaper is in white color, VisualFBEditor uses default dark theme, the flash between 2 colors make my eyes not comfortable.

This does not occur in previous VisualFBEditor, and not in menu item "Service"-"options"-"ok"

**Comment by retsyo** [comment]
https://user-images.githubusercontent.com/7960913/193870216-9057318d-31d6-40dd-928d-1e176fb92c72.mp4

**Comment by retsyo** [comment]
it happends in this case too. 
1. no file/project is opened 
2. open 'project'-'project properities', do nothing, just click 'cancel' button
3. my last opened application's interface(in the video, its a notepad) shows first, then quickly VFB's interface shows. Thus there is a transition from VFB 'project properities''s dark window to notepad.exe's white looking, then to VFB's dark theme again in my video, it is a uncomfortable flash for eyes. In fact, if 'project properities' window is closed, VFB's window is expected to show immediately.

please note, the flash is too quick, so to let you find it easily, some video frames is duplicated, and the description in red is added.


https://user-images.githubusercontent.com/7960913/194082213-2df01ef4-cfef-4bb3-9c48-92e7b51ec40c.mp4

**Comment by XusinboyBekchanov** [comment]
Fixed: Blink on closing Modal Form:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/886cfad0eac3ae025938c00759ea18e1280f847d

**Comment by XusinboyBekchanov** [comment]
Fixed: Form ShowModal method:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/59ac4858c1d7f983e64822a886fb6aa80b869b55

**Comment by retsyo** [comment]
it seems that the bug has been fixed really. Thanks. I closed this issue.

**Comment by XusinboyBekchanov** [comment]
Thanks for reporting this issue.
