### ISSUE TITLE
ctrl+F9: No Main file specified for the project.!

### ISSUE THREAD

**Issue by retsyo** [XusinboyBekchanov/VisualFBEditor#416]
I am using latest VisualFBEditor and mff on windows 10 64 bits. VFB uses "compile default"
When I press ctrl+F9(compile), nothing happens except "No Main file specified for the project.!" is displayed in the output tab.
But when I press ctrl+alt+F9(compile all), exe is produced.

however, for the sample project, ctrl+F9 always make exe in previous VFB without problem

**Comment by XusinboyBekchanov** [comment]
I tried to create a new project -> GUI Application -> Ctrl+F9 works, maybe you don't have the main file setted for the project.

**Comment by retsyo** [comment]
no, I use my previous project which can be ctrl+F9

But I can't re-produce the reported issues after I reopen VFB.
