### ISSUE TITLE
bug when ctrl+mouse wheel in code editor

### ISSUE THREAD

**Issue by retsyo** [XusinboyBekchanov/VisualFBEditor#417]
when I use ctrl + mouse wheel to make the code editor have a big font, first it works as expected, after some seconds, the font   does not become bigger, instead the distance between lines becomes bigger. 
Then I ctrl +mouse wheel to move down and up for some more seconds, the code is displayed in a constant tiny size font so that I can't read it at all even the distance between line becomes too big, in my pic 2, the disctance is almost 1/5 of my screen's height!

![111](https://user-images.githubusercontent.com/7960913/193847966-4832c49c-585f-44cc-ab5a-83e8516df7c2.png)
 
![222](https://user-images.githubusercontent.com/7960913/193847955-e75abf65-10b1-4b32-9369-4b064b598e1c.png)

**Comment by hustbeef** [comment]
Could you please continue ctrl +mouse wheel to move down and up? This happen one time and never coming again.

**Comment by retsyo** [comment]
there are 2 videos
for "wheel down", I press ctrl then roll the mouse wheel down, yes always down without up

for "wheel up", I press ctrl then roll the mouse wheel up, yes always up without down


https://user-images.githubusercontent.com/7960913/193866131-56ff7e23-ed6e-4dde-afe6-99f461fede60.mp4


https://user-images.githubusercontent.com/7960913/193866215-88de3192-b09f-4572-bd8e-42bbcb3edd81.mp4

**Comment by retsyo** [comment]
almost 1 hours ago, ctrl+mouse wheel roll has made my code editor into a messy. I can't restore it to proper font size, line distance and zoom factor.

**Comment by retsyo** [comment]
the messy one use a font of courier new, -145pt

**Comment by hustbeef** [comment]
We can add a limitation for the smallest font size to 1pt.

**Comment by XusinboyBekchanov** [comment]
>We can add a limitation for the smallest font size to 1pt.

Here:
Fixed: Set limit for smallest font size to 1pt on Ctrl+Mouse wheel in Code Editor:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/8c836a939527c9d008a028f671d24494d858fd60

**Comment by retsyo** [comment]
Not yet as the video says. Sorry I have to compress the video into `7z` format for attachment size limitation, please remove the trailing `.zip` to decompress it.
 
My notebook has a screen resolution of 1920*1080, and the text is shown at 125% as windows 10 recommend . I don't know whether the setting matters.

[wheelbug.7z.zip](https://github.com/XusinboyBekchanov/VisualFBEditor/files/9716124/wheelbug.7z.zip)

**Comment by XusinboyBekchanov** [comment]
Fixed: Ctrl + MouseWheel:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/f60b657d86e7686d52481038fb7b1b479fef9729

**Comment by retsyo** [comment]
it seems that the bug has been fixed really. Thanks. I closed this issue.

**Comment by XusinboyBekchanov** [comment]
Then I close. Thank you too for reporting this issue.
