### ISSUE TITLE
Text Search Bug and Feature request

### ISSUE THREAD

**Issue by rexxitall** [XusinboyBekchanov/VisualFBEditor#42]
The bug is that the word or text to search has to be in the clipboars. Usually the word is taken without to do anything.
Either the word or line will be taken below the cursoer
Or if marked the marked area will be used.
if you choose a empty area nothing is choosen. Thats very handy and standard in most progrmming environments and text processors i know :) ...a lot ;)

Microsoft designs the Find Dialog like this, which is very handy and easy to understand :) 
![image](https://user-images.githubusercontent.com/22050310/84775361-6aa53080-afdf-11ea-84a3-b2185d59f28b.png)

You can tewak it a bit by adding buttons like you has jump prev, jump next and so on. If you press the replace button he changed his view to becomes the replace Dialog which is also very handy. Very often you wants to replace things you find. 

You can select old searches , can tell search direction, where to search. Your Search is very powerful and i like the grep style idea in the bottom window. 

The Replace thing from VBA is not that perfect. Here i suggest to use or robb/adopt parts from Notepad++. There you can also replace Tabs, linebreaks and so on :)

**Comment by XusinboyBekchanov** [comment]
Made the first paragraph of this post. I.e. When you open the search box by default, the current word in the editor is put in the textbox:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/27cc6cd3eae1fdd1956b6c26dad28e773854ee7a

**Comment by rexxitall** [comment]
Make this way more usable :) i will give it a try later on

**Comment by rexxitall** [comment]
Bug is fixed. Text gets in the find box and location of editor cursor is updated :)
