### ISSUE TITLE
bug: project properties windows size on dual display

### ISSUE THREAD

**Issue by retsyo** [XusinboyBekchanov/VisualFBEditor#424]
I am using latest VisualFBEditor and mff on windows 10 64 bits.

when VisualFBEditor appears on my main screen(i.e. the screen of my notebook, resolution is `1920*1080`, and the text is zoomed to `120%`), I choose to create a new "windows Appliaction" project. Then I maximize VisualFBEditor and drag it to my second/external display(`2560*1440`, the text is shown at  a factor of `100%`).

VisualFBEditor does not take up all the screen of my bigger display, which is expected. Then I click "project->project properties", the window displays but we can find that not  all cotrols, especially the buttons, are displayed.

Either it is can be considered as a bug on dual display, or not a bug by allowing users can drag-to-zoom properties windows size. I prerfer to the first thought.

   

![Clipboard02](https://user-images.githubusercontent.com/7960913/197342290-42a9bc22-ae52-4b74-8685-b5e4345121f7.png)

**Comment by retsyo** [comment]
btw, there is a feature request too, please open all sub-windows on the display where VisualFBEditor opens. 

For example, in the above case, VisualFBEditor lives on my second/external display, however "project properties window" always appears on my main screen(i.e. the screen of my notebook)

**Comment by simulanics** [comment]
Not sure if this is related, but in another language I develop with, this issue occurs on monitors with screen-scaling. For example, an app that had this issue, I had to check for screen scale for hi-dpi, and then multiply all controls' height and width by the scale, including the window's height and width, or the controls get clipped. It looks like the controls are scaling correctly, but the window is not? Try setting the external monitor resolution to 1:1 and see if that works to fix the window clipping (granted everything may be extremely small on a hi-dpi monitor). If that resolved the issue, then there may be a correlation.

**Comment by XusinboyBekchanov** [comment]
>It looks like the controls are scaling correctly, but the window is not?

I have set a common DPI for the entire application.
We need to split this into each shape. For testing, I need two monitors. I have not yet bought such monitors or have not found the opportunity to use other people's monitors.

>Try setting the external monitor resolution to 1:1 and see if that works to fix the window clipping (granted everything may be extremely small on a hi-dpi monitor). If that resolved the issue, then there may be a correlation.

If set 1:1 everything works correctly.
