### ISSUE TITLE
Examples does not compile

### ISSUE THREAD

**Issue by rexxitall** [XusinboyBekchanov/VisualFBEditor#43]
To make your life a bit more easy i comes on the idea to write a plugin byself. First it does not compiles by some strange message. A second obstacle was the lack of any kind of documentation.
A well documented filter Example would help a lot. (As well as e menu point for external tolls which could for sure also be some kind of text filter).

![image](https://user-images.githubusercontent.com/22050310/84776708-f10e4200-afe0-11ea-817d-76c39043e0b5.png)

**Comment by XusinboyBekchanov** [comment]
Without the switch -g compiles without problems. I don’t know why it does not compile with this key.

**Comment by rexxitall** [comment]
I will try it :) Should also compile with -g. But ... :)

**Comment by XusinboyBekchanov** [comment]
This fixed, in fbc 1.07.3.
