### ISSUE TITLE
Example Project - Bass: LiveFX - Fails to Build - Variable Declaration Mismatched Integer vs DWORD

### ISSUE THREAD

**Issue by simulanics** [XusinboyBekchanov/VisualFBEditor#439]
frmLiveFX.frm fails to build on Windows for line #28 

With input declared as an Integer. The InputInfo function found on line #409 calls for a DWORD as the 1st parameter.

Changing line #28 in frmLiveFX.frm to the following, fixes the issue:

`Input as DWORD`

**Comment by XusinboyBekchanov** [comment]
Fixed: Compiling LiveFX example on 64-bit Windows:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/e268d9a6b449c58aebb709fcc61910833194fb4c

Thanks, fixed it. Haven't run it in 64-bit before.
