### ISSUE TITLE
Designer Refresh onMouseUp Event

### ISSUE THREAD

**Issue by simulanics** [XusinboyBekchanov/VisualFBEditor#440]
Hello, 

A few controls in the designer do not repaint to the screen on resize. For example, the PageScroller Example can be seen below after resizing the commandbutton.

![refreshissue](https://user-images.githubusercontent.com/2744687/207201779-a9a3fd40-0e1c-4ba4-bff0-1db93a13e8fc.jpg)

I believe a refresh to the paint event may be needed somewhere. I anticipate to delve deep into the source code this week to make some contributions. 👍

**Comment by XusinboyBekchanov** [comment]
>I anticipate to delve deep into the source code this week to make some contributions. 👍

A good idea.
