### ISSUE TITLE
Hard Crash - Control Library

### ISSUE THREAD

**Issue by simulanics** [XusinboyBekchanov/VisualFBEditor#446]
IDE hard-crashes after attempting to draw a control on the main window surface **

**Steps to reproduce:
1) Open VFBE
2) Select Control Library option
3) Attempt to add any control to the surface

**Comment by XusinboyBekchanov** [comment]
This doesn't happen to me. What control are you adding?

**Comment by XusinboyBekchanov** [comment]
I found this case.

**Comment by XusinboyBekchanov** [comment]
Fixed: Crash on design UserControl:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/f1c18dda4d977863f44b0a1748863bbf7525720e
