### ISSUE TITLE
Segmentation Violation Signal (12)

### ISSUE THREAD

**Issue by simulanics** [XusinboyBekchanov/VisualFBEditor#447]
To Reproduce:

Menu Bar -> Service -> Tools...

Upon clicking "Tools..." a segmentation violation signal (12) occurs in USTRING.bas.

An error message only appears for 32-bit builds. 
For 64-bit builds, no warning is displayed upon crash. Instead, the IDE Closes immediately.

<img width="332" alt="image" src="https://user-images.githubusercontent.com/2744687/207943870-6bd2a51e-ee83-4215-90b1-2252947384bb.png">

**Comment by XusinboyBekchanov** [comment]
Fixed: Crash on open Tools Window:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/fcd12d731629ffe699820a0638053cca07a2f032

Thanks.
