### ISSUE TITLE
BCD type members cannot be displayed complete

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/VisualFBEditor#448]
at the SerialPort Example, there is a type named BCD, it's members cannot be displayed complete as following snap shot.

```
Type _DCB
	DCBlength As DWORD
	BaudRate As DWORD
	fBinary : 1 As DWORD
	fParity : 1 As DWORD
	fOutxCtsFlow : 1 As DWORD
	fOutxDsrFlow : 1 As DWORD
	fDtrControl : 2 As DWORD
	fDsrSensitivity : 1 As DWORD
	fTXContinueOnXoff : 1 As DWORD
	fOutX : 1 As DWORD
	fInX : 1 As DWORD
	fErrorChar : 1 As DWORD
	fNull : 1 As DWORD
	fRtsControl : 2 As DWORD
	fAbortOnError : 1 As DWORD
	fDummy2 : 17 As DWORD
	wReserved As WORD
	XonLim As WORD
	XoffLim As WORD
	ByteSize As UByte
	Parity As UByte
	StopBits As UByte
	XonChar As Byte
	XoffChar As Byte
	ErrorChar As Byte
	EofChar As Byte
	EvtChar As Byte
	wReserved1 As WORD
End Type
```
The following members cannot be displayed

```
	fBinary : 1 As DWORD
	fParity : 1 As DWORD
	fOutxCtsFlow : 1 As DWORD
	fOutxDsrFlow : 1 As DWORD
	fDtrControl : 2 As DWORD
	fDsrSensitivity : 1 As DWORD
	fTXContinueOnXoff : 1 As DWORD
	fOutX : 1 As DWORD
	fInX : 1 As DWORD
	fErrorChar : 1 As DWORD
	fNull : 1 As DWORD
	fRtsControl : 2 As DWORD
	fAbortOnError : 1 As DWORD
	fDummy2 : 17 As DWORD
```

![image](https://user-images.githubusercontent.com/35757455/207992750-deddfcb4-4205-4879-b81e-c715bd9e56e3.png)

**Comment by XusinboyBekchanov** [comment]
Fixed: IntelliSense for Type Fields with bits:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/c25a961fdb75ddc9c2300ee96e15cdc36f7bece2

**Comment by chunmingwang** [comment]
> Fixed: IntelliSense for Type Fields with bits: [c25a961](https://github.com/XusinboyBekchanov/VisualFBEditor/commit/c25a961fdb75ddc9c2300ee96e15cdc36f7bece2)

It's working, Thanks!

![image](https://user-images.githubusercontent.com/35757455/208013013-a3a3eed3-2dd6-4045-ae5c-b9f3313cf402.png)
