### ISSUE TITLE
Segmentation fault on startup (Linux64 GTK3)

### ISSUE THREAD

**Issue by birosys** [XusinboyBekchanov/VisualFBEditor#449]
After the initial screen is displayed and the parameters are loaded, the program stops working with a message
Segmentation fault in terminal.

**Comment by XusinboyBekchanov** [comment]
Fixed: Application:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/f2f73fa58af3d155911a5289db4553ad3c9253ad
