### ISSUE TITLE
Feature Request: Start behaviour

### ISSUE THREAD

**Issue by rexxitall** [XusinboyBekchanov/VisualFBEditor#46]
Somehow VFBE loads some kind of "random" file on Program start.
There should be a dropdown in the setup how to start. (Like any browser has)

Nothing
Empty file
Empty Project
Last File
Last Project
Last Session

:)

**Comment by XusinboyBekchanov** [comment]
It's done:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/169c9ba40ee0e3d03ff88b37d9ba79130f946687
