### ISSUE TITLE
Problem at Goto Define(F2)

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/VisualFBEditor#465]
Problem at Goto Define(F2)

Problem recurrence process
1, New create a GUI application
2, Mouse cursor move to text of "Form"
![1675741674817](https://user-images.githubusercontent.com/35757455/217143491-66fceb1b-296c-4185-9514-85b7e47bae6c.png)
3, Press [F2]
![image](https://user-images.githubusercontent.com/35757455/217143644-b07ac549-881d-49a1-b2e2-c9c44d1f1f05.png)
4, Select and double click "Form [Type]"
5, Prompt "File not found: 0" msgbox
![1675741481977](https://user-images.githubusercontent.com/35757455/217143137-11f31c8e-2039-4f71-8433-8e90196b7a34.png)

**Comment by XusinboyBekchanov** [comment]
Fixed: Define:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/513222e96f2b612a38030fbc6548e0fa36835128

Thank you.

**Comment by chunmingwang** [comment]
Thanks!
