### ISSUE TITLE
new(ctrl N) behavior is different bettwen menu command and toolbar button

### ISSUE THREAD

**Issue by elfsimulate** [XusinboyBekchanov/VisualFBEditor#486]
![图片](https://user-images.githubusercontent.com/29616909/220820114-3fe3282e-48d4-400a-95f8-fb613e4eddb9.png)
menu command creates a new  project
![图片](https://user-images.githubusercontent.com/29616909/220820166-892882c7-de74-43ee-9f95-f1c7fd105d7b.png)
toolbar button creates a new file

**Comment by XusinboyBekchanov** [comment]
It was a hustbeef's idea, earlier there was a separate menu item for the new project.

**Comment by XusinboyBekchanov** [comment]
Added: New Project menu item:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/880139d6c2bfcdb636aafce22a2342a7c00d6b01

**Comment by XusinboyBekchanov** [comment]
Thank you too.
