### ISSUE TITLE
Find Dialog doesnt jump to the code window

### ISSUE THREAD

**Issue by rexxitall** [XusinboyBekchanov/VisualFBEditor#49]
If i end the find dialog by ESC for example . The editor windows should be activated and the cursor should stay on start to the last found word-  or on the  last known position ( before find was called). If you find something you usually has a reason to search for it. Usually you want to change it. So the cursor has to be set automatically to that position :) Sorry for creating a lot of issues at the moment. But i really try to work with it :) I like it. I would love it if those tiny edges would get rounded :)

**Comment by XusinboyBekchanov** [comment]
This fixed:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/281352a49698581b99afb542b3eb29c7dea3c644
and
https://github.com/XusinboyBekchanov/MyFbFramework/commit/a13310bcf5c387d446f72de3ba2b3e27b5ba12f0

**Comment by rexxitall** [comment]
:) I will have a look at it later :) And check it out. I very often search things. I get old :D
