### ISSUE TITLE
Scroll up with left mouse key do not mark anything or scrolls.

### ISSUE THREAD

**Issue by rexxitall** [XusinboyBekchanov/VisualFBEditor#50]
Holding left mouse and scroll down will force also the editor window to scroll. It also marks lines. That is ok.

Same should be possible if i want to mark reverse. So i want sroll up while left maouse key is pressed

**Comment by XusinboyBekchanov** [comment]
This fixed:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/5372748fa30c7e0c6d5249ee9508769c5d98df12

**Comment by rexxitall** [comment]
It marks in reverse direction but do not scroll upwards if mouse reaches upper editor border.
I build it with the fbframework and ide source from today - found on github 22.06.2020

**Comment by XusinboyBekchanov** [comment]
I do not understand, can you show with a picture?

**Comment by XusinboyBekchanov** [comment]
Or do you want to say that?
![image](https://user-images.githubusercontent.com/32607344/85266684-a3388480-b48d-11ea-86ed-7df7edf83aa8.png)

**Comment by XusinboyBekchanov** [comment]
This fixed:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/171d3a7995ecd649e128b3cc30ca95ba9506796b

**Comment by rexxitall** [comment]
Yes that was what i want to say. Very often i start at the bottom of a sub or function and mark upwards til the sub / function head. Heads are more easy to recognize then ends :)

**Comment by rexxitall** [comment]
:) Works
