### ISSUE TITLE
Trackbar set to vertical style doesn't display properly

### ISSUE THREAD

**Issue by W98X** [XusinboyBekchanov/VisualFBEditor#508]
1. Add a trackbar to the form

2.  Set the style property to `1- tbVertical`

3. The trackbar disappears from the form

![vfbe-trackbar vertical not show](https://user-images.githubusercontent.com/88371717/231116574-6e95ead9-d081-4dc4-88e5-3ae664e412ef.jpg)

**Comment by XusinboyBekchanov** [comment]
Fixed: Setting Style property of TrackBar control:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/2ae99e754603d7d32150ebf0828b6c8ed7dd7bab
