### ISSUE TITLE
Picturebox RealSizeimage and CenterImage  properties dont work

### ISSUE THREAD

**Issue by W98X** [XusinboyBekchanov/VisualFBEditor#509]
When added a `Picturebox` control to a form, the properties in the propertygrid for `RealSizeImage` and `CenterImage` don't do anything.

![vfbe-picturebox center image](https://user-images.githubusercontent.com/88371717/231118885-be4bfa16-4cc0-4e78-adcb-19dbb55f79ab.jpg)

![vfbe-picturebox realsize image](https://user-images.githubusercontent.com/88371717/231118988-2a95c039-f5b2-48e3-ac69-eed855349f0b.jpg)

**Comment by XusinboyBekchanov** [comment]
Fixed: ReadProperty and WriteProperty function for CenterImage, RealSizeImage and Style properties of Picture control:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/66c90cc3c827c99ed9464df51c3b226c819c09bb

**Comment by XusinboyBekchanov** [comment]
> RealSizeImage = Not sure what it does. Changing this doesn't seem to have any affect. What is it supposed to do?

It didn't work for me either. The documentation says that SS_REALSIZEIMAGE only works with the SS_ICON style.
https://learn.microsoft.com/en-us/windows/win32/controls/static-control-styles

> What I want to achieve is to have a large image resized to fit inside the control, whilst also maintaining it's aspect ratio and not being distorted. Is there any way to achieve that in VFBE?

So it is possible:
```
'#Region "Form"
	#if defined(__FB_MAIN__) AndAlso Not defined(__MAIN_FILE__)
		#define __MAIN_FILE__
		#ifdef __FB_WIN32__
			#cmdline "Form1.rc"
		#endif
		Const _MAIN_FILE_ = __FILE__
	#endif
	#include once "mff/Form.bi"
	#include once "mff/Picture.bi"
	
	Using My.Sys.Forms
	
	Type Form1Type Extends Form
		Declare Static Sub _Form_Resize(ByRef Sender As Control, NewWidth As Integer, NewHeight As Integer)
		Declare Sub Form_Resize(ByRef Sender As Control, NewWidth As Integer, NewHeight As Integer)
		Declare Constructor
		
		Dim As Picture Picture1
	End Type
	
	Constructor Form1Type
		' Form1
		With This
			.Name = "Form1"
			.Text = "Form1"
			.Designer = @This
			.OnResize = @_Form_Resize
			.SetBounds 0, 0, 350, 300
		End With
		' Picture1
		With Picture1
			.Name = "Picture1"
			.Text = "Picture1"
			.TabIndex = 0
			.CenterImage = False
			.Graphic = "Logo"
			.Style = PictureStyle.ssBitmap
			.SetBounds 0, 0, 334, 261
			.Designer = @This
			.Parent = @This
		End With
	End Constructor
	
	Private Sub Form1Type._Form_Resize(ByRef Sender As Control, NewWidth As Integer, NewHeight As Integer)
		(*Cast(Form1Type Ptr, Sender.Designer)).Form_Resize(Sender, NewWidth, NewHeight)
	End Sub
	
	Dim Shared Form1 As Form1Type
	
	#if _MAIN_FILE_ = __FILE__
		App.DarkMode = True
		Form1.MainForm = True
		Form1.Show
		App.Run
	#endif
'#End Region

Private Sub Form1Type.Form_Resize(ByRef Sender As Control, NewWidth As Integer, NewHeight As Integer)
	With Picture1.Graphic.Bitmap
		If Me.ClientWidth - .Width < Me.ClientHeight - .Height Then
			Picture1.SetBounds 0, (Me.ClientHeight - .Height * Me.ClientWidth / .Width) / 2, Me.ClientWidth, .Height * Me.ClientWidth / .Width
		Else
			Picture1.SetBounds (Me.ClientWidth - .Width * Me.ClientHeight / .Height) / 2, 0, .Width * Me.ClientHeight / .Height, Me.ClientHeight
		End If
	End With
End Sub
```

**Comment by XusinboyBekchanov** [comment]
In this case, it relies on the functions of the control itself. If we add this function, we must draw ourselves or we must add another element inside this control.

**Comment by XusinboyBekchanov** [comment]
Added: StretchImage property to Picture control:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/033f81729b9d70282c7e9cf497eea835d6a696ae
