### ISSUE TITLE
Feature request: if a file is changed by an external program the IDE should ask how to act

### ISSUE THREAD

**Issue by rexxitall** [XusinboyBekchanov/VisualFBEditor#51]
I do some code generations at the moment. It would be nice if the IDE recognice taht a file has been changed by a external program. She should ask to load it (update) or to ignore those changes. If its loaded the cursor position should be kept in place if possible. :)

**Comment by rexxitall** [comment]
In any case a function to reload the file is also very handy in cases if you do something by mistake.

**Comment by XusinboyBekchanov** [comment]
This added:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/8de3bef6b8868aeadcf6c1c08fc65e37ab3fa6fd
https://github.com/XusinboyBekchanov/MyFbFramework/commit/47941c4984094690d34e469ef21c5313ff663a24
