### ISSUE TITLE
Open file control remains on the form editor after the control has been deleted from the form

### ISSUE THREAD

**Issue by W98X** [XusinboyBekchanov/VisualFBEditor#510]
1. Add an `openfilecontrol` to a form
2. Delete the`openfilecontrol` from the form
3. The `openfilecontrol` remains on the form and cannot be deleted

![vfbe-open file control not deleted](https://user-images.githubusercontent.com/88371717/231120177-232e8a70-ea33-4d6b-999c-4804ce4cf056.png)

**Comment by XusinboyBekchanov** [comment]
Fixed: OpenFileControl deleting:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/4281ec57f03d68a22ddd3a86dbe691d7972a673c
