### ISSUE TITLE
Can't create a command button with an icon but no text

### ISSUE THREAD

**Issue by W98X** [XusinboyBekchanov/VisualFBEditor#511]
Trying to create a command button that has an icon but no text

Step 1: Create a command button on the form

Step 2: Set the graphic property to give it an icon

Step 3: Set the `Style` property in the property panel for the button to `1 -bsBitmap` doesn't do anything, it resets to `0 - bsText`

![vfbe- button style property](https://user-images.githubusercontent.com/88371717/231127826-41a65563-63ac-4c48-b723-c26f6a52998b.png)

Step 4: Set the `Caption` property in the property panel to blank and the icon disappears

![vfbe button with icon but no text](https://user-images.githubusercontent.com/88371717/231127904-21dac229-e386-466b-a897-deb9f608dc9c.jpg)

**Comment by XusinboyBekchanov** [comment]
Fixed: Setting Style property of CommandButton:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/c2b3c87ffeaf4c0b57e1ce885be3c6b3dd78e10e
