### ISSUE TITLE
Collapsing an item in the property grid causes artifacts

### ISSUE THREAD

**Issue by W98X** [XusinboyBekchanov/VisualFBEditor#519]
When clicking to collapse an item in the property grid there are artifacts as shown:

![VFBE property grid collapse artifact2](https://user-images.githubusercontent.com/88371717/233852802-7aec8a1d-8f10-418e-86fd-b79ca5689fba.png)

Video:

https://user-images.githubusercontent.com/88371717/233853281-7484021c-3c8e-4198-9f5b-2ce710aa8596.mp4

**Comment by XusinboyBekchanov** [comment]
Fixed: Collapsing TreeListView:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/e05b76a97673bc2faa1b6f0d64b62b62181b7aa3

Is this being fixed now?
