### ISSUE TITLE
Change StartPosition Property of Form from DefaultLocation to CenterScreen issue

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/VisualFBEditor#527]
The process of reproducing problems

1. Start a new GUI Application,
2. Change StartPosition Property of Form from DefaultLocation to CenterScreen,
3. Form disappears from the Form Designer.

Please check if this is the case

**Comment by XusinboyBekchanov** [comment]
Fixed: Set StartPosition of Form on Design mode:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/72ea570d83b5002fb6c0af3875c295423d1d888b

**Comment by chunmingwang** [comment]
> Fixed: Set StartPosition of Form on Design mode: [XusinboyBekchanov/MyFbFramework@72ea570](https://github.com/XusinboyBekchanov/MyFbFramework/commit/72ea570d83b5002fb6c0af3875c295423d1d888b)

Thank you for your prompt response.
After testing, it has been resolved.
