### ISSUE TITLE
Removal of Project files failed if the file does not exists

### ISSUE THREAD

**Issue by rexxitall** [XusinboyBekchanov/VisualFBEditor#53]
I renamed main.bas to x.bas.
I want to change the project to keep it in order.
Even main.bas does not exists anymore on the drive it could not be removed.
On project load the files should be checked if they exists.
non existing ones should be marked as not found.
And of course it should be possible to get rid of them without edit the project file with a text editor :)

**Comment by XusinboyBekchanov** [comment]
I changed the icon for missing files. But when I deleted the missing file from the project, I did not have any problems. Maybe there is some kind of problem invisible to me. Please try this test version. When you click on the Remove Files from Project, the execution line of this function appears. Then I can see the problem line.
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/63cfec06694041390c4d9092f6d4d1fcf74cdf29

**Comment by XusinboyBekchanov** [comment]
You just need to compile IDE in console mode to see the messages.
