### ISSUE TITLE
Save file failure!

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/VisualFBEditor#532]
Please take a look at the issueI have encountered
Problem recurrence process

1. New Project
2. Select any of control from toolbox
3. Draw selected control add to Form
4. Prompt following "Save file failure!" message

![image](https://github.com/XusinboyBekchanov/VisualFBEditor/assets/35757455/8c0847dd-02db-4903-82dc-7fa7c96ce5ab)

**Comment by XusinboyBekchanov** [comment]
Update TabWindow.bas:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/b9c8b69e7bdfcef286e7585735d35314143c8ae6

After that, there will be no creation of a bak file when inserting and deleting controls.

Why can't you save the bak file to the specified location on your computer?

**Comment by chunmingwang** [comment]
> Why can't you save the bak file to the specified location on your computer?

I don't know either.
Is it because the path identifier has both "\" and "/"?

**Comment by chunmingwang** [comment]
> > Why can't you save the bak file to the specified location on your computer?
> 
> I don't know either. Is it because the path identifier has both "\" and "/"?

I found the problem because there is no .\Temp directory after unzip VisualFBEditor-master.zip
After manually adding the  .\Temp directory, there was no prompt for 'Save file failure!'

**Comment by XusinboyBekchanov** [comment]
Added: Temp folder:
https://github.com/XusinboyBekchanov/VisualFBEditor/tree/master/Temp

**Comment by chunmingwang** [comment]
Thanks!
