### ISSUE TITLE
Icon overlap on Control, Procedure dropdown lists

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/VisualFBEditor#535]
![image](https://github.com/XusinboyBekchanov/VisualFBEditor/assets/35757455/248e0598-ea99-49b7-9d7d-98151192674d)

**Comment by XusinboyBekchanov** [comment]
What version of Windows?
Windows 10 (1809) or (1903)?

**Comment by chunmingwang** [comment]
> What version of Windows? Windows 10 (1809) or (1903)?

Version of Windows

`Microsoft Windows [Version 10.0.19045.2965]`

**Comment by XusinboyBekchanov** [comment]
Does it fix it?
https://github.com/XusinboyBekchanov/MyFbFramework/commit/dbdd5328c3aa802188ddde1ea3d139177293ca31

**Comment by chunmingwang** [comment]
> Does it fix it? [XusinboyBekchanov/MyFbFramework@dbdd532](https://github.com/XusinboyBekchanov/MyFbFramework/commit/dbdd5328c3aa802188ddde1ea3d139177293ca31)

no, still the same.

**Comment by XusinboyBekchanov** [comment]
After this change, the program itself should draw the ComboBoxEx, and the program has some indentation for the text in the ProcessMessage at this location: https://github.com/XusinboyBekchanov/MyFbFramework/blob/dbdd5328c3aa802188ddde1ea3d139177293ca31/mff/ComboBoxEx.bas#LL677C28-L677C50

And the program enters at start in this place?
https://github.com/XusinboyBekchanov/MyFbFramework/blob/dbdd5328c3aa802188ddde1ea3d139177293ca31/mff/ComboBoxEx.bas#L788

**Comment by chunmingwang** [comment]
I do not use argument `-gen gas64` to compile VisualFBEditor64, then VisualFBEditor64 is normal.

```
"F:\OfficePC_Update\!FB\FreeBASIC-1.10.0-winlibs-gcc-9.3.0\fbc64.exe" "VisualFBEditor.bas" "VisualFBEditor.rc" -i "../Controls/MyFbFramework" -x "../VisualFBEditor64.exe" -s gui -v
```

![image](https://github.com/XusinboyBekchanov/VisualFBEditor/assets/35757455/7f69c492-f85e-4c03-94c2-0247c269e824)

**Comment by XusinboyBekchanov** [comment]
Removed -gen gas64 from VisualFBEditor project file:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/9c4f28585c51ff072351aa02347f478f0365f6e5

Returned ComboBoxEx to previous state:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/e3aa95787e09ad8382b04d0dc9554befbde0a188

Removed -gen gas64 from MyFbFramework project file:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/86bc6cc8216563c116d416df5c1c6b913d663dc2
