### ISSUE TITLE
Hint of hotkeys on the toolbar button does not match to the Options setting

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/VisualFBEditor#536]
For example on Save All menu is: Ctrl+Alt+Shift+S, match to hotkeys Options setting.

![1684914203401](https://github.com/XusinboyBekchanov/VisualFBEditor/assets/35757455/4be88ee6-e36a-4991-a0e5-ed61f91ee400)

Hint of hotkeys on the toolbar Save All button is: Shift+Ctrl+S, does not match to the setting.

![1684914366313](https://github.com/XusinboyBekchanov/VisualFBEditor/assets/35757455/4091f424-8884-499c-935b-66e60f5f0848)

**Comment by XusinboyBekchanov** [comment]
Fixed:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/705abb0846dea0d075d83a546de90dd482f96f31

Thanks.

**Comment by chunmingwang** [comment]
I see SaveAll hint changed.
I suggest the Hint of toolbar button follow to the options Shortcuts settings like menuitem instead of fixed constants in the code.

toobar button
```
	tbStandard.Buttons.Add tbsAutosize, "New", , @mClick, "New", , ML("New") & " (Ctrl+N)", True
	tbStandard.Buttons.Add , "Open",, @mClick, "Open", , ML("Open") & " (Ctrl+O)", True
	tbtSave = tbStandard.Buttons.Add(, "Save", , @mClick, "Save", , ML("Save") & "..." & " (Ctrl+S)", True, 0)
	tbtSaveAll = tbStandard.Buttons.Add(, "SaveAll", , @mClick, "SaveAll", , ML("Save &All") & " (Shift+Ctrl+S)", True, 0)
	tbtSaveAll = tbStandard.Buttons.Add(, "SaveAll", , @mClick, "SaveAll", , ML("Save &All") & " (Ctrl+Alt+Shift+S)", True, 0)
	tbStandard.Buttons.Add tbsSeparator
	tbtUndo = tbStandard.Buttons.Add(, "Undo", , @mClick, "Undo", , ML("Undo") & " (Ctrl+Z)", True, 0)
	tbtRedo = tbStandard.Buttons.Add(, "Redo", , @mClick, "Redo", , ML("Redo") & " (Ctrl+Y)", True, 0)
```
menu item
```
	miCloseFolder = miFile->Add(ML("Close Folder") & HK("CloseFolder", "Alt+F4"), "", "CloseFolder", @mClick, , , False)
	miFile->Add("-")
	miSave = miFile->Add(ML("&Save") & "..." & HK("Save", "Ctrl+S"), "Save", "Save", @mClick, , , False)
	miSaveAs = miFile->Add(ML("Save &As") & "..." & HK("SaveAs"), "", "SaveAs", @mClick, , , False)
	miSaveAll = miFile->Add(ML("Save All") & HK("SaveAll", "Ctrl+Alt+Shift+S"), "SaveAll", "SaveAll", @mClick, , , False)
	miFile->Add("-")
	miClose = miFile->Add(ML("&Close") & HK("Close", "Ctrl+F4"), "Close", "Close", @mClick, , , False)
```

![1684978185326](https://github.com/XusinboyBekchanov/VisualFBEditor/assets/35757455/3de722ed-4cfb-4b36-9047-2e99a5847779)

**Comment by chunmingwang** [comment]
i change the "shortcut keys" to "hotkeys"

**Comment by XusinboyBekchanov** [comment]
Fixed:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/d37dc9486a99b27b893ce48b721eccd88be5e3a4

**Comment by chunmingwang** [comment]
Thank you for your quick feedback.
