### ISSUE TITLE
Use WinFBX library in VisualFBEditor

### ISSUE THREAD

**Issue by WillyAguilera1977** [XusinboyBekchanov/VisualFBEditor#539]
It is possible to use Jose Roca WinFBX library in VisualFBEditor?

**Comment by XusinboyBekchanov** [comment]
Yes, can use.

**Comment by WillyAguilera1977** [comment]
I have a problem with Jose Roca WinFBX library.
I have a test project that uses ADO.
When compiling it shows me these errors:

15:58:25: Compilation: "C:\Programacion\WinFBE_Suite\toolchains\FreeBASIC-1.10.0-winlibs-gcc-9.3.0\fbc64.exe"  -b "frmMain.frm" -exx -v  -s console -i "C:\Programacion\VisualFBEditor\Controls\MyFbFramework" -i ".\Controls\MyFbFramework\inc" -p ".\Controls\MyFbFramework\Lib" -d _DebugWindow_=133082

15:58:25: FreeBASIC Compiler - Version 1.10.0 (2023-05-14), built for win64 (64bit)
15:58:25: Copyright (C) 2004-2023 The FreeBASIC development team.
15:58:25: standalone 
15:58:25: target :       win64, x86-64, 64bit
15:58:25: backend :      gcc
15:58:25: compiling :    frmMain.frm -o frmMain.c (main module)
C:\Programming\WinFBE_Suite\toolchains\FreeBASIC-1.10.0-winlibs-gcc-9.3.0\inc\Afx\AfxAdo.bi(850) error 4: Duplicated definition, found 'Delete' in 'DECLARE ABSTRACT FUNCTION Delete_ (BYVAL Index AS VARIANT) AS HRESULT'
C:\Programming\WinFBE_Suite\toolchains\FreeBASIC-1.10.0-winlibs-gcc-9.3.0\inc\Afx\AfxAdo.bi(1004) error 4: Duplicated definition, found 'Delete' in 'DECLARE ABSTRACT FUNCTION Delete_ (BYVAL AffectRecords AS AffectEnum = adAffectCurrent) AS HRESULT'
C:\Programming\WinFBE_Suite\toolchains\FreeBASIC-1.10.0-winlibs-gcc-9.3.0\inc\Afx\AfxAdo.bi(1076) error 4: Duplicated definition, found 'Delete' in 'DECLARE ABSTRACT FUNCTION Delete_ (BYVAL Index AS VARIANT) AS HRESULT'
C:\Programming\WinFBE_Suite\toolchains\FreeBASIC-1.10.0-winlibs-gcc-9.3.0\inc\Afx\CAdoDb\CAdoRecordset.inc(160) error 4: Duplicated definition, found 'Delete' in 'DECLARE FUNCTION Delete_ (BYVAL AffectRecords AS AffectEnum = adAffectCurrent) AS HRESULT'
C:\Programming\WinFBE_Suite\toolchains\FreeBASIC-1.10.0-winlibs-gcc-9.3.0\inc\Afx\CAdoDb\CAdoRecordset.inc(982) error 14: Expected identifier, found 'Delete' in 'PRIVATE FUNCTION CAdoRecordset.Delete_ (BYVAL AffectRecords AS AffectEnum = adAffectCurrent) AS HRESULT'
C:\Programming\WinFBE_Suite\toolchains\FreeBASIC-1.10.0-winlibs-gcc-9.3.0\inc\Afx\CAdoDb\CAdoRecordset.inc(984) error 215: Only static members can be accessed from static functions and parameter initializers, found 'm_pRecordset' in 'IF m_pRecordset THEN RETURN(SetResult(m_pRecordset->Delete_(AffectRecords)))'
C:\Programming\WinFBE_Suite\toolchains\FreeBASIC-1.10.0-winlibs-gcc-9.3.0\inc\Afx\CAdoDb\CAdoRecordset.inc(984) error 215: Only static members can be accessed from static functions and parameter initializers, found 'm_pRecordset' in 'IF m_pRecordset THEN RETURN(SetResult(m_pRecordset->Delete_(AffectRecords)))'
C:\Programming\WinFBE_Suite\toolchains\FreeBASIC-1.10.0-winlibs-gcc-9.3.0\inc\Afx\CAdoDb\CAdoRecordset.inc(984) error 3: Expected End-of-Line, found 'm_pRecordset' in 'IF m_pRecordset THEN RETURN(SetResult(m_pRecordset->Delete_(AffectRecords)))'
C:\Programming\WinFBE_Suite\toolchains\FreeBASIC-1.10.0-winlibs-gcc-9.3.0\inc\Afx\CAdoDb\CAdoRecordset.inc(985) warning 13(1): Function result was not explicitly set
C:\Programming\WinFBE_Suite\toolchains\FreeBASIC-1.10.0-winlibs-gcc-9.3.0\inc\Afx\CAdoDb\CAdoFields.inc(385) error 4: Duplicated definition, found 'Delete' in 'DECLARE FUNCTION Delete_ (BYREF cvIndex AS CVAR) AS HRESULT'
C:\Programming\WinFBE_Suite\toolchains\FreeBASIC-1.10.0-winlibs-gcc-9.3.0\inc\Afx\CAdoDb\CAdoFields.inc(500) error 14: Expected identifier, found 'Delete' in 'PRIVATE FUNCTION CAdoFields.Delete_ (BYREF cvIndex AS CVAR) AS HRESULT'
C:\Programming\WinFBE_Suite\toolchains\FreeBASIC-1.10.0-winlibs-gcc-9.3.0\inc\Afx\CAdoDb\CAdoFields.inc(500) error 133: Too many errors, exiting

15:58:26: Found Errors (11 Pos), Warnings (1 Pos)
15:58:26: Do not build file. Elapsed Time: 1,08 Seconds

When I compile with PaulSquires WinFBE no error occurs.
This is the project:
[Test.zip](https://github.com/XusinboyBekchanov/VisualFBEditor/files/11727550/Test.zip)

**Comment by WillyAguilera1977** [comment]
This is the Paul Squires WinFBE project that works perfect
[TestWinFBE.zip](https://github.com/XusinboyBekchanov/VisualFBEditor/files/11728044/TestWinFBE.zip)

**Comment by XusinboyBekchanov** [comment]
Changed: FBMemCheck:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/d775119c112391162dc3f01b6661db5c33af15d0

Changed: FBMemCheckAssist:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/8db7f371ffd3b87de3e3ef3ec81f38a34dc16bd0

Now this include file is also compiled.
