### ISSUE TITLE
Feature Request: Insert new file in Project

### ISSUE THREAD

**Issue by rexxitall** [XusinboyBekchanov/VisualFBEditor#54]
To just add a new empty file into a Project is painful.
First you create a "normal" file, then you save it with a new name. First you has to walk to the project... Then you remove and close it. And now finally you can walk with the Fille add button.
I suggest to have a button - add "empty" file to project, get asked for a filename and then the file will be created in the prject folder, added to the project and shown in the editor. Additional it would be nice to have something named add file from template to project :) Here the user is been asked to choose a file from the project template folder. Useful on includes or cause there has to be a gpl header or... :)

**Comment by XusinboyBekchanov** [comment]
This is done too:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/abf963a4af7e5edc9f608a831f655808ec23f717
