### ISSUE TITLE
TextBox - property Maxlength

### ISSUE THREAD

**Issue by piripallo** [XusinboyBekchanov/VisualFBEditor#546]
hi, 
vfbe vers. 1.2.3.1926 
Using textbox property maxlength has no effect.
best regards.

**Comment by XusinboyBekchanov** [comment]
Fixed: TextBox MaxLength property:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/9935362df1e5433e899467b8bdf917f501c8a887

Thanks.

**Comment by piripallo** [comment]
Thank You very much.

Il 1 agosto 2023 04:18:40 CEST, Xusinboy Bekchanov ***@***.***> ha scritto:
>Fixed: TextBox MaxLength property:
>https://github.com/XusinboyBekchanov/MyFbFramework/commit/9935362df1e5433e899467b8bdf917f501c8a887
>
>Thanks.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/XusinboyBekchanov/VisualFBEditor/issues/546#issuecomment-1659462695
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Inviato dal mio dispositivo Android con K-9 Mail. Perdonate la brevità.

**Comment by XusinboyBekchanov** [comment]
Problem solved.
