### ISSUE TITLE
Suggestions for finding and replacing

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/VisualFBEditor#552]
Using find next/find previous goto the location that needs to be replaced.
Replace the text then find back to 1st found. suggested find goto to the find next.

**Comment by chunmingwang** [comment]
Find selected "procedure",
at this point, using "replace all" will replace the entire file text instead of limiting it to the procedure where the cursor is located.

**Comment by XusinboyBekchanov** [comment]
>Find selected "procedure",
>at this point, using "replace all" will replace the entire file text instead of limiting it to the procedure where the cursor is located.

Fixed: Replacing in procedure:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/eaf546e178bf214813c2d63a2c86832da99087a3

>Using find next/find previous goto the location that needs to be replaced.
>Replace the text then find back to 1st found. suggested find goto to the find next.

I'll watch this again.

**Comment by chunmingwang** [comment]
Thanks!

**Comment by XusinboyBekchanov** [comment]
>Using find next/find previous goto the location that needs to be replaced.
>Replace the text then find back to 1st found. suggested find goto to the find next.

Fixed: Replacement one by one:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/a48a9916d2b91ddb801cdf18e8d7511df3f3fb9b

**Comment by chunmingwang** [comment]
Thanks,
If I don't need to replace one by one, I can't use find next to skip it up.

**Comment by XusinboyBekchanov** [comment]
Fixed: Find and Replace:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/c57d4a792fffa185b7bb983c5d4ddf640cf6b951

**Comment by chunmingwang** [comment]
Thanks!
