### ISSUE TITLE
Bug or Feature ? Breadcrumb help inside a functiob or sub

### ISSUE THREAD

**Issue by rexxitall** [XusinboyBekchanov/VisualFBEditor#56]
if a sub or function gets edited a help bubble is shown. But only if you eneters a NEW "(" brace. if the mouse moves out this help vanish forever. Those define help bubbles should be shown as long the function or sub call is edited :) It is very unhandy to remove and add a brace for this purpose :)

**Comment by XusinboyBekchanov** [comment]
When you move the mouse, the tooltip does not close. If you move the caret to another line then it closes.

**Comment by rexxitall** [comment]
the problem is that i want to see it until i finished my changes :) Its way to hard to bring it back. It should close if i leave the area of the sub or function. And for sure there should be a setting and icon to easy deactivate and reactivate tooltips at all :)

**Comment by XusinboyBekchanov** [comment]
Added: Complete Word and Parameter Info buttons to IDE ToolBar:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/bf54014c0edcc5755791ca9999a0f053baf366de
