### ISSUE TITLE
Feature Request: Snippets

### ISSUE THREAD

**Issue by LimpingNinja** [XusinboyBekchanov/VisualFBEditor#561]
In VSCode the concepts of "Snippets" is used as a template that is predefined (usually in JSON) is pasted into the code editor and where the $1,$2,$3, etc. variable substitutions equal tab-stops, giving you the ability to add a template that can be "filled in" rapidly. These also show up in "autocomplete" fields as options to select and allow for rapid and consistent typing.

Example:
```json
	"Creates a for loop":{
		"prefix": "for",
		"body": [
			"For ${1:iterator} = ${2:startvalue} To ${3:endvalue}",
			"\t$4",
			"Next $1"
			],
		"description": "Creates a for loop"
	},
```

Would paste

```basic
For iterator = startvalue To endvalue

Next iterator
```

With the first location "iterator" being highlighted for overwrite, so I would type "i" which replaces both the iterator there and the one at bottom, and press TAB which then highlights startvalue to overwrite so I type "0" and press tab to highlight endvalue and type "10" then tab once more which puts me in the center of the code block ready to code.

```basic
For i = 0 To 10
    (cursor is here)
Next i
```

https://code.visualstudio.com/docs/editor/userdefinedsnippets - Example, see animated first Gif.

**Comment by XusinboyBekchanov** [comment]
Yes, we will add this soon, thanks for the suggestion.

**Comment by XusinboyBekchanov** [comment]
Added: Snippets in Linux:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/ce2df19c642604c315446622877b56afcce9867b

Now you can check.
