### ISSUE TITLE
How to implement NewIndex Property of ListControl (or ComboBox, ComboBoxEx)

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/VisualFBEditor#572]
Following NewIndex Property is type as ListBox (or ComboBox, ComboBoxEx) on VB6

```
List1.Sorted=True

For i = 0 To j
    List1.AddItem aa(i)
    List1.ItemData(List1.NewIndex) = i
Next
```

How to implement NewIndex or add it to VFBE ListControl (or ComboBox, ComboBoxEx, CheckedListBox)?

**Comment by XusinboyBekchanov** [comment]
Added: NewIndex property to CheckedListBox, ComboBoxEdit, ComboBoxEx and ListControl:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/0b3e94028b7484f44d03447b881805ada0642372
https://github.com/XusinboyBekchanov/MyFbFramework/commit/153d087efb300194fd94257f246ead90bfb4762e

**Comment by chunmingwang** [comment]
Thanks. i will try.

**Comment by chunmingwang** [comment]
Example of attached
[testListControl.zip](https://github.com/XusinboyBekchanov/VisualFBEditor/files/12994492/testListControl.zip)

if set ListControl1 Property Sort = true

![1697610999542](https://github.com/XusinboyBekchanov/VisualFBEditor/assets/35757455/a262d1f7-099d-470b-8588-7c0577720ad1)
Property Item(i) can access correct strValue
Property ItemData(i) can't access the correct ptrValue

**Comment by XusinboyBekchanov** [comment]
Fixed: AddItem method of ListControl:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/c6141517c26f65c81f60ade1927d259e4486d88b

**Comment by chunmingwang** [comment]
Thanks!
