### ISSUE TITLE
Examples\ChineseCalendar behaves in a wrong way

### ISSUE THREAD

**Issue by retsyo** [XusinboyBekchanov/VisualFBEditor#579]
I am using latest official `FreeBASIC-1.10.0-win64`, latest-cloned `https://github.com/XusinboyBekchanov/VisualFBEditor` and `https://github.com/XusinboyBekchanov/MyFbFramework`

I run `ChineseCalendar64.exe`, shrink the window size, drag it to right corner of my windows 10 64 bits. After a long time ~ 1 hour, I find that the digitals freeze. If I try to resize the window, I get the following window, i.e. the window does not scale up correctly so there is some black region. The author of `Examples\ChineseCalendar` and I think there is some memory leaks in `https://github.com/XusinboyBekchanov/MyFbFramework`
![bug](https://github.com/XusinboyBekchanov/VisualFBEditor/assets/7960913/8efd8553-3a39-449c-8f3f-75dfe6257ef5)

**Comment by XusinboyBekchanov** [comment]
Fixed: Memory Leaks of Canvas:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/4e8d3eb35251e7b05c1e167a569e2cce952adcc5

Improved: ChineseCalendar Example:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/d0f14725d939e6fbac0e343e9228ca533cb8545e

Thanks.

**Comment by chunmingwang** [comment]
> I am using latest official `FreeBASIC-1.10.0-win64`, latest-cloned `https://github.com/XusinboyBekchanov/VisualFBEditor` and `https://github.com/XusinboyBekchanov/MyFbFramework`
> 
> I run `ChineseCalendar64.exe`, shrink the window size, drag it to right corner of my windows 10 64 bits. After a long time ~ 1 hour, I find that the digitals freeze. If I try to resize the window, I get the following window, i.e. the window does not scale up correctly so there is some black region. The author of `Examples\ChineseCalendar` and I think there is some memory leaks in `https://github.com/XusinboyBekchanov/MyFbFramework` ![bug](https://private-user-images.githubusercontent.com/7960913/286918097-8efd8553-3a39-449c-8f3f-75dfe6257ef5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MTE2NDQsIm5iZiI6MTcwMTQxMTM0NCwicGF0aCI6Ii83OTYwOTEzLzI4NjkxODA5Ny04ZWZkODU1My0zYTM5LTQ0OWMtOGYzZi03NWRmZTYyNTdlZjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDFUMDYxNTQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjYzODY4YmZmZjRlMzA5NjI5M2FiMThkM2IxMTNiOTdlNDZjYWFhMWE2OWFlNWRhNzlhYjczMzIzZGE4ODZlZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._zzQ0xFwWrvme1OqHUXLzrgxWm1DgU3cwXsrHLPzIh0)

Yes, I have discovered this issue sometimes either,
But I can't find the root cause of the issue.

**Comment by chunmingwang** [comment]
> Fixed: Memory Leaks of Canvas: [XusinboyBekchanov/MyFbFramework@4e8d3eb](https://github.com/XusinboyBekchanov/MyFbFramework/commit/4e8d3eb35251e7b05c1e167a569e2cce952adcc5)
> 
> Improved: ChineseCalendar Example: [d0f1472](https://github.com/XusinboyBekchanov/VisualFBEditor/commit/d0f14725d939e6fbac0e343e9228ca533cb8545e)
> 
> Thanks.

I wrote a sample code to test Canvas.
Please see as attachment.
The issue can still be reproduced after running a long time

[testCanvas.zip](https://github.com/XusinboyBekchanov/VisualFBEditor/files/13522285/testCanvas.zip)

```
Private Sub Form1Type.TimerComponent1_Timer(ByRef Sender As TimerComponent)
	Dim dt As String = Format(Now, "yyyy-mm-dd hh:mm:ss")
	Dim w As Integer = Canvas.TextWidth(dt)
	Dim h As Integer = Canvas.TextHeight(dt)
	Canvas.Brush.Color = &h404040
	Canvas.Pen.Color = &hff0000
	Canvas.Line 0, 0, ClientWidth, ClientHeight, &h0 , "F"
	Canvas.TextOut((ClientWidth - w) / 2 , (ClientHeight - h) / 2, dt, &hff00, &H808080)
End Sub
```

**Comment by hustbeef** [comment]
Yes. The control did not consider the image as background and now add this fuction. and we must change the default backcolor to the third color like blue apply to all control  and testing. The  default forecolor should testing the same also.

**Comment by hustbeef** [comment]
I run the TestCanvas32.EXE after a while it is slow down my laptop now.

**Comment by hustbeef** [comment]
Before using the Cavas, You must add the code  Canvas.HandleSetted = True
					Canvas.Handle = Dc     
and ending with  Canvas.HandleSetted = False.
The Question is : How to stop this happe?  Or default add this code inn cancas like GetDevice , ReleaseDevice

**Comment by XusinboyBekchanov** [comment]
Fixed: Memory Leaks in Canvas:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/ff36fad843b805726b2a6518dfe194be973586d6

**Comment by hustbeef** [comment]
So o need to add the code Canvas.HandleSetted = True Before using the Cavas? Or it must be

**Comment by XusinboyBekchanov** [comment]
Updated: Canvas.bas
https://github.com/XusinboyBekchanov/MyFbFramework/commit/e4dbd10215321ffcf4159c5641c5b0f38bc82d9a

>So no need to add the code Canvas.HandleSetted = True Before using the Cavas? Or it must be

In Timer you can do this:
```
Private Sub Form1Type.TimerComponent1_Timer(ByRef Sender As TimerComponent)
	Dim As Any Ptr CanvasHandle = Canvas.GetDevice
	Canvas.HandleSetted = True
	Dim dt As String = Format(Now, "yyyy-mm-dd hh:mm:ss")
	Dim w As Integer = Canvas.TextWidth(dt)
	Dim h As Integer = Canvas.TextHeight(dt)
	Canvas.Brush.Color = &h404040
	Canvas.Pen.Color = &hff0000
	Canvas.Line 0, 0, ClientWidth, ClientHeight, &h0 , "F"
	Canvas.TextOut((ClientWidth - w) / 2 , (ClientHeight - h) / 2, dt, &hff00, &H808080)
	Canvas.HandleSetted = False
	Canvas.ReleaseDevice CanvasHandle
End Sub
```

**Comment by XusinboyBekchanov** [comment]
In the Paint event, the library itself sets Canvas.Handle, Canvas.HandleSetted = True and Canvas.HandleSetted = False, that is, there is no need to set this in this event.
In other, non-Paint cases, you can call the Repaint method of the desired control.

**Comment by XusinboyBekchanov** [comment]
I will see from this place whether there is a leak of GDI objects or not:
![image](https://github.com/XusinboyBekchanov/VisualFBEditor/assets/32607344/5bc9868d-87ef-40bf-8622-945473544ac1)

If there is a leak of GDI objects then the number of GDI objects increases, when the number reaches 10,000, then the program will start drawing incorrectly.

Now I will see the number of GDI objects at the beginning and until the end of the program it shows only one number - 25.

**Comment by hustbeef** [comment]
There is a blink after updated the seconds in frmClock. Could you please help this no blink even updated every 10 mSec.
the Repaint need to improve also.

	```
Private Sub Control.Repaint
			#ifdef __USE_GTK__
				If GTK_IS_WIDGET(widget) Then gtk_widget_queue_draw(widget)
			#elseif defined(__USE_WINAPI__)
				If FHandle Then
					'If Parent->ClassName <> "Picture" AndAlso Parent->ClassName <> "Panel" Then
					'If ClassName <> "Picture" AndAlso ClassName <> "Panel" Then
						RedrawWindow FHandle, 0, 0, RDW_INVALIDATE Or RDW_ALLCHILDREN
						Update
					'Else
					'	ShowWindow(FHandle, SW_HIDE)
					'	ShowWindow(FHandle, SW_SHOW)
					'End If
				End If
			#endif 
```

**Comment by XusinboyBekchanov** [comment]
>There is a blink after updated the seconds in frmClock. Could you please help this no blink even updated every 10 mSec.

This doesn't appear to me.
Only when you click on the Month calendar there is a blink.

>the Repaint need to improve also.

What change do you propose?

**Comment by XusinboyBekchanov** [comment]
>There is a blink after updated the seconds in frmClock. Could you please help this no blink even updated every 10 mSec.

Improved: Clock of Chinese Calendar Example:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/78598f35e82d4ed37a3ccc34852cdf328141e79b

Now try it.

**Comment by hustbeef** [comment]
The ChineseCalendar and Clock a very good Examples which working in all OS and we can improve the APP Examples and move to MyFbFramework.  Like LED nnumber?

**Comment by hustbeef** [comment]
Not  must be.  But it is better for a clock.
![image](https://github.com/XusinboyBekchanov/VisualFBEditor/assets/52040833/216d90cf-008f-4a51-b274-3ced404caec2)
QT have a control QLCDNumber. It is easy for us also.

**Comment by hustbeef** [comment]
But it must be running under OS Linux.

**Comment by XusinboyBekchanov** [comment]
Yes, you can add. To work on Linux, you need to add #ifdef to the Chinese Calendar example where WinAPI is used.

**Comment by hustbeef** [comment]
Have a small bar after hide the caption. but is the same even the picture1.Top=-5  
![image](https://github.com/XusinboyBekchanov/VisualFBEditor/assets/52040833/c8efe717-f480-415e-a844-9dd7c50f4f3a)

**Comment by XusinboyBekchanov** [comment]
This is what mine looks like:
![image](https://github.com/XusinboyBekchanov/VisualFBEditor/assets/32607344/31836989-520b-4c88-b53c-a59da5de10cd)

**Comment by retsyo** [comment]
if possible, please add more features in https://digitalclock4.sourceforge.io/ (which is in QT, as a result, has a big file size) or https://www.appinn.com/ct-clock/ (which is in ASM and for windows only, but has not been updated for a very long time)
- portable and setting is save in local file, since there is no Windows Registry in Linux/Mac OSX
- alarm on user defined time with selected sound file
- theme/skin

thanks

**Comment by hustbeef** [comment]
We need everyone to join in and add some functionality to the code, not just send the request.

**Comment by XusinboyBekchanov** [comment]
>Yes, the small bar has a different color, so we can change the backcolor to match Picture1.backcolor. Another solution is to draw on the forms.

This doesn't bother me because it's an OS decoration. Some people like it and some don't.

>This example has a lot of functions. Now we need localized functions. So it is better to move the sub ML() to SysUtils.bas or create a new type Language?

We can add it as a separate file or in SysUtils as you said.

>We need everyone to join in and add some functionality to the code, not just send the request.

I agree with you.

**Comment by XusinboyBekchanov** [comment]
>Have a small bar after hide the caption in high DPI screen. but is the same even the picture1.Top=-5

This is how you can hide it:

Improved: ChineseCalendar Example Hide Caption function:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/54cf0a9d373ff0a69a8cbb1099a9eef858d2ba9a

**Comment by chunmingwang** [comment]
![1701856503466](https://github.com/XusinboyBekchanov/VisualFBEditor/assets/35757455/f1b1ba3f-9f39-431b-891c-21700952d09e)

**Comment by XusinboyBekchanov** [comment]
Are you using Transparent and TransparentColor?

**Comment by chunmingwang** [comment]
> Are you using Transparent and TransparentColor?

Yes, I have corrected the Transparent option and add Opacity option.

**Comment by chunmingwang** [comment]
Update PR
https://github.com/XusinboyBekchanov/VisualFBEditor/pull/581

**Comment by chunmingwang** [comment]
I think the Memory Leaks of Canvas can be closed
