### ISSUE TITLE
Feature request or bug: Error windows closes automatically

### ISSUE THREAD

**Issue by rexxitall** [XusinboyBekchanov/VisualFBEditor#58]
During the work task to fix syntax errors it is not always handy that the compiler errors which are shown gets closed.
There should be a "pin" or a checkbox, so it stay open even if the user edit code. Otherwise you has to compile again just to get this window back.

**Comment by XusinboyBekchanov** [comment]
You can double-click on the tab. Then the window does not close

**Comment by rexxitall** [comment]
Ho the user should know it ? could you put a pinacle icon or something like this ? Double click on a tab is not very intuitive :)

**Comment by XusinboyBekchanov** [comment]
I added pin to toolwindows:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/feca4d7290e489cd863be6a573e337675f140370
