### ISSUE TITLE
Find next, previous counting error

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/VisualFBEditor#589]
1. open bassaudio example
2. ctrl+f open find child window
3. input "Form" in find text box
4. click find previous or find next
5. find index on 17 counting is 50
6. find index on 22 counting is 55

![vfbe find](https://github.com/XusinboyBekchanov/VisualFBEditor/assets/35757455/b9385d2c-3066-4c25-ab78-6c4939a641dc)

**Comment by XusinboyBekchanov** [comment]
Fixed: Finding:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/92704edb28fc0ace872892630d5fdb5663429bc0

**Comment by hustbeef** [comment]
Fixed: It is not add the boolean of Match Case. I post the code.

**Comment by chunmingwang** [comment]
Thanks!
