### ISSUE TITLE
Form Desinger Toolbar turn to black

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/VisualFBEditor#595]
Problem phenomenon

![image](https://github.com/XusinboyBekchanov/VisualFBEditor/assets/35757455/8c6b477e-d003-4411-8b68-507d7cc415f4)

Problem reproduction method
1. open Example\MDIForm\MDIForm.vfp
2. open MDIMain.frm - Toolbar normal
3. open MDIList.frm
4. click the tab to swith designer between MDIMain and MDIList 
5. discovered the issue of the toolbar turning black

![toolbarblack](https://github.com/XusinboyBekchanov/VisualFBEditor/assets/35757455/7aecb042-6eb6-4c65-b921-bff4c616d45e)

**Comment by XusinboyBekchanov** [comment]
Try with the latest changes, this only happened with the 64-bit version, I don't have that problem now.

**Comment by chunmingwang** [comment]
Thanks for reply.

Add more information on my environment for reference.

1. I am using vfbe64, Windows [Version 10.0.19045.3930].
2. vfbe and mff are compile with FreeBASIC-1.10.1-winlibs-gcc-9.3.0.

**Comment by XusinboyBekchanov** [comment]
Fixed: Form Designer Toolbar turn to black:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/ce836abb2fbdffc7c7df1f420edd1b126310bccd

**Comment by chunmingwang** [comment]
Thanks!
