### ISSUE TITLE
Menu Editor crash

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/VisualFBEditor#596]
Problem reproduction method

1. open attached testMenu Project1.vfp
2. open Form1
3. open Form2
4. Right click PopupMenu1 to Menu Editor
5. close Menu Editor
6. switch bettwen Form1 and Form2
7. Repeat steps 4 to 6
8. Some times Right click PopupMenu1 can't popup ContextMenu
9. Some times start Menu Editor and crash

[testMenu.zip](https://github.com/XusinboyBekchanov/VisualFBEditor/files/13885286/testMenu.zip)

**Comment by XusinboyBekchanov** [comment]
I couldn't catch this situation, it works fine for me.

**Comment by chunmingwang** [comment]
Thanks for reply.

Add more information on my environment for reference.
1. I am using vfbe64, Windows [Version 10.0.19045.3930].
2. vfbe compile with FreeBASIC-1.10.1-winlibs-gcc-9.3.0.
3. Yes the problem I was description upon, it's not stable happen every time.

**Comment by XusinboyBekchanov** [comment]
Will this solve this problem?

Fixed: Visible property of Control:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/5bc4b1b269578256f192d5b64a49dccdb00918d3

Improved: Menu Editor:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/f659368f508e39b89410f4c55c0c3e4a82b51be0

>After this update of [ce836ab](https://github.com/XusinboyBekchanov/VisualFBEditor/commit/ce836abb2fbdffc7c7df1f420edd1b126310bccd), the issue of Menu Editor crashes has become even more difficult to detect.
Will it also solve this problem?

May be.

**Comment by chunmingwang** [comment]
i don't meet the Menu Editor crash issue any more.

**Comment by chunmingwang** [comment]
[testMenu.zip](https://github.com/XusinboyBekchanov/VisualFBEditor/files/13944198/testMenu.zip)

Reopened this topic,

try following stree test for menu/toolbar/statusbar eiditor

1. open attached testMenu Project1.vfp
2. open Form1
3. open Form2
4. Right click PopupMenu1 to Menu Editor
5. Do some edit for menu
6. Closed menu eidtor
7. Right click Toolbar1 to Toolbar Editor
8. Do some edit for toolbar
9. Closed toolbar editor
10. Right click StatusBar1 ti Statusbar Editor
11. Dom some edit for statusbar
12. Closed statusbar edit
13. switch bettwen Form1 and Form2
14. Repeat steps 4 to 13

Some times start Menu/Toolbar/Statusbar Editor and crash

**Comment by XusinboyBekchanov** [comment]
Fixed: Crash Menu Editor:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/63b4c83afbae703ee0e77404134edb7bc36cb9b9

Now try it.

**Comment by chunmingwang** [comment]
Thanks.
the Menu/Toolbar/Statusbar Editor crash not happen at my environment and my test script any more.
