### ISSUE TITLE
Bug - Indenter / formatter  indet code whie is comented out

### ISSUE THREAD

**Issue by rexxitall** [XusinboyBekchanov/VisualFBEditor#60]
The formatter indents code which was comented out . I will provide a sample later.

**Comment by XusinboyBekchanov** [comment]
I fixed this:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/9c4d7900ec156410a6b988bb6be1522723caa911

**Comment by rexxitall** [comment]
works :)
