### ISSUE TITLE
Need click  2 times form Find expand to Replace dialog

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/VisualFBEditor#606]
Problem reproduction method

1. ctl+f to popup Find dialog
2. click Find Next or Find Previous
3. then need click  2 times expand to Replace dialog

**Comment by hustbeef** [comment]
Ctrl+H to open the Replace dialog

**Comment by hustbeef** [comment]
OH. found the bug. Click the btnReplaceShow button twice then switch to the Replace dialog.

**Comment by XusinboyBekchanov** [comment]
Fixed: Expand to Replace dialog by hustbeef:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/49ffa618ce59654334c48cf9c063f085be3e9d81

**Comment by chunmingwang** [comment]
Thanks hustbeef & XusinboyBekchanov.
btnReplaceShow click is normal.

**Comment by chunmingwang** [comment]
1. when the Find/Replace dialog was displayed,
2. back to code editor, used hot key Ctrl+F (or Ctrl+H) to active the Find ( or Replace) dialog,
3. should show Find (or Replace) dialog, but now it's:
4. if showing Find dialog  then the dialog will changed to Replace.
5. if showing Replace dialog  then the dialog will changed to Find.

**Comment by XusinboyBekchanov** [comment]
This was corrected by hustbeef:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/244e2f6841c7f4a0bd3d6e60c329ac6c360eafe0

**Comment by chunmingwang** [comment]
Thanks hustbeef & XusinboyBekchanov.
