### ISSUE TITLE
Form property ShowCaption=False not working

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/VisualFBEditor#607]
Problem reproduction method

1. start a new GII application
2. set ShowCaption=False
3. save project
4. start with compile
5. the application runs, Form still shows caption

**Comment by XusinboyBekchanov** [comment]
Fixed: Form ShowCaption property:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/0c53cb044c28e49b37916cc39c39f5596a116325

**Comment by chunmingwang** [comment]
Thanks. property ShowCaption=False is fixed.
