### ISSUE TITLE
Feature request - closing a project with unved files

### ISSUE THREAD

**Issue by rexxitall** [XusinboyBekchanov/VisualFBEditor#61]
I just was stopin working for today and wants to close a proect. During debug a lot of files was open. i got several times the dialog "do you want to save the  file" and yes no cancel. The missing thing was the "save the damn bullshit complete" button  :) So "YES ALL NO NOTHING  CANCEL " would be the prefered buttons

**Comment by XusinboyBekchanov** [comment]
It's done:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/169c9ba40ee0e3d03ff88b37d9ba79130f946687

**Comment by XusinboyBekchanov** [comment]
This added:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/4d51c4a91be6e30ae590d3628a2dd692c92cbb88

![image](https://user-images.githubusercontent.com/32607344/114868190-15a89580-9e0f-11eb-8ddd-96eab98554e5.png)
