### ISSUE TITLE
Two clicks on `Add-ins...` lead to IDE crash.

### ISSUE THREAD

**Issue by kaixinol** [XusinboyBekchanov/VisualFBEditor#614]
![image](https://github.com/XusinboyBekchanov/VisualFBEditor/assets/100816732/93479178-da1d-4fe2-92b7-5a12bdad6b26)

**Comment by XusinboyBekchanov** [comment]
Fixed: Export of MsgBox function:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/8a29c4af98afbfdc000035011b71ddd4aa2459f3

Fixed: Crash IDE when opening Add-ins:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/b87682a3b156a17d7f9bf2c7cc3d9ddd0da85975
