### ISSUE TITLE
Feature request: Display type hints when hovering over variables, constants, class names, etc

### ISSUE THREAD

**Issue by kaixinol** [XusinboyBekchanov/VisualFBEditor#618]
![image](https://github.com/XusinboyBekchanov/VisualFBEditor/assets/100816732/56601c35-e7e3-48f8-a6e2-56a9a4bf2553)
![image](https://github.com/XusinboyBekchanov/VisualFBEditor/assets/100816732/dbecf5d1-be08-410f-bc11-489d49cb565e)

And automatic variable type inference functionality

**Comment by XusinboyBekchanov** [comment]
Added: Display type hints when hovering over variables, constants, class names, etc:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/af7be326b4f1a5f273508398b3558d91738ce60c

Improved: Display type hints when hovering over variables, constants, class names, etc:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/20b5a3388b3b9682b24cb180098bd2047f835be1

**Comment by hustbeef** [comment]
Got the wrong position on a High DPI screen. The scale should be applied.

**Comment by XusinboyBekchanov** [comment]
>Got the wrong position on a High DPI screen. The scale should be applied.

Fixed:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/39adee7f497ae4335efe942279f0a48dd9f032ce

**Comment by hustbeef** [comment]
The position display is fine, but the words appear incorrectly on a High DPI screen. The scaling should be adjusted.

**Comment by XusinboyBekchanov** [comment]
>The position display is fine, but the words appear incorrectly on a High DPI screen. The scaling should be adjusted.

Show a picture of what the problem is in high resolution.

**Comment by hustbeef** [comment]
![image](https://github.com/XusinboyBekchanov/VisualFBEditor/assets/52040833/9a50b83c-73b7-42de-b67e-0b958c946ed3)
It shows that only Y is not OK. X is OK.

**Comment by XusinboyBekchanov** [comment]
>It shows that only Y is not OK. X is OK.

Fixed: Display type hints when hovering over variables, constants, class names, etc:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/6695bdfd70a38698388370e9a365829fe5f3ba75

**Comment by hustbeef** [comment]
There are 2 items not closed after scrolling through the code window with the mouse or moving the scrollbar.
![image](https://github.com/XusinboyBekchanov/VisualFBEditor/assets/52040833/6d4fba5d-e21c-4e22-bed8-aaf3c977f330)

**Comment by XusinboyBekchanov** [comment]
>There are 2 items not closed after scrolling through the code window with the mouse or moving the scrollbar.

Improved: Display type hints when hovering over variables, constants, class names, etc:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/2e02f192ca330cde3e1f36c3072b5bdd2c0d6818

**Comment by hustbeef** [comment]
ToolTip does not close when IDE lost focus or move mouse to another APP.

**Comment by XusinboyBekchanov** [comment]
>ToolTip does not close when IDE lost focus or move mouse to another APP.

Fixed: Closing tooltips:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/584ece781416eb80377a7a9f4a5b0f63d57404eb
