### ISSUE TITLE
The IDE do not take care which project has to be compiled

### ISSUE THREAD

**Issue by rexxitall** [XusinboyBekchanov/VisualFBEditor#62]
The IDE just compiles the first project which is loaded. It will also continue to compile only this project if the project is closed. Desired behaviour should be that the project which has the cursor in the project window or if some file open the project which file is shown to the user. If nothing can be deteced automatically the IDE should show a requester with a list and let the user choose :)

**Comment by XusinboyBekchanov** [comment]
Have you tried the Set As Main to the project?

**Comment by rexxitall** [comment]
yes. sure in both projects and that should be enough :) A unloaded or closed project do not even has a main form. its just not loaded - so how the IDE gets the idea to compile it ? . At least i as stupid user would assume (as long there is no more clever thing like in VS), that the thing will be compile which he already work on.

**Comment by XusinboyBekchanov** [comment]
Like this you need to set the project as the main one.
![image](https://user-images.githubusercontent.com/32607344/86429368-c4f4ff80-bd08-11ea-9016-fb137e246b60.png)

**Comment by XusinboyBekchanov** [comment]
Here in VB6 there is also the same.
![image](https://user-images.githubusercontent.com/32607344/86429715-ca067e80-bd09-11ea-8dc7-67ef3cb59056.png)

**Comment by hustbeef** [comment]
Later I will upload the updated code for SetAsMain. Remember MainNode always is a Pointer of root node. SetAsMain could set main .bas and .rc file.

**Comment by XusinboyBekchanov** [comment]
In my opinion, we should make different menu items for the root node and for the rest as in VB6.

**Comment by rexxitall** [comment]
VBA and VB6 are nearly same :) In fact they use the same engine. Just the hull looks slightly different. And VBA was stripped down not to canibalise VB6. MS could make a Vb6 clone immediatly. But then they would see that noone wants to use VB.Net anymore :D I think that is the real reason they do not do it. They have a working vb6 Engine which is 64 bit. They use them as VBA. But thats another story

**Comment by XusinboyBekchanov** [comment]
I added Bold style to Startup Project as VB6 and VBA.
