### ISSUE TITLE
Combobox problem, problems with display type hints and problems with searchbars

### ISSUE THREAD

**Issue by WillyAguilera1977** [XusinboyBekchanov/VisualFBEditor#622]
There is a problem with the control selection combobox. it is drawn badly

![combobox problem](https://github.com/XusinboyBekchanov/VisualFBEditor/assets/106629173/a1df5d8a-bf18-47c5-98ae-982706e3386a)

**Comment by WillyAguilera1977** [comment]
There are errors with SearchBar of properties
and with the search, it gives incorrect results. Sometimes the IDE crashes when searching or positioning the mouse cursor on a property

**Comment by WillyAguilera1977** [comment]
Sorry my english

**Comment by WillyAguilera1977** [comment]
The properties window is displayed incorrectly when closing a project.

![problem with properties tab](https://github.com/XusinboyBekchanov/VisualFBEditor/assets/106629173/ae33cee9-0370-4bd3-ab7d-a7330f047bda)

**Comment by XusinboyBekchanov** [comment]
>There is a problem with the control selection combobox. it is drawn badly

You are currently compiling with fbc 1.10.0 or fbc 1.10.1 with the -gen gas64 switch.
To solve this problem, you need to compile with the -gen gcc switch or compile with the latest version of the compiler (1.20.0 from 28.01.2024)

**Comment by XusinboyBekchanov** [comment]
>The properties window is displayed incorrectly when closing a project.

This also depends on the previous problem, fixed.

**Comment by XusinboyBekchanov** [comment]
>Sorry my english.
>### Problems with display type hints
>the display type hints is sometimes displayed incorrectly. For example, moving the mouse over a property or method displays the data of a subroutine declaration.

This may also depend on the previous problem, try with the latest changes.

**Comment by XusinboyBekchanov** [comment]
>Sorry my english.
>### Problems with display type hints
>the display type hints is sometimes displayed incorrectly. For example, moving the mouse over a property or method displays >the data of a subroutine declaration.

Fixed: Display type hints when hovering over variables, constants, class names, etc:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/6695bdfd70a38698388370e9a365829fe5f3ba75

**Comment by hustbeef** [comment]
![image](https://github.com/XusinboyBekchanov/VisualFBEditor/assets/52040833/5a3c7ce4-c560-4ff5-80a7-d5a99722bce6)
The search box is missing when the width of the property windows is reduced.  It is better add a searching ico there????

**Comment by hustbeef** [comment]
![image](https://github.com/XusinboyBekchanov/VisualFBEditor/assets/52040833/f2af258e-bc8e-49cf-b9ae-4638d4610f34)
This happened on a High DPI screen.

**Comment by XusinboyBekchanov** [comment]
>This happened on a High DPI screen.

Fixed: Properties and Events Window SearchBar in High DPI:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/ad11b7f312c72bd7cc3c2a519584d8136922e5d5

>It is better add a searching ico there????

Yes, if we add an icon, it will be better.
