### ISSUE TITLE
ToolBar Button not display complted on MDINotpad example

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/VisualFBEditor#633]
After this update, i found the Toolbar is abnormal on MDINotepad example 
https://github.com/XusinboyBekchanov/MyFbFramework/commit/075823529ee2339cb4d0b566aec9afdb8449984e

Normal:
![image](https://github.com/XusinboyBekchanov/VisualFBEditor/assets/35757455/af470b0c-84f0-45e3-9267-241a2f3320b9)

Abnormal (ToolBar Button not display complted):
![image](https://github.com/XusinboyBekchanov/VisualFBEditor/assets/35757455/486f5367-9267-4af7-a4e0-0eb95e48eee2)

**Comment by XusinboyBekchanov** [comment]
Fixed: ToolButton Width property:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/48de7020b06d85a83a89ccd9eb92740631f6fde7

**Comment by chunmingwang** [comment]
Thanks.
