### ISSUE TITLE
Dark mode fails in windows 8.1 

### ISSUE THREAD

**Issue by elfsimulate** [XusinboyBekchanov/VisualFBEditor#640]
version: 1.3.6.1218
neither the view menu darkmode menu nor the darkmode  button in toolbar is not working in windows 8.1

**Comment by XusinboyBekchanov** [comment]
Dark mode only works on Windows 10 and higher:
![image](https://github.com/XusinboyBekchanov/VisualFBEditor/assets/32607344/acfd2f3a-4530-4ca7-9ecf-dde516379d9c)
