### ISSUE TITLE
something missing for the com wrapper . As well as at leas some tiny documentation or sample

### ISSUE THREAD

**Issue by rexxitall** [XusinboyBekchanov/VisualFBEditor#65]
![image](https://user-images.githubusercontent.com/22050310/89523275-e30bbf00-d7e2-11ea-8ae5-b65dc38da458.png)

**Comment by XusinboyBekchanov** [comment]
Here on the forum also created a topic.
https://freebasic.net/forum/viewtopic.php?f=8&t=28739

You are right, need to do the documentation.

**Comment by XusinboyBekchanov** [comment]
Added Readme.doc:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/f73adf291048d3daaaa3428079ead5f7f0b62e90
