### ISSUE TITLE
build broken

### ISSUE THREAD

**Issue by rexxitall** [XusinboyBekchanov/VisualFBEditor#67]
Hi, i updated last myfbframework, compile it (successful), copy it in the VFBEditor folder like usually and try to start to build the project with the 1.25 working version from august. Seems the new memcheck function has broken things.
![image](https://user-images.githubusercontent.com/22050310/103145483-e96fe880-473b-11eb-9cb3-baa007721834.png)

**Comment by XusinboyBekchanov** [comment]
You, in my opinion, are compiling with the old library

**Comment by XusinboyBekchanov** [comment]
The new version of MyFbFramework has FBMemCheck.bi

**Comment by XusinboyBekchanov** [comment]
Here you need to specify the new library:
![image](https://user-images.githubusercontent.com/32607344/103164716-99268280-4830-11eb-9c79-5ece64c76403.png)

**Comment by rexxitall** [comment]
That is a nice idea. Even i think that the bug might be located inside the conditional define system. I could not see the desired functions been exported by the mff dll. And by this it will look as if the old lib is included. That i have checked. The lib has the checkmem.bi in the right place. The file is also included by the project.  But if its functions not get exported ( i use  windows )  it will look as if its missing. mff builds without errors but the Editor fails. 
![image](https://user-images.githubusercontent.com/22050310/103170507-fe846e80-4844-11eb-8780-6ced7b4bad40.png) As you can see it looks quite normal.

**Comment by XusinboyBekchanov** [comment]
You are compiling VisualFBEditor with library version 1.2.5. Compiling the library is not required to compile VisualFBEditor. All libraries are included in VisualFBEditor with sources. Therefore, exported functions are not needed either.
