### ISSUE TITLE
RC file located issue at Compile All projects

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/VisualFBEditor#678]
RC file located issue at Compile All projects

1. open following vfbe projects.

```
Download/Download.vfp
DynamicControl/DynamicControl.vfp
FileBrowser/FileBrowser.vfp
gdipClock/gdipClock.vfp
```

2. set Download.vfp as start up project.
3. used [Build\Compile All] menu to start compile all projects.
4. all the project's RC file was created at Download directory.

![1715844776574](https://github.com/XusinboyBekchanov/VisualFBEditor/assets/35757455/f772e669-8acd-4215-a1d2-86dec1bee7fc)

Expect the generated RC file to be in the directory where the project is located.

**Comment by XusinboyBekchanov** [comment]
Fixed: RC file located issue at Compile All projects:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/7ba008a8fae3902126d92604e55c31166b490606

**Comment by chunmingwang** [comment]
Thanks for your quick respons.
