### ISSUE TITLE
Darkmode issue of MDIChild Scrollbar at MDIScintilla example

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/VisualFBEditor#679]
Darkmode issue of MDIChild Scrollbar at MDIScintilla example

See as screen shot as following:

Please help me solve it.

![1716254714743](https://github.com/XusinboyBekchanov/VisualFBEditor/assets/35757455/984c3e07-a310-417d-969f-e4542fea0189)

**Comment by chunmingwang** [comment]
Let me correct that Scrollbar is the part of Scintilla control in MDIChild

**Comment by XusinboyBekchanov** [comment]
Fixed:
Update Scintilla.bas:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/f5eabf9470c1bd561fe60c467d0a2f6654cb8943

**Comment by chunmingwang** [comment]
Thanks for your quick respons.
