### ISSUE TITLE
build broken

### ISSUE THREAD

**Issue by rexxitall** [XusinboyBekchanov/VisualFBEditor#68]
Build is still broken. I tryed to include the FBMemcheck file also additional. Does not work. On windows 64 bit it still fails. So please check the conditional compiler defines for this build target. Regards Thomas

**Comment by XusinboyBekchanov** [comment]
You are compiling VisualFBEditor with library version 1.2.5. Compiling the library is not required to compile VisualFBEditor. All libraries are included in VisualFBEditor with sources. Therefore, exported functions are not needed either.

**Comment by rexxitall** [comment]
By the way, someones which has no IDE of the editor will also have the problem not to know how to build the thing. Might be a idea to provide a batch file and a document on how to place the mff thing in the right place, where to get the right compiler and how to do a manaul build without the IDE/Editor. I am quite sure that a lot of peoples just will say, does not work and run away. That was already the case by a friend of me in summer. The damn thing was not been able to be build on his system.

**Comment by rexxitall** [comment]
Xusingboy how else i can compile the thing as with 1.2.5. I (and all other) have no other choice. I have to use 1.2.5 to build 1.2.6.  ! :D So either you provides a batch or whatever file or NO ONE will be able to see 1.2.6 ! Cause you are the only person in this universe which has a running 1.2.6 version which might can build the code. So how to build 1.2.6 with 1.2.5 or build from scratch (that should be in any case be included). As long you do not provide working binarys there must be a way tu build the thing just using fbc and nothing else :)

**Comment by XusinboyBekchanov** [comment]
I updated Readme.txt and added this:
#### Compilation:

To compile use the following command lines:

#### For Windows 32-bit:

  fbc "VisualFBEditor.bas" -x "../VisualFBEditor32.exe" "VisualFBEditor.rc" -i "Path_to_MyFbFramework"

#### For Windows 64-bit:

  fbc "VisualFBEditor.bas" -x "../VisualFBEditor64.exe" "VisualFBEditor.rc" -i "Path_to_MyFbFramework"

#### For Linux 32-bit:

  fbc "VisualFBEditor.bas" -x "../VisualFBEditor32_gtk3" -i "Path_to_MyFbFramework"

#### For Linux 64-bit:

  fbc "VisualFBEditor.bas" -x "../VisualFBEditor64_gtk3" -i "Path_to_MyFbFramework"

**Comment by XusinboyBekchanov** [comment]
>>I have to use 1.2.5 to build 1.2.6.
Here you can also specify the path to the new library:
-i "Path_to_MyFbFramework"

**Comment by XusinboyBekchanov** [comment]
Once you compiled by setting the path to the new library like this, then you forgot in my opinion:
![image](https://user-images.githubusercontent.com/32607344/103171085-1cfd6080-486b-11eb-8af9-1795807e7b05.png)

**Comment by XusinboyBekchanov** [comment]
This is where you compiled:
https://github.com/XusinboyBekchanov/VisualFBEditor/issues/17

**Comment by rexxitall** [comment]
here is the dll info i got by 1.2.6
File Type: WINDOWS EXECUTABLE

File Version Information:
  File Version:                  1.2.6.249
  Product Version:               1.2.6.0
  File Type:                     0x00000001 (Application)
  File Subtype:                  0x00000000
  File Flags Mask:               0x00000000
  File Flags:                    0x00000000
  String File Information:       1033 (Englisch (Vereinigte Staaten))
    CompanyName
    FileDescription:             My FreeBasic Framework
    FileVersion:                 1.2.6.249
    InternalName
    LegalCopyright
    OriginalFilename
    ProductName:                 MyFbFramework
    ProductVersion:              1.2.6

File Header:
  Machine:                       0x8664 (AMD64)
  Number of Sections:            20
  Time Date Stamp:               0x5FE87840 (27.12.2020 13:04:16)
  Pointer to Symbol Table:       0x001E5000
  Number of Symbols:             9599
  Size of Optional Header:       0x00F0 (240)
  Characteristics:               0x2026
    File is executable
    Line numbers stripped from file
    App can handle >2GB addresses
    File is a DLL

Optional Header:
  Magic:                         0x020B
  Linker Version:                2.25
  Size of Code:                  0x0009A600 (632320)
  Size of Initialized Data:      0x000B3200 (733696)
  Size of Uninitialized Data:    0x0000CA00 (51712)
  Address of Entry Point:        0x000013E0
  Base of Code:                  0x00001000
  Image Base:                    0x0000000010000000
  Section Align:                 0x00001000
  File Align:                    0x00000200
  Operating System Version:      4.0
  Image Version:                 0.0
  Subsystem Version:             5.2
  Size of Image:                 0x001FD000 (2084864)
  Size of Headers:               0x00000600 (1536)
  Checksum:                      0x0023216E
  Subsystem:                     0x0003 (Windows character subsystem)
  DLL Characteristics:           0x0000
  Size of Stack Reserve:         0x0000000000100000 (1048576)
  Size of Stack Commit:          0x0000000000100000 (1048576)
  Size of Heap Reserve:          0x0000000000100000 (1048576)
  Size of Heap Commit:           0x0000000000001000 (4096)
  Loader Flags:                  0x00000000
  Number of RVA and Sizes:       16

Data Directory:
  Export directory:               VA: 0x000B5000  Size: 0x00001A45 (6725)
  Import directory:               VA: 0x000B7000  Size: 0x00003590 (13712)
  Resource directory:             VA: 0x000BD000  Size: 0x00009024 (36900)
  Exception directory:            VA: 0x000A6000  Size: 0x000003CC (972)
  Security directory:             VA: 0           Size: 0
  Base relocation table:          VA: 0x000C7000  Size: 0x00000640 (1600)
  Debug directory:                VA: 0           Size: 0
  Architecture-specific data:     VA: 0           Size: 0
  RVA of global pointer:          VA: 0           Size: 0
  Thread local storage directory: VA: 0x000BC020  Size: 0x00000028 (40)
  Load configuration directory:   VA: 0           Size: 0
  Bound import directory:         VA: 0           Size: 0
  Import address table:           VA: 0x000B7CC8  Size: 0x00000BB0 (2992)
  Delay load import descriptors:  VA: 0           Size: 0
  COM run-time descriptor:        VA: 0           Size: 0
  (unknown directory entry):      VA: 0           Size: 0

Export Table:
  Name:                          mff64.dll
  Time Date Stamp:               0x5FE87840 (27.12.2020 13:04:16)
  Version:                       0.00
  Ordinal Base:                  1
  Number of Functions:           119
  Number of Names:               119

  Ordinal   Entry Point   Name
        1   0x00025F21    ApplicationFileName
        2   0x00025EF1    ApplicationMainForm
        3   0x000094AC    BitmapTypeLoadFromPNGResourceName
        4   0x0000738A    ComponentGetBounds
        5   0x000073CC    ComponentSetBounds
        6   0x00021A16    ControlByIndex
        7   0x00021A54    ControlByName
        8   0x00021ADB    ControlFreeWnd
        9   0x00030494    ControlIsContainer
       10   0x00021AC3    ControlSetFocus
       11   0x0007E113    CreateComponent
       12   0x0007C305    CreateControl
       13   0x0007EC0A    CreateObject
       14   0x00080092    DeleteAllObjects
       15   0x0007EEAB    DeleteComponent
       16   0x00021A8F    IsControl
       17   0x00015E41    MenuFindByName
       18   0x00015E7C    MenuItemAdd
       19   0x00015EE1    MenuItemAddWithBitmapType
       20   0x00015E06    MenuItemFindByName
       21   0x00015DA6    MenuItemItemsCount
       22   0x00015F46    MenuItemRemove
       23   0x00015DD6    MenuItemsCount
       24   0x00015F69    MenuRemove
       25   0x00025CCE    MsgBox
       26   0x0007FED1    ObjectDelete
       27   0x000219D0    QControl
       28   0x00007367    Q_Component
       29   0x000053FB    ReadProperty
       30   0x000219F3    RemoveControl
       31   0x00080118    ShowPropertyPage
       32   0x000053C4    ToString
       33   0x0006C8E4    ToolBarAddButtonWithImageIndex
       34   0x0006C974    ToolBarAddButtonWithImageKey
       35   0x0006CA2E    ToolBarIndexOfButton
       36   0x0006CA04    ToolBarRemoveButton
       37   0x0000543E    WriteProperty
       38   0x00053C97    _ZN2MY3SYS14COMPONENTMODEL7PRINTER11GETCHARSIZEERu7INTEGERS4_
       39   0x0005265A    _ZN2MY3SYS14COMPONENTMODEL7PRINTER11NAME__get__Ev
       40   0x00052614    _ZN2MY3SYS14COMPONENTMODEL7PRINTER11NAME__set__ER8FBSTRING
       41   0x000540F6    _ZN2MY3SYS14COMPONENTMODEL7PRINTER11ORIENTPRINTEi
       42   0x0005280B    _ZN2MY3SYS14COMPONENTMODEL7PRINTER11PAGE__get__Ev
       43   0x000527EA    _ZN2MY3SYS14COMPONENTMODEL7PRINTER11PAGE__set__Eu7INTEGER
       44   0x00054918    _ZN2MY3SYS14COMPONENTMODEL7PRINTER12CALCPAGESIZEERiS3_
       45   0x00052B1B    _ZN2MY3SYS14COMPONENTMODEL7PRINTER12SCALE__get__Ev
       46   0x000545F7    _ZN2MY3SYS14COMPONENTMODEL7PRINTER12TITLE__get__Ev
       47   0x000545B1    _ZN2MY3SYS14COMPONENTMODEL7PRINTER12TITLE__set__ER8FBSTRING
       48   0x0005371E    _ZN2MY3SYS14COMPONENTMODEL7PRINTER13CHOOSEPRINTEREv
       49   0x00052919    _ZN2MY3SYS14COMPONENTMODEL7PRINTER13COPIES__get__Ev
       50   0x00052880    _ZN2MY3SYS14COMPONENTMODEL7PRINTER13COPIES__set__Eu7INTEGER
       51   0x000530C9    _ZN2MY3SYS14COMPONENTMODEL7PRINTER13HANDLE__get__Ev
       52   0x00052AF1    _ZN2MY3SYS14COMPONENTMODEL7PRINTER13TOPAGE__get__Ev
       53   0x00052AD0    _ZN2MY3SYS14COMPONENTMODEL7PRINTER13TOPAGE__set__Eu7INTEGER
       54   0x0005334B    _ZN2MY3SYS14COMPONENTMODEL7PRINTER14DEFAULTPRINTEREv
       55   0x0005520D    _ZN2MY3SYS14COMPONENTMODEL7PRINTER14GETPRINTERPORTE8FBSTRING
       56   0x000529DA    _ZN2MY3SYS14COMPONENTMODEL7PRINTER14QUALITY__get__Ev
       57   0x00052943    _ZN2MY3SYS14COMPONENTMODEL7PRINTER14QUALITY__set__ENS1_14PRINTERQUALITYE
       58   0x00054302    _ZN2MY3SYS14COMPONENTMODEL7PRINTER14UPDATEMARGEINSEv
       59   0x00052AA6    _ZN2MY3SYS14COMPONENTMODEL7PRINTER15FROMPAGE__get__Ev
       60   0x00052A85    _ZN2MY3SYS14COMPONENTMODEL7PRINTER15FROMPAGE__set__Eu7INTEGER
       61   0x00055819    _ZN2MY3SYS14COMPONENTMODEL7PRINTER15GETPRINTERSCALEE8FBSTRING
       62   0x00052856    _ZN2MY3SYS14COMPONENTMODEL7PRINTER15PAGESIZE__get__Ev
       63   0x00052835    _ZN2MY3SYS14COMPONENTMODEL7PRINTER15PAGESIZE__set__Eu7INTEGER
       64   0x000526D7    _ZN2MY3SYS14COMPONENTMODEL7PRINTER15PORTNAME__get__Ev
       65   0x000526C8    _ZN2MY3SYS14COMPONENTMODEL7PRINTER15PORTNAME__set__ER8FBSTRING
       66   0x00052D55    _ZN2MY3SYS14COMPONENTMODEL7PRINTER16COLORMODE__get__Ev
       67   0x00052CC2    _ZN2MY3SYS14COMPONENTMODEL7PRINTER16COLORMODE__set__Ei
       68   0x00058462    _ZN2MY3SYS14COMPONENTMODEL7PRINTER16ENUMPRINTERPORTSEv
       69   0x00057BC9    _ZN2MY3SYS14COMPONENTMODEL7PRINTER16GETPRINTERDUPLEXE8FBSTRING
       70   0x0005326A    _ZN2MY3SYS14COMPONENTMODEL7PRINTER16MARGINTOP__get__Ev
       71   0x00053294    _ZN2MY3SYS14COMPONENTMODEL7PRINTER16MARGINTOP__set__Eu7INTEGER
       72   0x00052F22    _ZN2MY3SYS14COMPONENTMODEL7PRINTER16MAXCOPIES__get__Ev
       73   0x00053148    _ZN2MY3SYS14COMPONENTMODEL7PRINTER16PAGEWIDTH__get__Ev
       74   0x00056201    _ZN2MY3SYS14COMPONENTMODEL7PRINTER16SETPRINTERCOPIESE8FBSTRINGi
       75   0x00053FEC    _ZN2MY3SYS14COMPONENTMODEL7PRINTER17DUPLEXMODE__set__ENS1_17PRINTERDUPLEXMODEE
       76   0x0005321F    _ZN2MY3SYS14COMPONENTMODEL7PRINTER17MARGINLEFT__get__Ev
       77   0x00053249    _ZN2MY3SYS14COMPONENTMODEL7PRINTER17MARGINLEFT__set__Eu7INTEGER
       78   0x000531DE    _ZN2MY3SYS14COMPONENTMODEL7PRINTER17PAGEHEIGHT__get__Ev
       79   0x000549F9    _ZN2MY3SYS14COMPONENTMODEL7PRINTER17PRINTERPAPERNAMESE8FBSTRING
       80   0x0005752A    _ZN2MY3SYS14COMPONENTMODEL7PRINTER17SETPRINTERQUALITYE8FBSTRINGNS1_14PRINTERQUALITYE
       81   0x00057C3B    _ZN2MY3SYS14COMPONENTMODEL7PRINTER18GETPRINTERFROMPORTE8FBSTRING
       82   0x000532B5    _ZN2MY3SYS14COMPONENTMODEL7PRINTER18MARGINRIGHT__get__Ev
       83   0x000532DF    _ZN2MY3SYS14COMPONENTMODEL7PRINTER18MARGINRIGHT__set__Eu7INTEGER
       84   0x00054275    _ZN2MY3SYS14COMPONENTMODEL7PRINTER18ORIENTATION__get__Ev
       85   0x000541F2    _ZN2MY3SYS14COMPONENTMODEL7PRINTER18ORIENTATION__set__Ei
       86   0x00052D7B    _ZN2MY3SYS14COMPONENTMODEL7PRINTER19DRIVEVERSION__get__Ev
       87   0x000582CC    _ZN2MY3SYS14COMPONENTMODEL7PRINTER19GETPRINTERMAXCOPIESE8FBSTRING
       88   0x00053300    _ZN2MY3SYS14COMPONENTMODEL7PRINTER19MARGINBOTTOM__get__Ev
       89   0x0005332A    _ZN2MY3SYS14COMPONENTMODEL7PRINTER19MARGINBOTTOM__set__Eu7INTEGER
       90   0x00052BA8    _ZN2MY3SYS14COMPONENTMODEL7PRINTER19SCALEFACTORX__get__Ev
       91   0x00052C35    _ZN2MY3SYS14COMPONENTMODEL7PRINTER19SCALEFACTORY__get__Ev
       92   0x00055BD5    _ZN2MY3SYS14COMPONENTMODEL7PRINTER19SETPRINTERCOLORMODEE8FBSTRINGi
       93   0x00056EFE    _ZN2MY3SYS14COMPONENTMODEL7PRINTER19SETPRINTERPAPERSIZEE8FBSTRINGi
       94   0x00054DB1    _ZN2MY3SYS14COMPONENTMODEL7PRINTER20GETPRINTERPAPERSIZESE8FBSTRING
       95   0x0005303C    _ZN2MY3SYS14COMPONENTMODEL7PRINTER20MAXPAPERWIDTH__get__Ev
       96   0x0005682D    _ZN2MY3SYS14COMPONENTMODEL7PRINTER20SETPRINTERDUPLEXMODEE8FBSTRINGi
       97   0x00058E48    _ZN2MY3SYS14COMPONENTMODEL7PRINTER21GETDEFAULTPRINTERPORTEv
       98   0x000523C0    _ZN2MY3SYS14COMPONENTMODEL7PRINTER21GETPRINTERORIENTATIONE8FBSTRING
       99   0x000555BC    _ZN2MY3SYS14COMPONENTMODEL7PRINTER21GETPRINTERQUALITYMODEE8FBSTRING
      100   0x00052FAF    _ZN2MY3SYS14COMPONENTMODEL7PRINTER21MAXPAPERHEIGHT__get__Ev
      101   0x00052E08    _ZN2MY3SYS14COMPONENTMODEL7PRINTER21PRINTABLEWIDTH__get__Ev
      102   0x0005169B    _ZN2MY3SYS14COMPONENTMODEL7PRINTER21SETPRINTERORIENTATIONE8FBSTRINGi
      103   0x00058FFC    _ZN2MY3SYS14COMPONENTMODEL7PRINTER21SHOWPRINTERPROPERTIESEv
      104   0x00052E95    _ZN2MY3SYS14COMPONENTMODEL7PRINTER22PRINTABLEHEIGHT__get__Ev
      105   0x00058AE0    _ZN2MY3SYS14COMPONENTMODEL7PRINTER23GETDEFAULTPRINTERDEVICEEv
      106   0x00058C94    _ZN2MY3SYS14COMPONENTMODEL7PRINTER23GETDEFAULTPRINTERDRIVEREv
      107   0x00057B57    _ZN2MY3SYS14COMPONENTMODEL7PRINTER23GETPRINTERDRIVERVERSIONE8FBSTRING
      108   0x000583D4    _ZN2MY3SYS14COMPONENTMODEL7PRINTER23GETPRINTERMAXPAPERWIDTHE8FBSTRING
      109   0x0005833E    _ZN2MY3SYS14COMPONENTMODEL7PRINTER24GETPRINTERMAXPAPERHEIGHTE8FBSTRING
      110   0x00058218    _ZN2MY3SYS14COMPONENTMODEL7PRINTER28GETPRINTERVERTICALRESOLUTIONE8FBSTRING
      111   0x00058164    _ZN2MY3SYS14COMPONENTMODEL7PRINTER30GETPRINTERHORIZONTALRESOLUTIONE8FBSTRING
      112   0x00054877    _ZN2MY3SYS14COMPONENTMODEL7PRINTER6ENDDOCEv
      113   0x000539AF    _ZN2MY3SYS14COMPONENTMODEL7PRINTER7NEWFONTER8FBSTRINGiiii
      114   0x0005481F    _ZN2MY3SYS14COMPONENTMODEL7PRINTER7NEWPAGEEv
      115   0x000547FB    _ZN2MY3SYS14COMPONENTMODEL7PRINTER8ENDDPAGEEv
      116   0x00053D6E    _ZN2MY3SYS14COMPONENTMODEL7PRINTER8GETLINESEu7INTEGER
      117   0x00054665    _ZN2MY3SYS14COMPONENTMODEL7PRINTER8STARTDOCEv
      118   0x000547AF    _ZN2MY3SYS14COMPONENTMODEL7PRINTER9STARTPAGEEv
      119   0x0005907B    _ZN2MY3SYS14COMPONENTMODEL7PRINTERC1Ev

**Comment by rexxitall** [comment]
Thats how the files are organized: 
![image](https://user-images.githubusercontent.com/22050310/103171360-ee23c200-484b-11eb-95c9-38b39e93e83f.png)

**Comment by rexxitall** [comment]
this is the batch i use acc. your informations...
c:
cd "C:\FREEBASIC\PROJECTS\VisualFBEditor-master\src"
C:\FREEBASIC\X64\fbc.exe "VisualFBEditor.bas" -x "../VisualFBEditor64.exe" "VisualFBEditor.rc" -i "C:\FREEBASIC\PROJECTS\VisualFBEditor-master\MyFbFramework\mff"

**Comment by rexxitall** [comment]
and this i get... 
![image](https://user-images.githubusercontent.com/22050310/103171395-37741180-484c-11eb-9b49-506b951916cb.png)

**Comment by XusinboyBekchanov** [comment]
This is not needed here: "\mff"

**Comment by XusinboyBekchanov** [comment]
> here is the dll info i got by 1.2.6
> File Type: WINDOWS EXECUTABLE
> 
This is where they read it.
When compiling library, you need to specify the -dll switch.

**Comment by rexxitall** [comment]
Works :)
REM SAMPLE Windows 64 bit Build
REM CHANGE ACC. YOUR SETUP / PATHS
REM change path to the VisualFBEditor source
c:
cd "C:\FREEBASIC\PROJECTS\VisualFBEditor-master\src"

REM A Copy of the MyFbFramework was also placed to
REM "C:\FREEBASIC\PROJECTS\VisualFBEditor-master\MyFbFramework"

REM the 64bit FREEBASIC compiler is located in
REM "C:\FREEBASIC\X64\fbc.exe"
REM "Version 1.08.0 64bit Windows build"

REM BUILD COMMAND
C:\FREEBASIC\X64\fbc.exe "VisualFBEditor.bas" -x "../VisualFBEditor64.exe" "VisualFBEditor.rc" -i "C:\FREEBASIC\PROJECTS\VisualFBEditor-master\MyFbFramework"
might be a idea to put this as a sample
