### ISSUE TITLE
Crashing Bug

### ISSUE THREAD

**Issue by jwoff78** [XusinboyBekchanov/VisualFBEditor#69]
IDE keeps crashing on windows 10 for some reason, each time I save the project, open a new project, can't seem to save properly either functionality isn't working well.

**Comment by XusinboyBekchanov** [comment]
I can't grasp such a thing. Can you show me the procedure for such a crash.

**Comment by jwoff78** [comment]
i'll get you a video upload somehow, maybe unlisted yt video

**Comment by jwoff78** [comment]
https://youtu.be/dnftxcLgiiM here's the unlisted yt video

**Comment by XusinboyBekchanov** [comment]
This is in the new version corrected. You can try compiling from github:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/3b2fc8c668e3d88a54a5e5a49d64c35a9a2666a6

**Comment by jwoff78** [comment]
Appreciated! and what about the readonly on richtext box not selected that I noticed also and showed off, wasn't saving the setting.

**Comment by XusinboyBekchanov** [comment]
This is added now:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/03a66b5fddd170b65b905d7ba68f31f458617c06

**Comment by jwoff78** [comment]
Thanks!
