### ISSUE TITLE
compile  IDE, file not found

### ISSUE THREAD

**Issue by ssepan2** [XusinboyBekchanov/VisualFBEditor#70]
ERROR: (user info redacted)
`username@pcname:~/Github/VisualFBEditor/src$ fbc "VisualFBEditor.bas" -x "../VisualFBEditor64_gtk3" -i "/home/username/Github/VisualFBEditor/MyFbFramework"
/home/username/Github/VisualFBEditor/src/Main.bi(8) error 23: File not found, "mff/WStringList.bi""`

README.md: (instructions I used "For Linux 64-bit:")
`cd Path_to_VisualFBEditor/src`
`  fbc "VisualFBEditor.bas" -x "../VisualFBEditor64_gtk3" -i "Path_to_VisualFBEditor/MyFbFramework"
`

COMMAND: (run from src folder)
`fbc "VisualFBEditor.bas" -x "../VisualFBEditor64_gtk3" -i "/home/username/Github/VisualFBEditor/MyFbFramework"
`

**Comment by XusinboyBekchanov** [comment]
You also need the MyFbFramework:
https://github.com/XusinboyBekchanov/MyFbFramework

And put it in a folder:
/home/username/Github/VisualFBEditor/

**Comment by ssepan2** [comment]
Ah, I understand now. 
Reading the README.me, I took it ('My') to mean 'replace with your path to something in _my_ installation of something buried in  the IDE folder structure'.

I'll try again with the other repository in place. From your comment above, I read that it should be under the top folder of the editor(?) (Does that work OK with with both being clones of a github repository?)

Thanks

**Comment by XusinboyBekchanov** [comment]
Yes, it works.

**Comment by ssepan2** [comment]
Ah, I see it is in the .gitignore, of course.
OK, so setting that up and running again I get further:
`username@userpc:~/Github/VisualFBEditor/src$ fbc "VisualFBEditor.bas" -x "../VisualFBEditor64_gtk3" -i "/home/username/Github/VisualFBEditor/MyFbFramework"
ld: cannot find -lgtk-3
ld: cannot find -lgdk-3
`

**Comment by XusinboyBekchanov** [comment]
>>that was it; completed that step without error...continuing
Did it work?

**Comment by ssepan2** [comment]
When I opened it, it wanted to find fbc on /media/... 
Had to track down the copy I installed in /usr/... this morning, adn it seemed happy with the choice, so Yes, I think we can close the Issue.
Thanks!

**Comment by XusinboyBekchanov** [comment]
You could also just add the path as "fbc".

**Comment by ssepan2** [comment]
Good point; it IS in bin, after all.

**Comment by XusinboyBekchanov** [comment]
We will fix it in the next release

**Comment by XusinboyBekchanov** [comment]
For me, the path like fbc, works, it turns out.
