### ISSUE TITLE
IDE crashes if you close the only active editor window.

### ISSUE THREAD

**Issue by rexxitall** [XusinboyBekchanov/VisualFBEditor#73]
If i close this preset file the whole IDE crashes
![image](https://user-images.githubusercontent.com/22050310/117721007-a5a7e800-b1df-11eb-8c8f-4a40e5ad3ff3.png)

It would be nice to have a setup how to start.
Last used project, last used file, empty or with a template ... :)

**Comment by XusinboyBekchanov** [comment]
>>If i close this preset file the whole IDE crashes
I will open and close the tabs several times in a day, this will not happen to me.

Maybe you haven't downloaded the latest version of MyFbFramework.

>>It would be nice to have a setup how to start.
>>Last used project, last used file, empty or with a template ... :)
The settings have this:
![image](https://user-images.githubusercontent.com/32607344/117754516-ecbfc880-b233-11eb-8f10-971d8bd2064b.png)

You can choose how to proceed during the startup of VisuaFBEditor.

**Comment by rexxitall** [comment]
Thanks i haveve overseen that nice feature :)
