### ISSUE TITLE
Wrong path to mff DLL

### ISSUE THREAD

**Issue by rexxitall** [XusinboyBekchanov/VisualFBEditor#76]

**Comment by rexxitall** [comment]
Entering the mff DLL pAth in the textbox or after download and compile the project leads to a wrong setting 
![image](https://user-images.githubusercontent.com/22050310/118806979-069e8280-b8a8-11eb-8f7a-418f849eec2f.png)
The path is set correctly if you BROWSE by the Settings Browse Button to the dll

**Comment by XusinboyBekchanov** [comment]
Fixed: mff dll path on Load Toolbox:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/7c4410a76cd3768e3f211bb3ce6ec873ac6b3417
