### ISSUE TITLE
Missing Project type GUI

### ISSUE THREAD

**Issue by rexxitall** [XusinboyBekchanov/VisualFBEditor#78]
Might be a idea to add / change a entry  Executable Terminal, Executable GUI

![image](https://user-images.githubusercontent.com/22050310/118807544-bd026780-b8a8-11eb-88ab-35a33c402399.png)

**Comment by XusinboyBekchanov** [comment]
I control the Console/GUI from here:
![image](https://user-images.githubusercontent.com/32607344/118809170-b33a2d80-b8c3-11eb-85aa-2a825e9147e6.png)

**Comment by XusinboyBekchanov** [comment]
In VB6:
![image](https://user-images.githubusercontent.com/32607344/118809324-ea104380-b8c3-11eb-8c58-1784577f4710.png)

**Comment by XusinboyBekchanov** [comment]
New Project Prompt in VisualFBEditor:
![image](https://user-images.githubusercontent.com/32607344/118809400-07dda880-b8c4-11eb-8389-fc4d16dc19dc.png)

**Comment by rexxitall** [comment]
VB6 is nice but not the godmother of everything. You fall in the same pit like me. You seems to compile the IDE to console mode. And by this all your Tools has the black window in behind. Thats why i suggest to have all those things also in the project settings. Maybe add something like "Depends" for a random type :)  I think peoples may need to change such a compile target and do not want to first create a new project add files and so on ..
There should be also some kind of info WHICH setting is currently active :)

**Comment by demosthenesk** [comment]
i think Xusinboy Bekchanov, is better.
May be this issue can be closed.

**Comment by XusinboyBekchanov** [comment]
Added: Subsystem option to Project Properties:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/e75168f2baba45cf0535cfec79c96051ca85c64e

![image](https://user-images.githubusercontent.com/32607344/132513108-5e7e7fdc-4960-4b6a-976c-239bfd5feda6.png)

**Comment by XusinboyBekchanov** [comment]
Fixed: Resource file:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/ca302a7d91f55b3672a5ea7e686113a1d8d92038
