### ISSUE TITLE
Alt-C Open Command Prompt

### ISSUE THREAD

**Issue by rexxitall** [XusinboyBekchanov/VisualFBEditor#79]
Does not do anything

**Comment by rexxitall** [comment]
even after checking and set up "Terminal" settings

**Comment by rexxitall** [comment]
In the terminal settings or project settings it would be nice to define WHERE the terminal should be opened. curren Project, some Data Folder, ...

**Comment by rexxitall** [comment]
True, but would be nice to have in case you want to debug things located elsewhere. Aka Data files ;)

**Comment by XusinboyBekchanov** [comment]
Added: Options to Command Prompt:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/0a0dc9d73da839d836231abc01e7c491bcbda9cf

**Comment by demosthenesk** [comment]
In linux Command Options window... elements are one over the other...
![Screenshot from 2021-09-14 13-07-51](https://user-images.githubusercontent.com/1350282/133238954-5cc582dc-d0b3-40f3-b8f2-198a12edd9ce.png)

**Comment by XusinboyBekchanov** [comment]
Fixed: Command Prompt options in Linux:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/ee18e8bacccd8cabddd59b1ac35ff77317b7e7de

**Comment by demosthenesk** [comment]
> Fixed: Command Prompt options in Linux:
> [ee18e8b](https://github.com/XusinboyBekchanov/VisualFBEditor/commit/ee18e8bacccd8cabddd59b1ac35ff77317b7e7de)

fixed!
