### ISSUE TITLE
Trange view in GUI Explorer after fld and unfold

### ISSUE THREAD

**Issue by rexxitall** [XusinboyBekchanov/VisualFBEditor#80]
![image](https://user-images.githubusercontent.com/22050310/118809521-0784e380-b8ab-11eb-8261-97cdc09c308d.png)

**Comment by demosthenesk** [comment]
does this issue exist any more ?
i thought to clean some old issues.

**Comment by XusinboyBekchanov** [comment]
On Windows I use ToolBarWindow32 for ToolBox. I cannot improve it now.

**Comment by XusinboyBekchanov** [comment]
Improved: ToolPalette Group collapsed in Windows:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/10afec50385880a9ab631c2b3140a78b7088bd02

Improved: ToolBox collapsed state:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/06c8dfd24e587769bf5c9bd63d8db808d393ed6d

![image](https://user-images.githubusercontent.com/32607344/134314749-e95e154d-9bcc-439e-aed0-b929f9821397.png)
