### ISSUE TITLE
CheckBoxes do not allow changing their default check property and CheckBoxes cannot be checked if placed within GroupBoxes

### ISSUE THREAD

**Issue by TRSlimShaney** [XusinboyBekchanov/VisualFBEditor#82]
I am using VisualFBEditor 32-bit on 64-bit Windows 10.

CheckBoxes have a Checked property which allows the setting of the default state of the check box. While changing it in the editor seems to work and the RAD window shows it as being checked, running the compiled program results in an unchecked checkbox regardless of the initial property value. When the IDE is closed and reopened to the same project, the code still says the default state of the checkbox should be checked, however the RAD properties say the checkbox default checked state is false.
I have been able to get around this by having the AppOnCreate set the value of the checkbox manually.

CheckBoxes cannot be checked by mouse-click during runtime when placed inside of GroupBoxes at all. I have tried other containers such as Panels and the CheckBoxes work as expected there.

**Comment by XusinboyBekchanov** [comment]
The first part of the problem has been fixed:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/dbdbedbc4369b01efc7ef81cc31864d0f5ff64c8

I am working on the second problem.

**Comment by XusinboyBekchanov** [comment]
Second problem has been fixed too:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/3376127802a49fb70282b237377647e90c128383
