### ISSUE TITLE
Include Paths and Library Paths are not visible on gtk3 for linux

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#84]
Hello, i try VisualFBEditor on Ubuntu 20.04 LTS with gtk3.
The paths of Include and Library are not visible.
![Screenshot at 2021-07-18 03-26-53](https://user-images.githubusercontent.com/1350282/126052221-2b00275d-0359-4df7-80b0-d44b6807d22c.png)

**Comment by XusinboyBekchanov** [comment]
I fixed ListControl.AddItem procedure in Linux:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/6b879c3dabab84d8c5c050e72c6c58914a1e26e3

Previously, after showing the form, did not shows the newly added items in ListControl. After this fix, try adding a new item. Maybe the background of the ListBox you have is different.

**Comment by demosthenesk** [comment]
Ok now are visible.
However they are not read VisualFBEditorX64.ini and they are empty.
If i add or remove paths they are not updated.

**Comment by XusinboyBekchanov** [comment]
Have you compiled VisualFBEditor64_gtk3 again?

**Comment by demosthenesk** [comment]
> Have you compiled VisualFBEditor64_gtk3 again?

yes

**Comment by XusinboyBekchanov** [comment]
I am now fix double additions Include Path and Library Path:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/c4add3b91072d2fdf69f479989c833f678041f3b

It works fine:
https://user-images.githubusercontent.com/32607344/126073689-843b138b-92d2-48fb-9275-c77d4f48c2b5.mp4

**Comment by demosthenesk** [comment]
yes it is ok now.
Thanks!
