### ISSUE TITLE
There are two resources / Resources folders

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#85]
There are 2 folders with the name resources.
I copied the files from resources to Resources and delete resources and compile.
It works!

**Comment by XusinboyBekchanov** [comment]
Fixed: resources have been moved to Resources:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/44b703d7387b6df606cc71cfdc6c5273c9905eea
