### ISSUE TITLE
Cannot run console apps in Windows 10

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#86]
I have VisualFBEditor.1.2.9 with Include and Library Paths set up of FreeBASIC-1.08.1-win64.
I cannot run console apps on windows 10 64 bit. The cmd window is always blank.

How to reproduce bug:
1) From Menu "Service->Options->Compiler->Includes" uncheck "Include MFF Path"
2) From Menu "Service->Options->Compiler->Includes" add "Others" and "Library Paths" to 
a) C:\Users\User\Bin\FreeBasic\FreeBASIC-1.08.1-win64\inc
b) C:\Users\User\Bin\FreeBasic\FreeBASIC-1.08.1-win64\lib
3) Write a console bas like the following
-----------------------------------------------
#include "crt/stdlib.bi"

Dim i As Integer
i = abs_(-5)
Print i
Sleep
End
-----------------------------------------------
4) Compile the abs.bas. It gives the following output:
13:36:58: Compilation: ""C:\Users\User\Bin\FreeBasic\FreeBASIC-1.08.1-win64\fbc64.exe"  -b "abs.bas" -exx -v -Wc -gdwarf-2 -s gui -i "C:\Users\User\Bin\FreeBasic\FreeBASIC-1.08.1-win64\inc" -p "C:\Users\User\Bin\FreeBasic\FreeBASIC-1.08.1-win64\lib" 2> "C:\Users\User\Bin\FreeBasic\VisualFBEditor.1.2.9/Temp/Compile.log""

FreeBASIC Compiler - Version 1.08.1 (2021-07-05), built for win64 (64bit)
Copyright (C) 2004-2021 The FreeBASIC development team.
standalone
target:       win64, x86-64, 64bit
backend:      gcc
compiling:    abs.bas -o abs.c (main module)
compiling C:  C:\Users\User\Bin\FreeBasic\FreeBASIC-1.08.1-win64\bin\win64\gcc.exe -m64 -march=x86-64 -S -nostdlib -nostdinc -Wall -Wno-unused-label -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-main -Werror-implicit-function-declaration -O0 -fno-strict-aliasing -frounding-math -fno-math-errno -fwrapv -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables -Wno-format -masm=intel "abs.c" -o "abs.asm" -gdwarf-2 
assembling:   C:\Users\User\Bin\FreeBasic\FreeBASIC-1.08.1-win64\bin\win64\as.exe --64 --strip-local-absolute "abs.asm" -o "abs.o"
linking:      C:\Users\User\Bin\FreeBasic\FreeBASIC-1.08.1-win64\bin\win64\ld.exe -m i386pep -o "abs.exe" -subsystem windows -T "C:\Users\User\Bin\FreeBasic\FreeBASIC-1.08.1-win64\lib\win64\fbextra.x" --stack 2097152,2097152 -s -L "C:\Users\User\Bin\FreeBasic\FreeBASIC-1.08.1-win64\lib" -L "C:\Users\User\Bin\FreeBasic\FreeBASIC-1.08.1-win64\lib\win64" -L "." "C:\Users\User\Bin\FreeBasic\FreeBASIC-1.08.1-win64\lib\win64\crt2.o" "C:\Users\User\Bin\FreeBasic\FreeBASIC-1.08.1-win64\lib\win64\crtbegin.o" "C:\Users\User\Bin\FreeBasic\FreeBASIC-1.08.1-win64\lib\win64\fbrt0.o" "abs.o" "-(" -lfb -lgcc -lmsvcrt -lkernel32 -luser32 -lmingw32 -lmingwex -lmoldname -lgcc_eh "-)" "C:\Users\User\Bin\FreeBasic\FreeBASIC-1.08.1-win64\lib\win64\crtend.o" 

13:36:59: Layout succeeded!

5) Run the abs.exe with cmd
6) I get a blank cmd. Expected to get "5"
7) I tried to compile with poseidonEditor and it runs correctly

**Comment by demosthenesk** [comment]
i think the parameter of fbc -s gui is responsible for this

**Comment by XusinboyBekchanov** [comment]
Here's the console option:
![image](https://user-images.githubusercontent.com/32607344/126155893-53782f92-1edb-47c4-b915-b6a7efede2bb.png)

**Comment by demosthenesk** [comment]
OK ! I have learned something today, i did not noticed that there it was.
It works fine.
Thanks.
