### ISSUE TITLE
Syntax Check and Compile commands do not work with many files

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#87]
Hello, i have 2 bas files in a Project. main.bas, sum.bas
When i try to compile the project it calls fbc -b main.bas only and ommit other file(s)

23:30:28: Compilation: "/home/user/Bin/FreeBASIC-1.08.1-ubuntu-20.04-x86_64/bin/fbc" -b "main.bas" -exx -i "/home/user/Bin/FreeBASIC-1.08.1-ubuntu-20.04-x86_64/include/freebasic" -p "/home/user/Bin/FreeBASIC-1.08.1-ubuntu-20.04-x86_64/lib/freebasic/linux-x86_64" 2> "/home/user/Bin/VisualFBEditor.1.2.9.1/Temp/Compile.log"

check zip file with the project
[sum_project.zip](https://github.com/XusinboyBekchanov/VisualFBEditor/files/6858741/sum_project.zip)

**Comment by XusinboyBekchanov** [comment]
Added: Project Property: Pass All Module Files To Compiler:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/e7e62cdf33f552e196dd5bffc17e0153bce0f669

![image](https://user-images.githubusercontent.com/32607344/126591812-f7d50b61-f69e-42cd-a2bb-3053d0d88d44.png)

Previously, this was possible in three ways (Adding "sum.bas"):
1) Project Properties -> Compile -> Compilation Arguments
2) Main Menu -> Build -> Parameters -> fbc 32-bit or fbc 64-bit
3) At the beginning of the code main.bas '#Compile sum.bas

**Comment by demosthenesk** [comment]
ok fixed
thanks !
