### ISSUE TITLE
Property grid doesn't update to the control selected by the drop down

### ISSUE THREAD

**Issue by W98X** [XusinboyBekchanov/VisualFBEditor#90]
Hello,
WOW, VisualFBEditor is like a dream come true for Freebasic! 

For many years people thought it was impossible to create a proper GUI in Freebasic, but now with VisualFBEditor, its finally possible! This is what people have waited for so many years!

However, I have noticed some bugs. So here is one:

In the visual form designer, when a control is selected by the drop down combo box, the property grid doesn't update with the info for the newly selected control

![vfb-propertygrid-notupdate](https://user-images.githubusercontent.com/88371717/127983422-a5099f15-611e-4147-bf68-bc747bc93fa2.png)

**Comment by XusinboyBekchanov** [comment]
Thanks for the good review.

This has been fixed:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/a59dc48437d1ea926f742e8c4017311bdf2964e9

**Comment by W98X** [comment]
Yes it works now. Thanks.
