### ISSUE TITLE
Text box and rich-text editor controls can't be set to multi line

### ISSUE THREAD

**Issue by W98X** [XusinboyBekchanov/VisualFBEditor#91]
The Text box and rich-text editor controls can't be set to multi-line in the property grid. When I select multi-line, it reverts back to blank. 

Also, trying to set those controls to multiline in the code editor doesn't work either, because it gives an error when compiling.

Also can't enable scroll bars or word wrap for them in the property grid.

**Comment by XusinboyBekchanov** [comment]
This fixed:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/f61bfa6cc0a2cb20d3ee2764217f07d889beccfb

**Comment by W98X** [comment]
Yes it works now. Thanks. 😀
