### ISSUE TITLE
Visual form designer window can't be scrolled

### ISSUE THREAD

**Issue by W98X** [XusinboyBekchanov/VisualFBEditor#92]
If the form in the visual designer is bigger than the viewing area, there is no way to scroll to the parts of the form which go past the edge of the window.

![vfbe-no-scrollbars-form-designer](https://user-images.githubusercontent.com/88371717/128156687-6900a9bc-a467-4cad-9eab-d48e6fd404d2.png)

**Comment by XusinboyBekchanov** [comment]
This fixed:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/09fef7fe8bfe5ea5bd55fa5b48e3ae3de0c718a1

**Comment by W98X** [comment]
I tested it. When the viewing mode is set to "form" it is correct. 

However, there seems to be a problem when the viewing mode is set to "code + form" and both side panels are pinned open. The code editor seems to dissappear underneath the left side panel and the horizontal scroll bar becomes obscured underneath the left side panel or the scroll bar disappears completely, as shown in the picture below.
![vfbe-no-scrollbars-with-both-code-and-design](https://user-images.githubusercontent.com/88371717/128336770-523dad03-e348-4d46-9c33-c4405b5ee2f3.png)

I think the problem is caused by the splitter in-between the code editor and the form. If this splitter is dragged off to the left too far then then code editor dissappears completely. This splitter should stop when it reaches the left edge of the code viewer.

![vfbe-no-scrollbars-with-both-code-and-design-splitter-limits](https://user-images.githubusercontent.com/88371717/128336844-de7870a0-5e8c-4500-8fce-511fe76748ef.png)


Also I noticed that the viewing mode icons don't update to reflect the current viewing mode if I change the viewing mode in the "view" menu.
![vfbe-viewing-mode-menu-icon](https://user-images.githubusercontent.com/88371717/128337996-9f3e744c-8420-4622-9bb8-9a737fcc2835.png)

**Comment by XusinboyBekchanov** [comment]
Fixed: Splitter between the code view and form view stops when it reaches the left edge of the code view:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/f086b236286f454ccf781c3d684fc8cb08c59bd1

>>Also I noticed that the viewing mode icons don't update to reflect the current viewing mode if I change the viewing mode in the "view" menu.
How can they be updated there, are they just ordinary menus with an icon, without birds?

**Comment by W98X** [comment]
> How can they be updated there, are they just ordinary menus with an icon, without birds?

It's the buttons on the right above the code editor which don't update after the viewing mode has been set in the "view" menu.

In the screenshot below the buttons are still saying "form" view, even though the editor has been set to "code" view via the "View" menu:
![vfbe-viewing-mode-buttons-dont-update](https://user-images.githubusercontent.com/88371717/128477048-0f447b67-6cd7-4b26-8b15-3aca18f69626.png)

**Comment by XusinboyBekchanov** [comment]
Fixed: https://github.com/XusinboyBekchanov/VisualFBEditor/commit/87341b75d4df3ac20c432bdcaab02ee5031a4ca7

**Comment by W98X** [comment]
Yes, I tested it and it works. Thanks.
