### ISSUE TITLE
TextBox1_Change(ByRef Sender As TextBox) does not work as expected

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#94]
i have a Form1 and a TextBox1. I want when the textbox changes its text to print in console the TextBox1.Text
But it does not work. It seems that Change event is not trigered.

```
Private Sub Form1.TextBox1_Change(ByRef Sender As TextBox)
	Print TextBox1.Text
End Sub

```
See attached project
[formtest.zip](https://github.com/XusinboyBekchanov/VisualFBEditor/files/6947298/formtest.zip)
My system is Ubuntu Mate 20.04

**Comment by XusinboyBekchanov** [comment]
Added: TextBox changed event in Linux:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/3e8416dcb8761339dd6119921ef4a82922de52d5

**Comment by demosthenesk** [comment]
ok fixed.
Thanks!
