### ISSUE TITLE
Feature request: High DPI compatibility

### ISSUE THREAD

**Issue by W98X** [XusinboyBekchanov/VisualFBEditor#95]
Feature requesting that VisualFBEditor be made fully high-DPI compatible and also the exe's it compiles to be properly scaled at different high-DPI settings.

**Comment by XusinboyBekchanov** [comment]
What problems are there in high-DPI now?

**Comment by W98X** [comment]
It's not high-dpi aware like what Firefly and WinFBE are, so VisualFBEditor and exe's made by it appear fuzzy on a high DPI monitor.

Firefly and WinFBE do automatic scaling using "afxScale" functions so everything is scaled properly and automatically for all different DPI settings:

`SetWindowPos hWndControl, 0, afxScaleX(100), afxScaleY(100), afxScaleX(500), afxScaleY(250)`

**Comment by XusinboyBekchanov** [comment]
It works like this:
`TextBox1.SetBounds 80, 130, 170, 20, False`

**Comment by XusinboyBekchanov** [comment]
Added: __USE_DPI__ definition for DPI scaling in Windows:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/af3852c43130d4e827e39140b50e7b3c56c14068

**Comment by W98X** [comment]
Does this "setbounds" function mean that VisualFBEditor / MFF already has high-dpi scaling functions built in?

The problem is when I run an exe created with VisualFBEditor on a high-DPI monitor, it's GUI appears fuzzy. 

VisualFBEditor also appears fuzzy when viewed on a high DPI monitor.

It is not performing high-DPI scaling automatically.

So I am feature requesting that the high-DPI scaling be performed automatically.

**Comment by XusinboyBekchanov** [comment]
Do you check on Windows or Linux?

**Comment by W98X** [comment]
Windows

**Comment by W98X** [comment]
I have now tested it on Windows 10 with the monitor scaling set to 140% and recompiled mff and VisualFBEditor with added the following define to the top of **visualeditor.bas**:
`#define __USE_DPI__`

Then before running VisualFBEditor32.exe, I set the DPI compatibility mode as follows, so that Windows10 will allow VFBE to do it's own dpi scaling. This step is needed because VFBE doesn't automatically add the high-dpi metadata to the exe "manifest".
![vfbe-disablescaling-properties](https://user-images.githubusercontent.com/88371717/128593042-5b75fd4e-6466-4a47-b5c4-bf1ac361dfa4.PNG)

The end result was not good, as shown in the screenshot below. Notice how the 2nd combo box and viewing mode buttons above the form designer have disappeared. A white space has appeared under the toolbox and propertygrid tabs. And the 2nd column of the property grid has disappeared. And the project properties window has scaling errors:

![vfbe-disablescaling-properties-WITH-DPI-DEF](https://user-images.githubusercontent.com/88371717/128593095-34128b6f-52e5-4bd3-a111-aeec54a32841.png)

**Comment by XusinboyBekchanov** [comment]
Added: High DPI compatibility:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/d5d3e926e7acfc699be416c32b8f402614dafa24

Added: High DPI compatibility:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/6d647be19e490327dee836cadff2d9a0523620ac

**Comment by XusinboyBekchanov** [comment]
Added: High DPI Compatibility to MenuEditor, Designer and EditControl:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/67c327def032009ed7229548a3b4afeceacb9360

Added: High DPI compatibility to Canvas:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/cbcacab3d4c5bc01d400858ae4e7ea149ec27903

**Comment by W98X** [comment]
Wow!
I have tested it on Windows 10 at 140% scaling and now it looks so crisp and clear 😀  . No more fuzzyness, VisualFBEditor is now in HD!  😎 

And the exe's it compiles are now automatically high-dpi 👍 
Now I can make modern looking non-fuzzy high-dpi programs in Freebasic! 🥳 

This is a big improvement. Thank you very much.

However, I did notice a few small glitches, which are shown in the screenshots below.
1) There is grey rectangle appearing below the pins for both side panels, when they are pinned open.
2) When the side panels are unpinned, the sideways text on the side-tabs appears wrong
![vfbe-pinbutton-dpi-error](https://user-images.githubusercontent.com/88371717/128642776-8cc77eb6-aa68-4880-896d-46401b2039cc.png)
![vfbe-sidetabs-unpinned-sideways-text](https://user-images.githubusercontent.com/88371717/128642779-f8f41ad0-0ad1-48dd-8224-4abe5e07d3b0.png)

**Comment by XusinboyBekchanov** [comment]
Fixed: Pin buttons in DPI:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/37c98f644103932fc50acb804172d3304a9f9d59

Fixed: TabControl DPI:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/77f3bf38ac027e007a5ab01136b1a0f1bb68112e

**Comment by W98X** [comment]
Yes, it's fixed now.
Thanks.
