### ISSUE TITLE
Cannot run compiled app if there are spaces in project path

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#96]
If i have a bas file in a directory which contains spaces,  it been compiled ok but it fails to run the executable in linux

**Comment by XusinboyBekchanov** [comment]
I check it in the evening when I am at home (Linux is in my home).

**Comment by XusinboyBekchanov** [comment]
Fixed: Run compiled app if there are spaces in project path (Linux):
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/519db3bc0efc9c9118b372d25599541984941e09

**Comment by demosthenesk** [comment]
Yes it is fixed.
However i have issues with mate-terminal.
I tried to run app with:
1) "mate-terminal" --command "/home/user/freebasic/folder 1/hello"
and it fails.
2) xterm succeeds
"xterm" -bc "/home/user/freebasic/folder 1/hello"

**Comment by XusinboyBekchanov** [comment]
Added: mate-terminal and xterm to VisualFBEditor terminal settings in Linux:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/8d82c520a922bb893db469e3f0d10cef3f1af446

It was necessary to replace --command with --execute in the mate-terminal.

**Comment by demosthenesk** [comment]
nice.. it works with --execute
thanks !
