### ISSUE TITLE
Save dialog does not have a title to indicate what is been saved

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#99]
Hello,
i have a project with a form unsaved.
If i press Save All from menu, i get 2 save dialog forms without a title and i dont know what to save project or form.
It is a little confusing. After test i found out that the first dialog is for Project and second dialog is for form.

Please add title for saving each file to help developer to know what is doing.

**Comment by XusinboyBekchanov** [comment]
Added: Caption to Save Dialog:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/94094af3f4eff314f8c7398d34e7ddbf8c8c5523

**Comment by demosthenesk** [comment]
still no caption in linux save dialogs when press Save All.

**Comment by XusinboyBekchanov** [comment]
Fixed: Set initial dir to Save File Dialog:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/8c59e6758aa0d9293b97612474de3ba2b3e711ea

Fixed: Open and Save Dialogs Caption, Filter, FilterIndex, FileName and InitialDir properties in Linux:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/93a66e2865449d283e69be6d42f06763006208ee

This is the only way we can:
![Снимок экрана от 2021-08-22 20-38-51](https://user-images.githubusercontent.com/32607344/130361326-62d6abd0-6944-499c-9117-5fd07c621c45.png)

**Comment by XusinboyBekchanov** [comment]
Fixed: Open and Save File Dialog Filter property:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/d26df0f2a3c581bd766eaa2aa1bf3123ac065cab

**Comment by demosthenesk** [comment]
Yes it is better now. Work like a charm in Ubuntu Mate 20.04 LTS.
